export const adminNextCopy = {
  shell: {
    brandEyebrow: 'Bukeer Admin Next',
    productName: 'Human-Agent OS',
    modeLabel: 'Prototype mode',
    searchPlaceholder: 'Search leads, trips, suppliers',
    readOnlyStatus: 'Read-only',
    noWritesStatus: 'No writes',
    notificationsLabel: 'Notifications',
    nav: [
      { key: 'dashboard', label: 'Dashboard' },
      { key: 'planner', label: 'Planner' },
      { key: 'conversations', label: 'Conversaciones' },
      { key: 'contacts', label: 'Contactos' },
      { key: 'products', label: 'Productos' },
      { key: 'reports', label: 'Reportes' },
      { key: 'agenda', label: 'Agenda' },
      { key: 'account', label: 'Mi cuenta' },
      { key: 'settings', label: 'Configuracion' },
    ],
  },
  dashboard: {
    title: 'Dashboard',
    subtitle: 'Resumen operativo · Junio 2026',
    dateRange: 'Ultimos 30 dias',
    primaryAction: 'Nuevo itinerario',
    salesVsCostTitle: 'Ventas vs. costo',
    salesLegend: 'Ventas',
    costLegend: 'Costo',
    receivablesTitle: 'Cuentas por cobrar proximas',
    sellersTitle: 'Ranking de vendedores',
    activityTitle: 'Actividad reciente',
    aiPanelEyebrow: 'Panel contextual IA',
    aiPanelTitle: 'Senales operativas',
    aiPanelDescription:
      'Lectura grounded del dashboard: cobros vencidos, margen y actividad comercial.',
    viewReportAction: 'Ver reporte',
    monthLabels: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun'],
    metricTrend: (value: string) => `${value} vs. mayo`,
    targetProgress: (value: number) => `${value}% de la meta`,
  },
  conversations: {
    eyebrow: 'Bukeer CRM',
    title: 'Conversaciones',
    subtitle: 'CRM realtime · WhatsApp, email y solicitudes conectadas',
    primaryAction: 'Nueva solicitud',
    closeAction: 'Cerrar conversacion',
    inboxTitle: 'Inbox',
    threadTitle: 'Hilo activo',
    crmPanelTitle: 'Cliente y oportunidad',
    composerPlaceholder: 'Escribir respuesta o usar plantilla',
    sendAction: 'Enviar borrador',
    aiPanelEyebrow: 'Panel contextual IA',
    aiPanelTitle: 'Siguiente mejor accion',
    aiPanelDescription:
      'Lectura grounded del hilo, SLA y datos CRM. Ningun mensaje sale sin accion humana.',
    realtimeTitle: 'Mirror realtime',
    realtimeLatencyLabel: 'Latencia objetivo',
    qualificationTitle: 'Calificacion',
    linkedItineraryTitle: 'Itinerario vinculado',
    createRequestAction: 'Crear solicitud',
    templatesTitle: 'Plantillas',
    notesTitle: 'Notas CRM',
    idLabel: 'ID',
    phoneLabel: 'Telefono',
    emailLabel: 'Email',
    lastPurchaseLabel: 'Compra previa',
    marginLabel: 'Margen',
    closeModalTitle: 'Cerrar conversacion',
    closeModalSubtitle: 'El resultado queda auditado. No compro exige motivo.',
    closeSaveAction: 'Guardar cierre',
    closeCancelAction: 'Cancelar',
    reasonRequiredLabel: 'Motivo obligatorio para No compro',
    closeValidLabel: 'Cierre listo para guardar',
    closeOutcomeLabels: {
      won: 'Gano',
      no_purchase: 'No compro',
      not_qualified: 'No calificado',
    },
    statusLabels: {
      open: 'Abierta',
      waiting: 'En espera',
      closed: 'Cerrada',
    },
    channelLabels: {
      whatsapp: 'WhatsApp',
      email: 'Email',
      web: 'Web',
    },
    temperatureLabels: {
      cold: 'Frio',
      warm: 'Tibio',
      hot: 'Caliente',
    },
    unreadLabel: (count: number) => `${count} sin leer`,
  },
  contacts: {
    title: 'Contactos',
    subtitle: 'Clientes y proveedores · 1.248 registros',
    importAction: 'Importar CSV',
    primaryAction: 'Nuevo contacto',
    searchPlaceholder: 'Buscar por nombre, email o telefono',
    filters: [
      { key: 'all', label: 'Todos' },
      { key: 'clients', label: 'Clientes' },
      { key: 'providers', label: 'Proveedores' },
      { key: 'debt', label: 'Con deuda' },
    ],
    totalLabel: (count: number) => `${count} visibles`,
    itinerariesLabel: 'Itinerarios',
    balanceLabel: 'Saldo',
    totalSalesLabel: 'Ventas totales',
    cityLabel: 'Ciudad',
    openConversationAction: 'Abrir conversacion',
    newItineraryAction: 'Nuevo itinerario',
    timelineTitle: 'Itinerarios y pagos recientes',
    infoTitle: 'Informacion',
    documentLabel: 'Documento',
    emailLabel: 'Email',
    phoneLabel: 'Telefono',
    aiPanelEyebrow: 'Panel contextual IA',
    aiPanelTitle: 'Lectura del contacto',
    aiPanelDescription:
      'Senales accionables sobre saldo, proveedor vinculado y datos listos para operar.',
  },
  agenda: {
    title: 'Agenda de servicios',
    subtitle: 'Servicios programados · proximos 30 dias · 18 servicios',
    filters: [
      { key: 'all', label: 'Todos' },
      { key: 'flights', label: 'Vuelos' },
      { key: 'hotels', label: 'Hoteles' },
      { key: 'transport', label: 'Transporte' },
      { key: 'services', label: 'Servicios' },
    ],
    searchPlaceholder: 'Buscar por cliente, proveedor o producto',
    collapsedDayLabel: 'Servicios agrupados para revision posterior.',
    amountLabel: 'Total',
    serviceSubline: (supplier: string, customer: string) => `${supplier} · ${customer}`,
    itineraryLabel: (id: string) => `ID ${id}`,
    aiPanelEyebrow: 'Panel contextual IA',
    aiPanelTitle: 'Riesgos de operacion',
    aiPanelDescription:
      'Lectura de notificaciones, pagos de cliente y pendientes con proveedor para los proximos servicios.',
  },
  products: {
    title: 'Productos',
    subtitle: 'Catalogo operativo · hoteles, actividades, traslados y vuelos',
    importAction: 'Importar CSV',
    primaryAction: 'Nuevo producto',
    searchPlaceholder: 'Buscar por producto, ciudad o proveedor',
    cityFilterLabel: 'Ciudad · con productos',
    priceFilterLabel: 'Precio y tarifa',
    providerFilterLabel: 'Proveedor',
    tariffFilterLabel: 'Tarifa',
    clearFiltersAction: 'Limpiar filtros',
    appliedFiltersLabel: 'Filtros activos',
    urlStateLabel: 'URL-as-state activo',
    cityFilterOptions: [
      { key: 'cartagena', label: 'Cartagena', count: 2 },
      { key: 'san-andres', label: 'San Andres', count: 1 },
    ],
    providerFilterOptions: [
      { key: 'hotel-las-islas', label: 'Hotel Las Islas', count: 1 },
      { key: 'sea-tours', label: 'Sea Tours', count: 1 },
      { key: 'marsol', label: 'Marsol', count: 1 },
    ],
    tariffFilterOptions: [
      { key: 'active', label: 'Tarifa activa', count: 2 },
      { key: 'review', label: 'Revisar tarifa', count: 1 },
    ],
    priceRangeOptions: [
      { key: 'budget', label: 'Hasta $200k', max: 200000 },
      { key: 'mid', label: '$200k - $1.5M', min: 200000, max: 1500000 },
      { key: 'premium', label: 'Mas de $1.5M', min: 1500000 },
    ],
    resultsLabel: (count: number) => `${count} productos visibles`,
    fromLabel: 'Desde',
    editAction: 'Editar',
    newRateAction: 'Nueva tarifa',
    galleryTitle: 'Galeria',
    manageImagesAction: (count: number) => `Gestionar imagenes · ${count}`,
    galleryStatusLabel: (count: number) => `${count} de 10 imagenes`,
    galleryNoImagesStatus: 'Sin fotos maestro/override disponibles',
    catalogContractLabel: 'Catalogo V2',
    catalogContractValue: 'Resolver maestro/propio activo',
    mainImageLabel: 'Principal',
    restoreMasterImagesAction: 'Restablecer fotos del catalogo',
    ratesTitle: 'Tarifas',
    ratesSubtitle: 'Costo, margen y venta deben quedar visibles para operar.',
    activeRatesLabel: (count: number) => `${count} vigentes`,
    costLabel: 'Costo',
    marginLabel: 'Margen',
    saleLabel: 'Venta',
    providerTitle: 'Proveedor',
    operationsTitle: 'Detalles operativos',
    aiPanelEyebrow: 'Panel contextual IA',
    aiPanelTitle: 'Control del catalogo',
    aiPanelDescription:
      'Senales grounded sobre tarifas, fotos maestro/override y productos que requieren revision antes del corte.',
    cancelAction: 'Cancelar',
    closeAction: 'Cerrar',
    continueAction: 'Continuar',
    backAction: 'Volver',
    newProductTitle: 'Tipo de producto',
    newProductSubtitle: 'Selecciona la familia para crear el producto con el contrato de catalogo correcto.',
    productTypeHotel: 'Hotel',
    productTypeActivity: 'Actividad',
    productTypeTransfer: 'Traslado',
    newProductHint: 'El alta completa exige ubicacion, proveedor y al menos una tarifa activa.',
    newHotelTitle: 'Nuevo hotel',
    newHotelSubtitle: 'Stepper operativo para dejar el hotel vendible sin romper el catalogo maestro.',
    stepInfo: 'Info',
    stepLocation: 'Ubicacion',
    stepDetails: 'Detalles',
    stepProvider: 'Proveedor',
    sectionBasicInfo: 'Informacion base',
    sectionLocation: 'Ubicacion comercial',
    sectionServiceDetails: 'Detalles del servicio',
    sectionProviderStatus: 'Proveedor y estado',
    productNameLabel: 'Nombre del producto',
    shortDescriptionLabel: 'Descripcion corta',
    longDescriptionLabel: 'Descripcion larga',
    locationSearchLabel: 'Buscar ciudad, zona o hotel maestro',
    selectedLocation: 'Ubicacion seleccionada',
    includesLabel: 'Incluye',
    extraCostsLabel: 'Costos extra',
    recommendationsLabel: 'Recomendaciones',
    mandatoryRateNote: 'Al finalizar se pedira al menos una tarifa activa.',
    rateRequiredGateTitle: 'Tarifa obligatoria pendiente',
    rateRequiredGateDetail:
      'El producto queda en borrador operativo hasta registrar una tarifa activa.',
    rateReadyGateTitle: 'Tarifa activa lista',
    rateReadyGateDetail:
      'Guardar esta tarifa habilita el producto para ventas, catalogo y CRM.',
    finishHotelAction: 'Finalizar hotel',
    newRateTitle: 'Tarifas del hotel',
    newRateSubtitle: 'Precio = costo + margen. El resumen se recalcula al editar.',
    rateNameLabel: 'Nombre de tarifa',
    netCostLabel: 'Costo neto',
    currencyLabel: 'Moneda',
    priceCalculationLabel: 'Calculo del precio',
    fromMarginLabel: 'Desde margen',
    fromPriceLabel: 'Desde precio',
    marginPercentLabel: 'Margen %',
    gainLabel: 'Ganancia',
    roomTypeLabel: 'Tipo de habitacion',
    mealPlanLabel: 'Plan de alimentacion',
    capacityLabel: 'Capacidad',
    stateLabel: 'Estado',
    activeRateLabel: 'Activa',
    priceFormulaNote: 'Precio = costo + margen · se recalcula al editar',
    saveRateAction: 'Guardar tarifa',
    editProductTitle: 'Editar producto · Hotel',
    editProductSubtitle: 'El nombre del catalogo maestro queda bloqueado; los datos propios pueden sobrescribir la ficha operativa.',
    catalogNameLockedLabel: 'Nombre catalogo maestro bloqueado',
    deleteProductAction: 'Eliminar producto',
    saveChangesAction: 'Guardar cambios',
    galleryModalTitle: 'Gestionar imagenes',
    galleryModalSubtitle: 'Maximo 10 imagenes por producto. La principal alimenta catalogo, detalle y flyer CRM.',
    addImageAction: 'Agregar imagen',
    deleteImageAction: 'Eliminar',
    primaryImageLabel: 'Principal',
    autosaveLabel: 'Autosave activo',
    dragReorderLabel: 'Arrastra para reordenar',
    imageSlotLabel: (index: number) => `Imagen ${index}`,
    importCsvTitle: 'Importar productos CSV',
    importCsvSubtitle: 'Wizard de 3 pasos para cargar catalogo sin romper tarifas, proveedor ni ciudad.',
    importCsvUploadStep: 'Cargar archivo',
    importCsvMapStep: 'Mapear columnas',
    importCsvReviewStep: 'Revisar y confirmar',
    importCsvDropTitle: 'Arrastra el CSV o selecciona archivo',
    importCsvDropSubtitle: 'CSV UTF-8 con hoteles, actividades, traslados o vuelos. Maximo 2.000 filas por lote.',
    importCsvTemplateAction: 'Descargar plantilla',
    importCsvSelectedFile: 'productos_cartagena_junio.csv',
    importCsvRowsLabel: 'filas detectadas',
    importCsvWarningsLabel: 'avisos',
    importCsvErrorsLabel: 'errores bloqueantes',
    importCsvMappingTitle: 'Mapeo requerido',
    importCsvPreviewTitle: 'Vista previa del lote',
    importCsvResolverTitle: 'Resolver coincidencias',
    importCsvResolverSubtitle: 'Los nombres similares se enlazan al catalogo maestro; los nuevos quedan como propios.',
    importCsvResolverSourceLabel: 'Origen CSV',
    importCsvResolverMasterLabel: 'Catalogo maestro',
    importCsvResolverConfidenceLabel: 'Score',
    importCsvConfirmAction: 'Confirmar importacion',
    importCsvReadyLabel: 'Listo para importar',
    importCsvDuplicateLabel: 'Coincidencia probable',
    importCsvMissingRateLabel: 'Requiere tarifa',
    resolverActionLabels: {
      link: 'Vincular maestro',
      create: 'Crear propio',
      rate_required: 'Vincular + tarifa',
    },
    importCsvResultLabel: (count: number) => `${count} productos preparados`,
    importCsvMappings: [
      { source: 'nombre_producto', target: 'Nombre del producto', state: 'OK' },
      { source: 'categoria', target: 'Tipo de producto', state: 'OK' },
      { source: 'ciudad', target: 'Ubicacion', state: 'OK' },
      { source: 'proveedor', target: 'Proveedor', state: 'OK' },
      { source: 'costo_neto', target: 'Costo neto', state: 'OK' },
      { source: 'margen', target: 'Margen %', state: 'OK' },
    ],
    importCsvPreviewRows: [
      { name: 'Hotel Las Islas', type: 'Hotel', city: 'Baru, Cartagena', status: 'Coincidencia probable' },
      { name: 'Tour manglares Baru', type: 'Actividad', city: 'Cartagena', status: 'Listo para importar' },
      { name: 'Traslado aeropuerto hotel', type: 'Traslado', city: 'Cartagena', status: 'Requiere tarifa' },
    ],
  },
  reports: {
    eyebrow: 'Bukeer Intelligence',
    title: 'Reportes',
    subtitle: 'Hub operativo · ventas, rentabilidad, CxC, SLA y tesoreria',
    exportAction: 'Exportar CSV',
    filtersTitle: 'Filtros reproducibles',
    urlStateLabel: 'URL-as-state',
    urlStateDescription:
      'Reporte, rango y precio viajan en la URL para agentes, deep-links y auditoria.',
    insightsTitle: 'Lecturas accionables',
    tableTitle: 'Detalle operativo',
    aiPanelEyebrow: 'Panel contextual IA',
    aiPanelTitle: 'Riesgos y gates',
    aiPanelDescription:
      'Lectura grounded del reporte actual. SLA y Stripe fee quedan visibles como watches antes de corte.',
  },
  account: {
    title: 'Mi cuenta',
    subtitle: 'Perfil personal y preferencias · Carolina Ruiz',
    signOutAction: 'Cerrar sesion',
    profileTitle: 'Perfil',
    editProfileAction: 'Editar perfil',
    securityTitle: 'Seguridad',
    preferencesTitle: 'Preferencias',
    notificationsTitle: 'Notificaciones',
    signatureTitle: 'Firma en propuestas',
    changeAction: 'Cambiar',
    editAction: 'Editar',
  },
  settings: {
    title: 'Configuracion',
    subtitle: 'Ajustes base de agencia · lectura operativa',
    saveAction: 'Guardar cambios',
    agencyTitle: 'Agencia',
    agencyNameLabel: 'Nombre comercial',
    websiteLabel: 'Dominio principal',
    localeLabel: 'Idioma',
    currencyLabel: 'Moneda',
    rulesTitle: 'Reglas de negocio',
    billingTitle: 'Facturacion',
    teamTitle: 'Equipo y permisos',
    integrationsTitle: 'Integraciones',
    readOnlyLabel: 'Solo lectura',
  },
  tripRail: {
    eyebrow: 'Active travel opportunities',
    title: 'Planner queue',
    paxLabel: (count: number) => `${count} pax`,
    marginLabel: (value: string) => `${value} margin`,
  },
  workflow: {
    missingDataTitle: 'Missing data',
    marginGuardTitle: 'Margin guard',
    revenueLabel: 'Revenue',
    costLabel: 'Cost',
    profitLabel: 'Profit',
    currentMarginLabel: 'Current margin',
    targetLabel: 'Target',
    recoveryHint: 'Hotel swap suggestion can recover margin before public proposal send.',
  },
  agentCards: {
    reasoningSummaryTitle: 'Reasoning summary',
    traceAction: 'Trace',
    acceptDraftAction: 'Accept draft',
    rejectAction: 'Reject',
    inspectTraceAction: 'Inspect trace',
    requiredPrefix: 'Required',
    policyClearanceFallback: 'policy clearance',
    suggestionAcceptedMessage: 'Suggestion accepted locally. No backend write was executed.',
    suggestionRejectedMessage: 'Suggestion rejected locally. Feedback capture is not wired yet.',
  },
  approvalCommand: {
    traceAction: 'Trace',
    editApprovalAction: 'Edit approval',
    rejectAction: 'Reject',
    approveOnceAction: 'Approve once',
    approveWithEditsMessage: 'Approve with edits simulated locally. No write was sent.',
    rejectedMessage: 'Approval rejected locally. No workflow execution was triggered.',
    approvedMessage: 'Approval simulated locally. Execution remains disabled in this prototype.',
  },
  liveFeed: {
    eyebrow: 'Live supplier feed',
    title: 'Availability & margin',
    marginLabel: (value: string) => `${value} margin`,
    inspectTraceAction: 'Inspect trace',
  },
  planningCanvas: {
    title: 'Planner Workbench',
    slaLabel: 'SLA',
    valueLabel: 'Value',
    marginLabel: 'Margin',
    blockedTitle: 'Not ready to send',
    blockedDescription:
      'Public proposal send requires approval and missing passenger data resolution. This prototype is read-only.',
    manifestTitle: 'Itinerary Manifest',
    manifestDescription: 'Confirmed, suggested, blocked and approval-required segments',
    traceAction: 'Trace',
  },
  prototype: {
    hydratedLabel: 'Planner Workbench hydrated',
    appearanceLabel: 'Appearance',
    lightModeAction: 'Light',
    darkModeAction: 'Dark',
    whatsappHandoffFallbackError: 'Could not create WhatsApp handoff.',
    whatsappHandoffIncompleteError: 'WhatsApp handoff response was incomplete.',
  },
  traceDrawer: {
    inspectorPill: 'Inspector',
    traceAvailablePill: 'Trace available',
    title: 'Agent trace',
    description:
      'Human-visible audit of evidence, tool results and approval state. Hidden chain-of-thought is not shown.',
    closeAction: 'Close trace drawer',
    auditSequenceEyebrow: 'Audit sequence',
    timelineTitle: 'Trace timeline',
    runLabel: (agentRunId: string) => `Run ${agentRunId}`,
    evidenceReadyPill: 'Evidence ready',
    confidenceLabel: 'Confidence',
    permissionLabel: 'Permission',
    policyLabel: 'Policy',
    auditLabel: 'Audit',
    dataUsedTitle: 'Data used',
    approvalBoundaryTitle: 'Human approval boundary',
    approvalBoundaryDescription:
      'This drawer explains what the agent used and why the workflow remains gated. Customer-facing sends require explicit approval.',
  },
  signature: {
    statusLabels: {
      observed: 'Observed',
      suggested: 'AI suggestion',
      drafted: 'Drafted',
      blocked_missing_data: 'AI blocked',
      blocked_policy: 'Policy blocked',
      approval_required: 'Approval required',
      approved: 'Approved',
      executing: 'Executing',
      executed: 'Executed',
      rejected: 'Rejected',
      expired: 'Expiring',
    },
    variantDefaults: {
      loading: {
        title: 'Loading signature workspace',
        description: 'Fetching fixture context and preparing the human-agent controls.',
        badge: 'Loading',
      },
      empty: {
        title: 'No signature work queued',
        description: 'There are no planner opportunities ready for signature review.',
        badge: 'Empty',
      },
      error: {
        title: 'Signature state unavailable',
        description: 'The local prototype state could not be resolved.',
        badge: 'Error',
        actionLabel: 'Retry',
      },
      noPermission: {
        title: 'Permission required',
        description: 'This user cannot approve or execute this signature workflow.',
        badge: 'No permission',
      },
      approved: {
        title: 'Approved for execution',
        description: 'The human approval gate has been cleared.',
        badge: 'Approved',
      },
      rejected: {
        title: 'Rejected by reviewer',
        description: 'The proposal remains blocked and requires revision before execution.',
        badge: 'Rejected',
      },
      executing: {
        title: 'Executing approved action',
        description: 'The local prototype is showing execution-in-progress state only.',
        badge: 'Executing',
      },
      executed: {
        title: 'Execution complete',
        description: 'The approved workflow has completed in prototype state.',
        badge: 'Executed',
      },
    },
    draft: {
      fallbackStatus: 'Drafted',
      fallbackType: 'travel draft',
      bodyLabel: 'Draft body',
      needsReview: 'Needs review',
      localReviewValue: 'Editable in local review',
      handoffErrorFallback: 'Could not create WhatsApp handoff. Try again from local review.',
      humanReviewRequired: 'Human review is required before this draft can leave local review.',
      reviewDraftFields: 'Review draft fields before any customer or supplier action.',
      awaitingReviewTitle: 'Draft action awaiting planner review',
      inspectTraceAction: 'Inspect trace',
      requiredHumanActionTitle: 'Required human action',
      editableFieldsTitle: 'Editable fields',
      requiredPill: 'Required',
      statusLabel: (status: string) => `Status: ${status}`,
      noEditableFields: 'No editable fields were included in this draft payload.',
      safetyBoundary: 'Safety boundary: not sent, not reserved, not paid, not confirmed.',
      whatsappHandoffTitle: 'WhatsApp handoff',
      manualSendOnlyPill: 'Manual send only',
      manualSendDescription: 'Not sent. Human must open and send manually.',
      creatingHandoffAction: 'Creating handoff',
      handoffCreatedAction: 'WhatsApp handoff created',
      createHandoffAction: 'Create WhatsApp handoff',
      reviewAction: 'Review locally',
      editAction: 'Edit locally',
      discardAction: 'Discard locally',
      reviewedMessage: (id: string) =>
        `Reviewed draft ${id} locally. No send, reservation, payment or confirmation ran.`,
      editMessage: (id: string) =>
        `Opened local edit state for draft ${id}. No production write was executed.`,
      discardMessage: (id: string) =>
        `Discarded draft ${id} locally. No production record was deleted.`,
      panelEyebrow: 'Draft-only actions',
      panelTitle: 'Bukeer DraftAction review',
      localSimulationPill: 'Local simulation only',
    },
    whatsappHandoff: {
      creatingTitle: 'Creating WhatsApp handoff',
      manualSendDescription: 'Not sent. Human must open and send manually.',
      errorTitle: 'WhatsApp handoff was not created',
      immutableBoundary: 'Not sent, not reserved, not paid, not confirmed.',
      successTitle: 'WhatsApp handoff created',
      notSentPill: 'Not sent',
      successDescription:
        'Human must open and send manually. This is not reserved, not paid, not confirmed.',
      referenceLabel: 'Reference',
      waMeLabel: 'wa.me',
      expiresAtLabel: 'Expires at',
      noExpiryFallback: 'No expiry returned',
    },
    header: {
      productPill: 'Human-Agent OS',
      blockedPill: 'Not ready to send',
      tracePill: 'Trace available',
      title: 'Planner Workbench',
      quotedLabel: 'Quoted',
      marginLabel: 'Margin',
      slaLabel: 'SLA',
    },
    rail: {
      eyebrow: 'Planner queue',
      title: 'Bukeer travel desk',
      searchPlaceholder: 'Search trips...',
    },
    blockedBanner: {
      title: 'Public proposal send is blocked',
      missingFieldsPill: (count: number) => `${count} fields missing`,
    },
    manifest: {
      eyebrow: 'Client itinerary state',
      title: 'Itinerary Manifest',
      inspectTraceAction: 'Inspect trace',
      marginLabel: (value: string) => `${value} margin`,
    },
    copilot: {
      title: 'Conversation Copilot',
      suggestionPill: 'AI suggestion',
      inspectTraceAction: 'Inspect trace',
    },
    tracePreview: {
      eyebrow: 'Governance',
      title: 'Trace & approval chain',
      humanLoopPill: 'Human loop',
      inspectTraceAction: 'Inspect trace',
    },
    liveFeedPanel: {
      eyebrow: 'Live feed',
      title: 'Supplier intelligence',
      livePill: 'Live',
      inspectTraceAction: 'Inspect trace',
    },
    marginGuard: {
      title: 'Margin guard',
      revenueLabel: 'Revenue',
      costLabel: 'Cost',
      profitLabel: 'Profit',
      targetDescription: (target: string) =>
        `Target margin: ${target}. Manager approval is required before any customer-facing send.`,
    },
    missingData: {
      title: 'Missing data',
    },
    approvalBar: {
      requiredTitle: 'Approval required',
      riskLabel: (risks: string) => `Risk: ${risks}`,
      permissionLabel: (permission: string) => `Permission: ${permission}`,
      inspectTraceAction: 'Inspect trace',
      rejectAction: 'Reject',
      approveOnceAction: 'Approve once',
      rejectedMessage: 'Rejected locally. No production write was executed.',
      approvedMessage: 'Approved locally for prototype review. Execution remains blocked.',
    },
  },
} as const;

export type AdminNextCopy = typeof adminNextCopy;
