// Data for ColombiaTours site
// Scenic backgrounds are CSS-only gradient "placeholders" — styled to evoke
// different Colombian regions. Real photography would slot in here later.

const DESTINATIONS = [
  {
    id: "cartagena",
    name: "Cartagena",
    tag: "Caribe colonial",
    subtitle: "Ciudad amurallada · 3–5 días",
    emphasis: "de Indias",
    region: "Caribe",
    scene: {
      bg: "linear-gradient(155deg, #0a3a5c 0%, #0e5b7e 35%, #d9a25b 75%, #f0c27b 100%)",
      layers: [
        { type: "rect", style: { left: "8%", bottom: 0, right: "48%", height: "42%", background: "linear-gradient(180deg, rgba(232,168,106,.9), rgba(190,110,70,.92))" }},
        { type: "rect", style: { left: "55%", bottom: 0, right: 0, height: "38%", background: "linear-gradient(180deg, rgba(216,148,92,.9), rgba(170,95,55,.92))" }},
        { type: "rect", style: { left: "16%", bottom: "34%", width: "14%", height: "22%", background: "rgba(238,196,140,.92)" }},
        { type: "rect", style: { left: "60%", bottom: "30%", width: "18%", height: "28%", background: "rgba(226,174,120,.92)" }},
        { type: "circle", style: { right: "12%", top: "16%", width: 90, height: 90, background: "radial-gradient(circle, #fde7b3, #f3b13b)", opacity: .85 }},
      ],
    },
  },
  {
    id: "san-andres",
    name: "San Andrés",
    emphasis: "& Providencia",
    tag: "Mar de 7 colores",
    subtitle: "Isla · 4–6 días",
    region: "Caribe",
    scene: {
      bg: "linear-gradient(180deg, #59cde8 0%, #1a9bc6 35%, #0d5c7a 75%, #0a3d52 100%)",
      layers: [
        { type: "rect", style: { left: 0, right: 0, bottom: "26%", height: "2%", background: "rgba(255,255,255,.28)" }},
        { type: "rect", style: { left: "10%", right: "20%", bottom: "12%", height: "4%", background: "rgba(161,222,196,.7)", borderRadius: "50%" }},
        { type: "circle", style: { left: "15%", top: "18%", width: 70, height: 70, background: "radial-gradient(circle, #fff7d8, #fff085)", opacity: .9 }},
      ],
    },
  },
  {
    id: "eje-cafetero",
    name: "Eje Cafetero",
    tag: "Paisaje cultural",
    subtitle: "Quindío · Salento · 3 días",
    region: "Andes",
    scene: {
      bg: "linear-gradient(170deg, #93c084 0%, #568b4a 40%, #2f5b34 80%)",
      layers: [
        { type: "rect", style: { left: 0, right: 0, bottom: 0, height: "48%", background: "linear-gradient(180deg, rgba(71,120,64,.92), rgba(40,72,42,.95))" }},
        { type: "rect", style: { left: "12%", bottom: "40%", width: 3, height: "38%", background: "rgba(247,230,180,.95)", boxShadow: "0 0 20px rgba(247,230,180,.4)" }},
        { type: "rect", style: { left: "32%", bottom: "30%", width: 3, height: "50%", background: "rgba(247,230,180,.95)" }},
        { type: "rect", style: { left: "52%", bottom: "35%", width: 3, height: "42%", background: "rgba(247,230,180,.95)" }},
        { type: "rect", style: { left: "72%", bottom: "32%", width: 3, height: "48%", background: "rgba(247,230,180,.95)" }},
      ],
    },
  },
  {
    id: "tayrona",
    name: "Tayrona",
    tag: "Selva · costa",
    subtitle: "Santa Marta · 2–4 días",
    region: "Caribe",
    scene: {
      bg: "linear-gradient(180deg, #a5d8c2 0%, #3e9b7a 35%, #18554a 75%, #0a2f2a 100%)",
      layers: [
        { type: "rect", style: { left: 0, right: 0, bottom: 0, height: "32%", background: "linear-gradient(180deg, rgba(210,188,130,.9), rgba(180,150,90,.95))" }},
        { type: "circle", style: { left: "-10%", bottom: "22%", width: 220, height: 220, background: "rgba(12,60,50,.7)" }},
        { type: "circle", style: { right: "-15%", bottom: "18%", width: 280, height: 280, background: "rgba(14,70,55,.65)" }},
      ],
    },
  },
  {
    id: "medellin",
    name: "Medellín",
    tag: "Ciudad primavera",
    subtitle: "Antioquia · 2–3 días",
    region: "Andes",
    scene: {
      bg: "linear-gradient(165deg, #e0a3b0 0%, #b46d83 40%, #553a5c 80%, #241a35 100%)",
      layers: [
        { type: "rect", style: { left: "4%", bottom: 0, width: "10%", height: "48%", background: "rgba(35,28,50,.9)" }},
        { type: "rect", style: { left: "18%", bottom: 0, width: "14%", height: "62%", background: "rgba(45,32,58,.9)" }},
        { type: "rect", style: { left: "36%", bottom: 0, width: "8%", height: "40%", background: "rgba(35,28,50,.9)" }},
        { type: "rect", style: { left: "48%", bottom: 0, width: "18%", height: "72%", background: "rgba(55,40,70,.92)" }},
        { type: "rect", style: { left: "70%", bottom: 0, width: "12%", height: "52%", background: "rgba(40,30,55,.9)" }},
        { type: "rect", style: { left: "86%", bottom: 0, width: "10%", height: "42%", background: "rgba(35,28,50,.9)" }},
      ],
    },
  },
  {
    id: "guatape",
    name: "Guatapé",
    tag: "Peñón · embalse",
    subtitle: "Antioquia · 1–2 días",
    region: "Andes",
    scene: {
      bg: "linear-gradient(180deg, #93b9cc 0%, #3e7591 40%, #1d4058 80%)",
      layers: [
        { type: "circle", style: { left: "38%", bottom: "20%", width: 160, height: 220, background: "linear-gradient(180deg, #576e6c, #2a3a3c)", borderRadius: "40% 40% 50% 50% / 60% 60% 40% 40%" }},
        { type: "rect", style: { left: 0, right: 0, bottom: 0, height: "22%", background: "linear-gradient(180deg, rgba(40,75,95,.75), rgba(20,40,55,.95))" }},
      ],
    },
  },
  {
    id: "desierto",
    name: "La Guajira",
    tag: "Desierto · mar",
    subtitle: "Cabo de la Vela · 4 días",
    region: "Caribe",
    scene: {
      bg: "linear-gradient(180deg, #f7d8a0 0%, #e09a58 35%, #a04b2f 80%)",
      layers: [
        { type: "rect", style: { left: 0, right: 0, bottom: 0, height: "30%", background: "linear-gradient(180deg, rgba(170,85,50,.7), rgba(90,40,25,.9))" }},
        { type: "circle", style: { right: "14%", top: "14%", width: 110, height: 110, background: "radial-gradient(circle, #fff4cf, #f5bf5a)", opacity: .85 }},
      ],
    },
  },
  {
    id: "amazonas",
    name: "Amazonas",
    tag: "Leticia · selva",
    subtitle: "Amazonas · 4–6 días",
    region: "Selva",
    scene: {
      bg: "linear-gradient(180deg, #7ba878 0%, #2c5a34 50%, #12301a 90%)",
      layers: [
        { type: "rect", style: { left: 0, right: 0, bottom: 0, height: "58%", background: "linear-gradient(180deg, rgba(30,70,40,.55), rgba(8,24,14,.92))" }},
        { type: "circle", style: { left: "12%", top: "22%", width: 90, height: 90, background: "rgba(20,50,30,.8)" }},
        { type: "circle", style: { right: "8%", top: "18%", width: 140, height: 140, background: "rgba(25,55,32,.8)" }},
      ],
    },
  },
];

const PACKAGES = [
  {
    id: "p1",
    title: "Caribe Esencial",
    subtitle: "Cartagena · Islas del Rosario · San Andrés",
    loc: "Caribe Colombiano",
    days: 7, nights: 6, group: "2–8 pax",
    price: 1890, currency: "USD", rating: 4.9, reviews: 284,
    badges: ["Más vendido"],
    type: "playa",
    dest: DESTINATIONS[0],
    includes: ["Vuelos domésticos", "6 noches hotel 4★", "Tour ciudad amurallada", "Navegación Islas del Rosario", "Desayunos"],
    itinerary: [
      { d: "Día 01", t: "Llegada a Cartagena", b: "Traslado privado + cena de bienvenida en la ciudad amurallada." },
      { d: "Día 02", t: "City tour colonial", b: "San Pedro Claver, Las Bóvedas, Palacio de la Inquisición y Getsemaní." },
      { d: "Día 03", t: "Islas del Rosario", b: "Navegación de día completo, almuerzo en Cholón." },
      { d: "Día 04", t: "Vuelo a San Andrés", b: "Traslado a hotel frente al mar, tarde libre en Spratt Bight." },
      { d: "Día 05", t: "Johnny Cay + acuario", b: "Tour en lancha al mar de siete colores." },
      { d: "Día 06", t: "Hoyo Soplador", b: "Vuelta a la isla en mulita, atardecer en West View." },
      { d: "Día 07", t: "Regreso", b: "Traslado al aeropuerto." },
    ],
  },
  {
    id: "p2",
    title: "Cafeteros & Cocora",
    subtitle: "Salento · Valle de Cocora · Filandia",
    loc: "Eje Cafetero",
    days: 5, nights: 4, group: "2–6 pax",
    price: 1290, currency: "USD", rating: 4.8, reviews: 196,
    badges: ["Eco"],
    type: "cultura",
    dest: DESTINATIONS[2],
    includes: ["Traslados 4x4", "Finca boutique 4 noches", "Tour del café de origen", "Caminata Cocora", "Desayunos + 2 cenas"],
    itinerary: [
      { d: "Día 01", t: "Llegada a Pereira", b: "Traslado a finca boutique en Salento." },
      { d: "Día 02", t: "Tour del café", b: "De la semilla a la taza en hacienda tradicional." },
      { d: "Día 03", t: "Valle de Cocora", b: "Caminata entre palmas de cera (árbol nacional)." },
      { d: "Día 04", t: "Filandia y Barcelona", b: "Pueblos cafeteros y miradores." },
      { d: "Día 05", t: "Regreso", b: "Desayuno y traslado al aeropuerto." },
    ],
  },
  {
    id: "p3",
    title: "Aventura Tayrona",
    subtitle: "Santa Marta · Minca · Parque Tayrona",
    loc: "Sierra Nevada",
    days: 6, nights: 5, group: "2–10 pax",
    price: 1490, currency: "USD", rating: 4.7, reviews: 152,
    badges: ["Aventura"],
    type: "aventura",
    dest: DESTINATIONS[3],
    includes: ["Glamping 3 noches", "Hotel Santa Marta 2 noches", "Entradas parque", "Guía certificado"],
    itinerary: [
      { d: "Día 01", t: "Llegada a Santa Marta", b: "Tarde libre en el centro histórico." },
      { d: "Día 02", t: "Minca + cascadas", b: "Finca cafetera y cascadas de Marinka." },
      { d: "Día 03", t: "Entrada a Tayrona", b: "Caminata Cañaveral — Arrecifes — Cabo San Juan." },
      { d: "Día 04", t: "Playa y Pueblito", b: "Ascenso al pueblo Tayrona ancestral." },
      { d: "Día 05", t: "Salida del parque", b: "Regreso a Santa Marta, tarde en Taganga." },
      { d: "Día 06", t: "Regreso", b: "Traslado al aeropuerto." },
    ],
  },
  {
    id: "p4",
    title: "Medellín Vibrante",
    subtitle: "Comuna 13 · Guatapé · Botero",
    loc: "Antioquia",
    days: 4, nights: 3, group: "2–8 pax",
    price: 890, currency: "USD", rating: 4.8, reviews: 221,
    badges: ["City"],
    type: "cultura",
    dest: DESTINATIONS[4],
    includes: ["Hotel Poblado 4★", "Tour Comuna 13", "Día Guatapé + Peñón", "Metrocable Arví"],
    itinerary: [
      { d: "Día 01", t: "Llegada a Medellín", b: "Traslado a El Poblado." },
      { d: "Día 02", t: "Comuna 13", b: "Tour de graffiti y escaleras eléctricas." },
      { d: "Día 03", t: "Guatapé", b: "Ascenso al Peñón + paseo por el pueblo de zócalos." },
      { d: "Día 04", t: "Metrocable + regreso", b: "Parque Arví y traslado al aeropuerto." },
    ],
  },
  {
    id: "p5",
    title: "Guajira Ancestral",
    subtitle: "Riohacha · Cabo de la Vela · Punta Gallinas",
    loc: "Alta Guajira",
    days: 5, nights: 4, group: "4–12 pax",
    price: 1390, currency: "USD", rating: 4.6, reviews: 88,
    badges: ["Off-grid"],
    type: "aventura",
    dest: DESTINATIONS[6],
    includes: ["Transporte 4x4", "Ranchería Wayúu", "Comidas regionales", "Guía bilingüe"],
    itinerary: [
      { d: "Día 01", t: "Llegada Riohacha", b: "Atardecer en el muelle + cena." },
      { d: "Día 02", t: "Cabo de la Vela", b: "Ruta por el desierto, Pilón de Azúcar." },
      { d: "Día 03", t: "Punta Gallinas", b: "Dunas de Taroa, punto más al norte de Sudamérica." },
      { d: "Día 04", t: "Ranchería Wayúu", b: "Inmersión cultural, artesanía y lengua wayuunaiki." },
      { d: "Día 05", t: "Regreso a Riohacha", b: "Traslado al aeropuerto." },
    ],
  },
  {
    id: "p6",
    title: "Amazonas Profundo",
    subtitle: "Leticia · Puerto Nariño · Tarapoto",
    loc: "Trapecio Amazónico",
    days: 5, nights: 4, group: "2–8 pax",
    price: 1590, currency: "USD", rating: 4.9, reviews: 134,
    badges: ["Eco", "Comunidad"],
    type: "naturaleza",
    dest: DESTINATIONS[7],
    includes: ["Lodge en la selva", "Navegación río Amazonas", "Avistamiento delfines rosados", "Guía indígena"],
    itinerary: [
      { d: "Día 01", t: "Leticia", b: "Parque Santander al atardecer (loros)." },
      { d: "Día 02", t: "Puerto Nariño", b: "Navegación, comunidad tikuna." },
      { d: "Día 03", t: "Lagos de Tarapoto", b: "Delfines rosados y victoria regia." },
      { d: "Día 04", t: "Selva profunda", b: "Caminata nocturna con guía indígena." },
      { d: "Día 05", t: "Regreso", b: "Traslado al aeropuerto." },
    ],
  },
];

const ACTIVITIES = [
  {
    id: "a1", title: "Caminata al Valle de Cocora", subtitle: "al amanecer, sin turistas",
    loc: "Salento, Quindío", region: "Eje Cafetero",
    cat: "aventura", level: "moderado", bucket: "full-day",
    dur: "6 h", durMin: 360, price: 65, rating: 4.9, reviews: 218,
    badges: ["Imprescindible"],
    desc: "Ruta circular entre palmas de cera y bosque nublado. Salida a las 5:45am desde Salento para llegar antes que los buses turísticos.",
    highlights: ["Palmas de cera (árbol nacional)", "Santuario de colibríes", "Cruces de río con puentes colgantes"],
    includes: ["Guía bilingüe", "Entrada al valle", "Snack energético"],
    time: "05:45", dest: DESTINATIONS[2],
  },
  {
    id: "a2", title: "Navegación a Islas del Rosario", subtitle: "en velero privado",
    loc: "Cartagena", region: "Caribe",
    cat: "mar", level: "fácil", bucket: "full-day",
    dur: "8 h", durMin: 480, price: 180, rating: 4.8, reviews: 412,
    badges: ["Más vendido"],
    desc: "Día completo en catamarán con anclaje en Cholón, almuerzo caribeño a bordo y tiempo para snorkel en arrecife.",
    highlights: ["Snorkel en arrecife", "Almuerzo a bordo", "Playa blanca en Cholón"],
    includes: ["Velero + tripulación", "Almuerzo y bebidas", "Equipo de snorkel"],
    time: "08:00", dest: DESTINATIONS[0],
  },
  {
    id: "a3", title: "Tour de café de origen", subtitle: "de la semilla a la taza",
    loc: "Salento, Quindío", region: "Eje Cafetero",
    cat: "gastronomia", level: "fácil", bucket: "half-day",
    dur: "3 h", durMin: 180, price: 45, rating: 4.9, reviews: 176,
    badges: [],
    desc: "Visita a finca tradicional con un caficultor de tercera generación. Recolección, despulpe, secado y cata guiada.",
    highlights: ["Cata comparativa 3 procesos", "Recolección en cafetal", "Conversación con el caficultor"],
    includes: ["Transporte desde Salento", "Cata + almuerzo típico"],
    time: "09:30", dest: DESTINATIONS[2],
  },
  {
    id: "a4", title: "Avistamiento de delfines rosados", subtitle: "en los lagos de Tarapoto",
    loc: "Puerto Nariño, Amazonas", region: "Amazonas",
    cat: "naturaleza", level: "fácil", bucket: "full-day",
    dur: "6 h", durMin: 360, price: 95, rating: 4.7, reviews: 94,
    badges: ["Eco"],
    desc: "Navegación en bote pequeño por los lagos de Tarapoto con biólogo local. Época alta Oct–Abr.",
    highlights: ["Delfines rosados (Inia)", "Victoria regia", "Comunidad Ticuna"],
    includes: ["Bote + biólogo guía", "Entrada a comunidad", "Almuerzo"],
    time: "07:00", dest: DESTINATIONS[7],
  },
  {
    id: "a5", title: "Free walking tour Comuna 13", subtitle: "con guía que creció ahí",
    loc: "Medellín, Antioquia", region: "Andes",
    cat: "cultura", level: "fácil", bucket: "short",
    dur: "2.5 h", durMin: 150, price: 0, rating: 4.8, reviews: 521,
    badges: ["Gratis", "Comunidad"],
    desc: "Recorrido a pie por la historia de la Comuna 13 contada por guías locales. Propina sugerida al final.",
    highlights: ["Escaleras eléctricas", "Graffitour", "Historia de la ciudad"],
    includes: ["Guía local", "Parada hip-hop"],
    time: "10:00", dest: DESTINATIONS[4],
  },
  {
    id: "a6", title: "Ascenso al Peñón de Guatapé", subtitle: "740 escalones y la mejor vista",
    loc: "Guatapé, Antioquia", region: "Andes",
    cat: "aventura", level: "moderado", bucket: "half-day",
    dur: "4 h", durMin: 240, price: 55, rating: 4.6, reviews: 302,
    badges: [],
    desc: "Día desde Medellín al embalse. Ascenso al Peñón y paseo por el pueblo de zócalos.",
    highlights: ["740 escalones", "Embalse desde arriba", "Pueblo de zócalos"],
    includes: ["Transporte ida/vuelta", "Entrada al Peñón", "Almuerzo típico"],
    time: "07:30", dest: DESTINATIONS[5],
  },
  {
    id: "a7", title: "Taller de cocina caribeña", subtitle: "con pescador y cocinera de Getsemaní",
    loc: "Cartagena", region: "Caribe",
    cat: "gastronomia", level: "fácil", bucket: "half-day",
    dur: "4 h", durMin: 240, price: 85, rating: 5.0, reviews: 67,
    badges: ["Nuevo"],
    desc: "Del mercado de Bazurto a la mesa. Compra con un chef local y cocina en casa patrimonial.",
    highlights: ["Mercado de Bazurto", "Cazuela de mariscos", "Patio colonial"],
    includes: ["Ingredientes", "Clase + almuerzo", "Receta digital"],
    time: "09:00", dest: DESTINATIONS[0],
  },
  {
    id: "a8", title: "Retiro de 2 días en la Sierra Nevada", subtitle: "silencio, río y mambeo",
    loc: "Minca, Magdalena", region: "Caribe",
    cat: "bienestar", level: "moderado", bucket: "multi-day",
    dur: "2 días", durMin: 2880, price: 390, rating: 4.9, reviews: 48,
    badges: ["Premium"],
    desc: "Dos días en eco-lodge kogui. Yoga matinal, caminatas, río y conversación con mamo.",
    highlights: ["Eco-lodge en la sierra", "Yoga + meditación", "Encuentro con mamo"],
    includes: ["1 noche lodge", "Todas las comidas", "Talleres"],
    time: "—", dest: DESTINATIONS[3],
  },
  {
    id: "a9", title: "Buceo en San Andrés", subtitle: "dos inmersiones para principiantes",
    loc: "San Andrés", region: "Caribe",
    cat: "mar", level: "moderado", bucket: "full-day",
    dur: "5 h", durMin: 300, price: 145, rating: 4.8, reviews: 134,
    badges: [],
    desc: "Bautismo + inmersión guiada con instructor PADI en arrecifes de poca profundidad.",
    highlights: ["Arrecife West Bay", "Tortugas marinas", "Visibilidad 30m"],
    includes: ["Equipo completo", "2 inmersiones", "Refrigerio"],
    time: "08:30", dest: DESTINATIONS[1],
  },
  {
    id: "a10", title: "Ascenso a Pueblito Chairama", subtitle: "arqueología Tayrona",
    loc: "Parque Tayrona", region: "Caribe",
    cat: "aventura", level: "exigente", bucket: "full-day",
    dur: "8 h", durMin: 480, price: 75, rating: 4.7, reviews: 89,
    badges: [],
    desc: "Ascenso técnico desde Cabo San Juan al asentamiento prehispánico Tayrona. Recomendado con condición física.",
    highlights: ["Terrazas precolombinas", "Canales de agua antiguos", "Bosque húmedo"],
    includes: ["Guía certificado", "Entrada al parque", "Almuerzo + snacks"],
    time: "06:00", dest: DESTINATIONS[3],
  },
  {
    id: "a11", title: "Visita a San Basilio de Palenque", subtitle: "primer pueblo libre de América",
    loc: "Bolívar (1h de Cartagena)", region: "Caribe",
    cat: "cultura", level: "fácil", bucket: "full-day",
    dur: "7 h", durMin: 420, price: 110, rating: 4.9, reviews: 72,
    badges: ["Comunidad"],
    desc: "Patrimonio UNESCO. Encuentro con líderes, música de tambor, clase de lengua palenquera.",
    highlights: ["Música en vivo", "Lengua palenquera", "Historia viva"],
    includes: ["Transporte privado", "Guía local", "Almuerzo en casa palenquera"],
    time: "08:00", dest: DESTINATIONS[0],
  },
  {
    id: "a12", title: "Caminata nocturna en la selva", subtitle: "con guía indígena tikuna",
    loc: "Leticia, Amazonas", region: "Amazonas",
    cat: "naturaleza", level: "moderado", bucket: "short",
    dur: "3 h", durMin: 180, price: 65, rating: 4.8, reviews: 56,
    badges: ["Eco"],
    desc: "Caminata nocturna por senderos en la selva primaria. Fauna nocturna y plantas medicinales.",
    highlights: ["Ranas, insectos, serpientes", "Saberes ancestrales", "Selva en su horario real"],
    includes: ["Guía indígena", "Linterna + botas", "Refrigerio"],
    time: "19:30", dest: DESTINATIONS[7],
  },
  {
    id: "a13", title: "Clase de salsa caleña", subtitle: "en una academia real",
    loc: "Cali, Valle", region: "Andes",
    cat: "cultura", level: "fácil", bucket: "short",
    dur: "2 h", durMin: 120, price: 30, rating: 4.7, reviews: 143,
    badges: [],
    desc: "Clase grupal en academia de barrio con bailarines profesionales. Opción de salir a bailar después.",
    highlights: ["Pasos base y giros", "Música en vivo", "Academia local"],
    includes: ["Clase 90min", "Bebida de bienvenida"],
    time: "18:00", dest: DESTINATIONS[4],
  },
  {
    id: "a14", title: "Parapente en el Chicamocha", subtitle: "vuelo sobre el cañón",
    loc: "San Gil, Santander", region: "Andes",
    cat: "aventura", level: "exigente", bucket: "half-day",
    dur: "3 h", durMin: 180, price: 120, rating: 4.8, reviews: 108,
    badges: ["Adrenalina"],
    desc: "Vuelo biplaza sobre el cañón del Chicamocha con piloto certificado. 20–30 minutos en el aire.",
    highlights: ["Cañón del Chicamocha", "Vuelo 20–30min", "Fotos y video incluidos"],
    includes: ["Piloto certificado", "Seguro", "Traslado desde San Gil"],
    time: "—", dest: DESTINATIONS[2],
  },
];

const PLANNERS = [
  {
    id: "pl1", name: "Mariana Vélez", role: "Especialista Caribe",
    base: "Cartagena", langs: ["ES", "EN", "FR"], years: 8,
    av: "linear-gradient(135deg, #f3b13b, #e85c3c)",
    regions: ["Cartagena", "Santa Marta", "San Andrés", "Guajira"],
    specialties: ["Lunas de miel", "Familias", "Gastronomía"],
    styles: ["boutique", "cultura", "playa"],
    rating: 4.98, reviews: 412, trips: 186,
    response: "< 15 min",
    quote: "Cartagena es mi ciudad. Conozco al chef que hace el mejor ceviche, al guía que sabe la historia de cada piedra, y los bares donde suena vallenato de verdad.",
    bio: "Nacida en Getsemaní, Mariana creció entre bailes de champeta y barcos que entraban a la bahía. Estudió Relaciones Internacionales en París, trabajó tres años en hotelería de lujo en la Riviera Francesa y volvió a Cartagena en 2018 para diseñar viajes que mostraran su Caribe — el real, no el de postal.",
    hallmarks: ["p2", "p1", "p3"],
    signature: { title: "Caribe Esencial", note: "Itinerario firma — Cartagena + Barú + Tayrona en 9 días." },
    funFacts: [
      "Colecciona discos de vinilo salseros de los 70.",
      "Su ceviche favorito es el de la Plaza Trinidad a las 10pm.",
      "Corrió la media maratón de Cartagena dos veces.",
    ],
    availability: "Libre desde 15 may 2026",
    destScene: 0,
  },
  {
    id: "pl2", name: "Andrés Restrepo", role: "Eje Cafetero & Andes",
    base: "Salento, Quindío", langs: ["ES", "EN"], years: 11,
    av: "linear-gradient(135deg, #6ea842, #1a5c3a)",
    regions: ["Eje Cafetero", "Bogotá", "Boyacá", "Santander"],
    specialties: ["Café de especialidad", "Senderismo", "Grupos pequeños"],
    styles: ["naturaleza", "cultura", "aventura"],
    rating: 4.97, reviews: 528, trips: 243,
    response: "< 1 h",
    quote: "Mi abuelo tostaba café en una paila de hierro. Yo sé a qué altura, a qué hora y con quién hay que tomarlo para entender por qué Colombia huele a esto.",
    bio: "Tercera generación de caficultores en Salento. Ingeniero agrónomo con especialización en catación. Desde 2014 diseña rutas que mezclan fincas familiares con senderos altos del Parque Los Nevados. Habla inglés que aprendió atendiendo turistas mochileros en los 2000.",
    hallmarks: ["p4", "p3", "p5"],
    signature: { title: "Cafeteros & Cocora", note: "Itinerario firma — 7 días entre palmas de cera, fincas y catación." },
    funFacts: [
      "Tiene 6 hectáreas de café caturra.",
      "Ha guiado a tres campeones mundiales de barismo.",
      "Habla quechua básico — aprendió en un intercambio en Perú.",
    ],
    availability: "Libre desde 1 jun 2026",
    destScene: 2,
  },
  {
    id: "pl3", name: "Luisa Carrizosa", role: "Amazonas & Pacífico",
    base: "Leticia, Amazonas", langs: ["ES", "EN", "PT"], years: 6,
    av: "linear-gradient(135deg, #2d8aaf, #0e4d6b)",
    regions: ["Amazonas", "Pacífico", "Chocó", "Nuquí"],
    specialties: ["Avistamiento de ballenas", "Selva con comunidad", "Fotografía"],
    styles: ["naturaleza", "ecoturismo", "cultura"],
    rating: 4.99, reviews: 186, trips: 94,
    response: "< 2 h",
    quote: "La selva no se recorre — se escucha. Mi trabajo es enseñarte a bajar el volumen para que ella suba el suyo.",
    bio: "Biológa marina bogotana que se enamoró del Amazonas en su tesis y ya no volvió. Vive entre Leticia y Nuquí según la temporada de ballenas. Trabaja mano a mano con cabildos Ticuna y Emberá para diseñar experiencias que benefician directo a las comunidades.",
    hallmarks: ["p6", "p1"],
    signature: { title: "Amazonas Profundo", note: "Itinerario firma — 6 días río adentro con guía Ticuna." },
    funFacts: [
      "Identifica 80+ aves solo por su canto.",
      "Es fotógrafa publicada en BBC Wildlife.",
      "Tiene una canoa llamada 'Manatí' en Puerto Nariño.",
    ],
    availability: "Libre desde 20 may 2026",
    destScene: 5,
  },
  {
    id: "pl4", name: "Juan David Ortiz", role: "Aventura & Trekking",
    base: "Santa Marta", langs: ["ES", "EN", "DE"], years: 9,
    av: "linear-gradient(135deg, #9c5f2d, #4a2d15)",
    regions: ["Sierra Nevada", "Tayrona", "Cocuy", "San Gil"],
    specialties: ["Multi-día trekking", "Ciudad Perdida", "Aventura exigente"],
    styles: ["aventura", "naturaleza"],
    rating: 4.96, reviews: 312, trips: 158,
    response: "< 30 min",
    quote: "Caminar la Sierra es caminar con los abuelos. Acá todo tiene dueño invisible y si pides permiso, la montaña se abre.",
    bio: "Samario, guía certificado de alta montaña por la Federación Colombiana de Montañismo. Vivió dos años en Múnich (de ahí el alemán) trabajando en una escuela de escalada. De regreso, se especializó en la Sierra Nevada trabajando con los cuatro pueblos indígenas guardianes.",
    hallmarks: ["p1", "p2"],
    signature: { title: "Ciudad Perdida Expedition", note: "Itinerario firma — 4 días de trek a la Teyuna ancestral." },
    funFacts: [
      "Ha subido el Pico Simón Bolívar (5,775m) cinco veces.",
      "Habla kogi básico.",
      "Tatuó en su antebrazo el mapa de la Sierra.",
    ],
    availability: "Libre desde 5 jun 2026",
    destScene: 1,
  },
  {
    id: "pl5", name: "Camila Duarte", role: "Medellín & Antioquia",
    base: "Medellín", langs: ["ES", "EN", "IT"], years: 7,
    av: "linear-gradient(135deg, #d46a2a, #7c3a12)",
    regions: ["Medellín", "Guatapé", "Jardín", "Oriente"],
    specialties: ["City breaks", "Arte urbano", "Gastronomía paisa"],
    styles: ["cultura", "gastronomia", "boutique"],
    rating: 4.94, reviews: 278, trips: 171,
    response: "< 30 min",
    quote: "Medellín no se explica — se camina. De la Comuna 13 a El Poblado en metro, y de ahí a una finca en Santa Elena donde aún cultivan silletas.",
    bio: "Arquitecta paisa, doctorada en urbanismo en Milán. Regresó a Medellín para trabajar en el equipo que diseñó el Metrocable original. Diseña viajes que entrelazan memoria, arte público y la transformación social de la ciudad.",
    hallmarks: ["p2", "p5"],
    signature: { title: "Medellín Vibrante", note: "Itinerario firma — 5 días entre barrios, arte y gastronomía." },
    funFacts: [
      "Diseñó dos estaciones de Metrocable.",
      "Es jurado del festival de comida paisa.",
      "Colecciona afiches de cine de los 80.",
    ],
    availability: "Libre desde 10 may 2026",
    destScene: 3,
  },
  {
    id: "pl6", name: "Esteban Caicedo", role: "Cali & Pacífico Sur",
    base: "Cali", langs: ["ES", "EN"], years: 5,
    av: "linear-gradient(135deg, #c84a8a, #6e1c5c)",
    regions: ["Cali", "Popayán", "Buenaventura", "Tumaco"],
    specialties: ["Salsa y música", "Gastronomía pacífica", "Afrocultura"],
    styles: ["cultura", "gastronomia"],
    rating: 4.95, reviews: 142, trips: 87,
    response: "< 1 h",
    quote: "El Pacífico colombiano es otro país — ritmo marimba, pescado tatabro, selva que baja al mar. Viajas ahí y ya no eres el mismo.",
    bio: "Caleño, sociólogo, ex-director de cultura de un festival afrocolombiano. Abrió el catálogo del Pacífico — una región que pocos operadores tocan — con guías comunitarios de Bazán Bocana y Juanchaco.",
    hallmarks: ["p1", "p2"],
    signature: { title: "Pacífico Sur Auténtico", note: "Itinerario firma — 6 días entre Buenaventura y selva Emberá." },
    funFacts: [
      "Baila salsa caleña desde los 7.",
      "Escribe crónicas para una revista de viajes.",
      "Su plato favorito: encocado de jaiba.",
    ],
    availability: "Libre desde 25 may 2026",
    destScene: 4,
  },
];

const PLANNER_REVIEWS = [
  { id: "pr1", plId: "pl1", name: "Camille Laurent", origin: "París, Francia", pkg: "Caribe Esencial", rating: 5,
    txt: "Mariana entendió a mi madre antes que yo. Cambió un museo por una clase de baile con una profesora de champeta en Getsemaní. Perfecto." },
  { id: "pr2", plId: "pl1", name: "John Carter", origin: "Boston, USA", pkg: "Playas & Colonial", rating: 5,
    txt: "Mariana nos reservó un barco privado a Cholón con chef a bordo. Cinco estrellas no alcanzan." },
  { id: "pr3", plId: "pl2", name: "Sofía Herrera", origin: "CDMX", pkg: "Cafeteros & Cocora", rating: 5,
    txt: "Andrés nos llevó a la finca de su tía en Filandia. Desayuno de arepas con quesito a la leña. Eso no está en ninguna guía." },
  { id: "pr4", plId: "pl3", name: "Anita Reyes", origin: "Lima", pkg: "Amazonas Profundo", rating: 5,
    txt: "Luisa coordinó todo con la comunidad Ticuna. Dormimos en malocas, pescamos con arpón. Viaje transformador." },
  { id: "pr5", plId: "pl4", name: "Daniel Oster", origin: "Berlín", pkg: "Ciudad Perdida Trek", rating: 5,
    txt: "Juan David sabía cuándo parar, cuándo empujar. Leyó el clima mejor que cualquier app y nos salvó un día de lluvia." },
  { id: "pr6", plId: "pl5", name: "Mark & Anna", origin: "Toronto", pkg: "Medellín Vibrante", rating: 5,
    txt: "Camila armó un día en la Comuna 13 con grafitero local + almuerzo en casa de familia. La diferencia se nota." },
];

const TESTIMONIALS = [
  {
    id: "t1", name: "Camille Laurent", origin: "París, Francia", pkg: "Caribe Esencial",
    short: "Siete días perfectos, cada detalle planeado con cariño.",
    long: "Viajamos con mi madre y todo — transporte, hoteles, guías locales — fluía sin que tuviéramos que pensarlo. <em>Mariana conocía cada esquina</em> de Cartagena y nos llevó a lugares que no salen en ninguna guía. Volveremos sin duda.",
    rating: 5,
  },
  {
    id: "t2", name: "Daniel Oster", origin: "Berlín, Alemania", pkg: "Aventura Tayrona",
    short: "El Tayrona fue otra cosa con un guía que sabe leer la selva.",
    long: "Hicimos la caminata completa a Cabo San Juan con Juan David. Además de la geografía, explicó la historia del pueblo Tayrona, nos señaló aves endémicas y nos cocinaron un pescado que jamás olvidaré.",
    rating: 5,
  },
  {
    id: "t3", name: "Sofía Herrera", origin: "CDMX, México", pkg: "Cafeteros & Cocora",
    short: "La finca boutique en Salento fue pura postal.",
    long: "Nos trataron como si fuéramos familia. El tour del café pasó de ser una curiosidad a una clase magistral sobre el oficio.",
    rating: 5,
  },
  {
    id: "t4", name: "Mark & Anna Thompson", origin: "Toronto, Canadá", pkg: "Medellín Vibrante",
    short: "Pasamos de escépticos a enamorados de Medellín.",
    long: "La Comuna 13 fue una clase de historia viva. Guatapé, puro color. Nuestro guía nos enseñó cómo llegar en metro a todos lados.",
    rating: 5,
  },
];

const FAQ = [
  {
    q: "¿Es seguro viajar a Colombia hoy?",
    a: "Sí. Nuestros destinos son áreas turísticas consolidadas, con protocolos de seguridad y guías locales certificados. Hacemos monitoreo permanente y ajustamos rutas si hace falta.",
  },
  {
    q: "¿Qué incluye el precio del paquete?",
    a: "Alojamiento, traslados terrestres/aéreos especificados, tours guiados, entradas a parques y desayunos. Revisa la ficha de cada paquete — marcamos con check lo incluido y con dash lo opcional.",
  },
  {
    q: "¿Puedo personalizar el itinerario?",
    a: "Todos los paquetes son punto de partida. Tu planner asignado puede agregar días, cambiar hoteles, sumar actividades o reemplazar destinos. Sin costo por ajustar antes de confirmar.",
  },
  {
    q: "¿Cómo se paga la reserva?",
    a: "30% para confirmar, saldo 30 días antes del viaje. Aceptamos tarjeta internacional, PSE, transferencia y, para USA/EU, también PayPal y link de pago.",
  },
  {
    q: "¿Qué pasa si tengo que cancelar?",
    a: "Cancelación flexible hasta 45 días antes (reembolso 90%). Entre 45 y 15 días, 50%. Menos de 15 días, el anticipo queda como crédito de viaje por 12 meses.",
  },
  {
    q: "¿Necesito vacunas o visa?",
    a: "La mayoría de pasaportes no requiere visa por menos de 90 días. Fiebre amarilla es recomendada (no obligatoria) para Amazonas y Pacífico. Te enviamos la checklist exacta según tu nacionalidad.",
  },
];

Object.assign(window, { DESTINATIONS, PACKAGES, ACTIVITIES, PLANNERS, PLANNER_REVIEWS, TESTIMONIALS, FAQ });
