import { test, expect, type Page } from '@playwright/test';
import { Buffer } from 'node:buffer';
import { getFirstWebsiteId, seedWave2Fixtures, getSeededPackageSlug } from './helpers';

// 1x1 transparent PNG — smallest valid payload accepted by /api/media/upload.
const PNG_1x1 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
  'base64',
);

async function gotoMarketing(page: Page): Promise<void> {
  const websiteId = await getFirstWebsiteId(page);
  const slug = getSeededPackageSlug();
  await page.goto(`/dashboard/${websiteId}/products/${slug}/marketing`);
  await expect(page.getByTestId('marketing-editor-gallery')).toBeVisible({ timeout: 15000 });
}

async function uploadFiles(page: Page, files: Array<{ name: string; buffer: Buffer }>): Promise<void> {
  const fileInput = page.locator('input[type="file"][aria-label="Seleccionar imágenes"]');
  await fileInput.setInputFiles(
    files.map(({ name, buffer }) => ({ name, mimeType: 'image/png', buffer })),
  );
}

test.describe('GalleryCurator — E2E', () => {
  test.use({ storageState: 'e2e/.auth/user.json' });

  test.beforeAll(async () => {
    const fixtures = await seedWave2Fixtures();
    if (!fixtures.packageId) {
      throw new Error(
        `Gallery curator test needs a seeded package. Warnings: ${fixtures.warnings.join(' | ')}`,
      );
    }
  });

  test('upload happy path appends gallery tiles', async ({ page }) => {
    await gotoMarketing(page);

    await page.route('**/api/media/upload', async (route) => {
      const url = `https://mock.cdn/e2e/${crypto.randomUUID()}.png`;
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          success: true,
          data: {
            publicUrl: url,
            alt: 'Mock alt text generated by AI',
            caption: null,
          },
        }),
      });
    });

    await uploadFiles(page, [
      { name: 'photo-a.png', buffer: PNG_1x1 },
      { name: 'photo-b.png', buffer: PNG_1x1 },
    ]);

    const gallery = page.getByTestId('marketing-editor-gallery');
    await expect(gallery.locator('[data-testid="gallery-tile"]')).toHaveCount(2);

    await gallery.getByRole('button', { name: /^Guardar$/ }).click();
    await expect(gallery.getByRole('status').filter({ hasText: 'Guardado' })).toBeVisible({
      timeout: 20000,
    });
  });

  test('upload failure surfaces error without losing draft', async ({ page }) => {
    await gotoMarketing(page);

    await page.route('**/api/media/upload', async (route) => {
      await route.fulfill({
        status: 500,
        contentType: 'application/json',
        body: JSON.stringify({
          success: false,
          error: { code: 'UPLOAD_FAILED', message: 'Mocked upload failure' },
        }),
      });
    });

    await uploadFiles(page, [{ name: 'photo-fail.png', buffer: PNG_1x1 }]);

    const gallery = page.getByTestId('marketing-editor-gallery');
    await expect(gallery.getByRole('alert')).toContainText(/Mocked upload failure|Upload failed/i, {
      timeout: 10000,
    });
  });

  test('drag-and-drop reorder via keyboard', async ({ page }) => {
    await gotoMarketing(page);

    await page.route('**/api/media/upload', async (route, request) => {
      const form = request.postDataBuffer();
      const idx = form ? form.byteLength % 1000 : Date.now();
      const url = `https://mock.cdn/e2e/reorder-${idx}-${crypto.randomUUID()}.png`;
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          success: true,
          data: { publicUrl: url, alt: null, caption: null },
        }),
      });
    });

    await uploadFiles(page, [
      { name: 'first.png', buffer: PNG_1x1 },
      { name: 'second.png', buffer: PNG_1x1 },
    ]);

    const gallery = page.getByTestId('marketing-editor-gallery');
    await expect(gallery.locator('[data-testid="gallery-tile"]')).toHaveCount(2);

    const tiles = gallery.locator('[data-testid="gallery-tile"]');
    await tiles.nth(0).locator('input[id^="gallery-alt-"]').fill('alt-first');
    await tiles.nth(1).locator('input[id^="gallery-alt-"]').fill('alt-second');

    // Keyboard reorder via drag handle arrows.
    const firstTile = tiles.first();
    const handle = firstTile.getByRole('button', { name: /Reordenar imagen 1/ });
    await handle.focus();
    await page.keyboard.press('ArrowDown');

    await expect(
      gallery
        .locator('[data-testid="gallery-tile"]')
        .first()
        .locator('input[id^="gallery-alt-"]'),
    ).toHaveValue('alt-second');
  });
});
