import { test, expect, type Locator, type Page } from '@playwright/test';
import { Buffer } from 'node:buffer';
import { getFirstWebsiteId, seedWave2Fixtures, getSeededPackageSlug } from './helpers';

// 1x1 transparent PNG — smallest valid payload accepted by /api/media/upload.
const PNG_1x1 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
  'base64',
);

async function gotoMarketing(page: Page): Promise<{ gallery: Locator; editable: boolean }> {
  const websiteId = await getFirstWebsiteId(page);
  const slug = getSeededPackageSlug();
  await page.goto(`/dashboard/${websiteId}/products/${slug}/marketing`);
  const gallery = page.getByTestId('marketing-editor-gallery');
  await expect(gallery).toBeVisible({ timeout: 15000 });
  const editable = (await gallery.locator('input[type="file"]').count()) > 0;
  return { gallery, editable };
}

async function uploadFiles(gallery: Locator, files: Array<{ name: string; buffer: Buffer }>): Promise<void> {
  const fileInput = gallery.locator('input[type="file"]').first();
  await expect(fileInput).toHaveCount(1, { timeout: 10000 });
  await fileInput.setInputFiles(
    files.map(({ name, buffer }) => ({ name, mimeType: 'image/png', buffer })),
  );
}

test.describe('GalleryCurator — E2E', () => {
  test.use({ storageState: 'e2e/.auth/user.json' });

  test.beforeAll(async () => {
    const fixtures = await seedWave2Fixtures();
    if (!fixtures.packageId) {
      throw new Error(
        `Gallery curator test needs a seeded package. Warnings: ${fixtures.warnings.join(' | ')}`,
      );
    }
  });

  test('upload happy path appends gallery tiles', async ({ page }) => {
    const { gallery, editable } = await gotoMarketing(page);
    test.skip(!editable, 'program_gallery is not Studio-owned in this environment (read-only mode).');

    await page.route('**/api/media/upload', async (route) => {
      const url = `https://mock.cdn/e2e/${crypto.randomUUID()}.png`;
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          success: true,
          data: {
            publicUrl: url,
            alt: 'Mock alt text generated by AI',
            caption: null,
          },
        }),
      });
    });

    await uploadFiles(gallery, [
      { name: 'photo-a.png', buffer: PNG_1x1 },
      { name: 'photo-b.png', buffer: PNG_1x1 },
    ]);

    await expect(gallery.locator('[data-testid="gallery-tile"]')).toHaveCount(2);

    await gallery.getByRole('button', { name: /^Guardar$/ }).click();
    await expect(gallery.getByRole('status')).toContainText(/Guardado/i, { timeout: 10000 });
  });

  test('upload failure surfaces error without losing draft', async ({ page }) => {
    const { gallery, editable } = await gotoMarketing(page);
    test.skip(!editable, 'program_gallery is not Studio-owned in this environment (read-only mode).');

    await page.route('**/api/media/upload', async (route) => {
      await route.fulfill({
        status: 500,
        contentType: 'application/json',
        body: JSON.stringify({
          success: false,
          error: { code: 'UPLOAD_FAILED', message: 'Mocked upload failure' },
        }),
      });
    });

    await uploadFiles(gallery, [{ name: 'photo-fail.png', buffer: PNG_1x1 }]);
    await expect(gallery.getByRole('alert')).toContainText(/Mocked upload failure|Upload failed/i, {
      timeout: 10000,
    });
  });

  test('drag-and-drop reorder via keyboard', async ({ page }) => {
    const { gallery, editable } = await gotoMarketing(page);
    test.skip(!editable, 'program_gallery is not Studio-owned in this environment (read-only mode).');

    await page.route('**/api/media/upload', async (route, request) => {
      const form = request.postDataBuffer();
      const idx = form ? form.byteLength % 1000 : Date.now();
      const url = `https://mock.cdn/e2e/reorder-${idx}-${crypto.randomUUID()}.png`;
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          success: true,
          data: { publicUrl: url, alt: null, caption: null },
        }),
      });
    });

    await uploadFiles(gallery, [
      { name: 'first.png', buffer: PNG_1x1 },
      { name: 'second.png', buffer: PNG_1x1 },
    ]);

    await expect(gallery.locator('[data-testid="gallery-tile"]')).toHaveCount(2);

    const firstTile = gallery.locator('[data-testid="gallery-tile"]').first();
    const firstSrcBefore = await firstTile.locator('img').getAttribute('src');

    // Keyboard DnD: focus drag handle, Space to pick up, Arrow to move, Space to drop.
    const handle = firstTile.getByRole('button', { name: /Reordenar imagen 1/ });
    await handle.focus();
    await page.keyboard.press('Space');
    await page.keyboard.press('ArrowRight');
    await page.keyboard.press('Space');

    const firstSrcAfter = await gallery
      .locator('[data-testid="gallery-tile"]')
      .first()
      .locator('img')
      .getAttribute('src');

    expect(firstSrcAfter).not.toEqual(firstSrcBefore);
  });
});
