INSERT INTO product_seo_overrides (id, website_id, product_type, product_id, locale, meta_title, meta_desc, slug, h1, keywords, body_content, created_at, updated_at)
VALUES
  (gen_random_uuid(), '894545b7-73ca-4dae-b76a-da5b6a3f8441', 'package_kit', '9b915c08-e74a-4c8d-a2b1-4fc62b08d0cc', 'de-DE',
   'Cartagena Paket 5 Tage | ColombiaTours',
   'Erleben Sie Cartagena: 5 Tage, 4-Sterne-Hotel in Bocagrande, Stadtrundfahrt, Islas del Rosario und typische Küche. Ab 2.500 USD – jetzt buchen!',
   'cartagena-reise',
   'Cartagena-Paket – 5 Tage voller Kultur und Karibik',
   ARRAY['Cartagena Reise','Kolumbien Paket','Bocagrande Hotel','Islas del Rosario','Karibikurlaub'],
   $$Entdecken Sie das karibische Juwel Kolumbiens mit unserem 5-taegigen Cartagena-Paket. Ihr Aufenthalt umfasst ein komfortables 4-Sterne-Hotel im exklusiven Stadtteil Bocagrande, nur wenige Schritte vom Strand entfernt. Erleben Sie eine gefuehrte Stadtrundfahrt durch die historische Altstadt mit ihren farbenfrohen Kolonialbauten und geniessen Sie die Atmosphaere der belebten Plaetze und Kopfsteinpflastergassen. Ein absolutes Highlight ist der Tagesausflug zu den Islas del Rosario. Ab 2.500 USD pro Person bietet Ihnen dieses Paket ein rundum sorgloses Reiseerlebnis.$$,
   NOW(), NOW()),
  (gen_random_uuid(), '894545b7-73ca-4dae-b76a-da5b6a3f8441', 'package_kit', '9b915c08-e74a-4c8d-a2b1-4fc62b08d0cc', 'fr-FR',
   'Forfait Carthagène 5 Jours | ColombiaTours',
   'Forfait Carthagène 5 jours : hôtel 4 étoiles à Bocagrande, visite guidée, Islas del Rosario et cuisine typique. À partir de 2 500 USD – réservez dès maintenant !',
   'carthagene',
   'Forfait Carthagène – 5 jours entre culture et Caraïbes',
   ARRAY['Forfait Carthagene','voyage Colombie','Islas del Rosario','vacances Caraibes','sejour Carthagene'],
   $$Partez a la decouverte du joyau cariben de la Colombie avec notre forfait Carthagene de 5 jours. Votre sejour comprend un hotel 4 etoiles dans le quartier prise de Bocagrande, a quelques pas de la plage. Profitez d'une visite guidee de la vieille ville historique aux ruelles pavees et aux facades coloniales colorees. Le point d'orgue de ce voyage: une excursion aux Islas del Rosario, un archipel aux eaux cristallines et aux plages de sable blanc. A partir de 2 500 USD par personne, ce forfait tout compris vous offre une experience sans souci.$$,
   NOW(), NOW()),
  (gen_random_uuid(), '894545b7-73ca-4dae-b76a-da5b6a3f8441', 'package_kit', '9b915c08-e74a-4c8d-a2b1-4fc62b08d0cc', 'pt-BR',
   'Pacote Cartagena 5 Dias | ColombiaTours',
   'Pacote Cartagena 5 dias: hotel 4 estrelas em Bocagrande, city tour, Ilhas do Rosario e comida tipica. A partir de US$ 2.500 – reserve agora!',
   'cartagena',
   'Pacote Cartagena – 5 dias de cultura e Caribe',
   ARRAY['Pacote Cartagena','viagem Colombia','Ilhas do Rosario','Caribe colombiano','pacote de viagem'],
   $$Descubra a joia caribenha da Colombia com nosso pacote de 5 dias em Cartagena. Sua estadia inclui um confortavel hotel 4 estrelas no exclusivo bairro de Bocagrande, a poucos passos da praia. Aproveite um city tour guiado pelo centro historico com suas ruas de paralelepipedos e casaroes coloniais coloridos. O ponto alto e o passeio de um dia para as deslumbrantes Ilhas do Rosario – um arquipelago de aguas cristalinas e praias de areia branca. A partir de US$ 2.500 por pessoa, este pacote oferece uma viagem sem preocupacoes.$$,
   NOW(), NOW());
