import React from 'react';
import { PageBuilder } from '@/components/page-builder';
import { PageConfig } from '@/types/blocks';

// -----------------------------------------------------------------------------
// AI GENERATED JSON SIMULATION
// -----------------------------------------------------------------------------
// This is exactly what the AI would output based on the user prompt:
// "Create a modern landing page for Bukeer Software with a dark theme"
// -----------------------------------------------------------------------------
const AI_GENERATED_PAGE: PageConfig = {
  meta: {
    title: "Bukeer - Software para Agencias de Viajes",
    description: "La plataforma todo en uno para el turismo moderno.",
    slug: "/"
  },
  blocks: [
    {
      id: "block_1",
      type: "hero-modern",
      props: {
        variant: "centered",
        title: "El Sistema Operativo del Turismo",
        subtitle: "Gestiona itinerarios, reservas y finanzas en una sola plataforma. Diseñado para las mejores agencias de Latam.",
        badge: {
          text: "Nuevo: AI Itineraries 2.0",
          color: "success"
        },
        primaryCta: {
          text: "Empezar Gratis",
          href: "/signup"
        },
        secondaryCta: {
          text: "Ver Demo",
          href: "/demo"
        }
      }
    },
    // Adding a second block to test the renderer (even if it renders 'not supported' for now)
    {
      id: "block_2",
      type: "bento-grid",
      props: {
        title: "Todo lo que necesitas",
        items: []
      }
    }
  ]
};

export default function CorporateDemoPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* The PageBuilder consumes the JSON and renders the UI */}
      <PageBuilder blocks={AI_GENERATED_PAGE.blocks} />
      
      {/* Debug view to show the JSON */}
      <div className="container mx-auto mt-20 p-8 border-t">
        <h3 className="text-sm font-mono text-muted-foreground mb-4 uppercase tracking-wider">
          Behind the scenes: JSON generated by AI
        </h3>
        <pre className="bg-slate-950 text-slate-50 p-6 rounded-lg overflow-auto text-xs font-mono">
          {JSON.stringify(AI_GENERATED_PAGE, null, 2)}
        </pre>
      </div>
    </div>
  );
}
