/**
 * Colombia-specific system presets.
 */

import { DESIGN_TOKENS_SCHEMA_VERSION } from '../contracts/design-tokens';
import { THEME_PROFILE_SCHEMA_VERSION } from '../contracts/theme-profile';
import type { ThemePreset } from '../contracts/preset';
import { TOURISM_PRESETS } from './tourism-presets';

function preset(p: Omit<ThemePreset, 'versions'>): ThemePreset {
  return { ...p, versions: [] };
}

export const COLOMBIA_CARIBE_PRESET: ThemePreset = preset({
  metadata: {
    id: 'a0000001-0000-0000-0000-000000000009',
    name: 'Colombia Caribe',
    slug: 'colombia-caribe',
    description: 'Paleta caribeña para operadores de costa, islas y experiencias tropicales en Colombia',
    category: 'tropical',
    emoji: '🏝️',
    tags: ['colombia', 'caribe', 'playa', 'islas', 'tropical'],
    isSystem: true,
    isActive: true,
    displayOrder: 9,
    suggestedSections: ['hero', 'destinations', 'activities', 'testimonials', 'gallery', 'cta'],
  },
  tokens: {
    $schema: DESIGN_TOKENS_SCHEMA_VERSION,
    colors: {
      seedColor: '#007C91',
      accents: {
        accent2: '#FFD166',
        accent3: '#CBE9FF',
      },
      chart: { c2: '#00ACC1', c3: '#F28C28', c5: '#2CA58D' },
      light: {
        primary: '#007C91',
        onPrimary: '#FFFFFF',
        primaryContainer: '#BDEBFF',
        onPrimaryContainer: '#002733',
        secondary: '#E07A2E',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#FFDCC3',
        onSecondaryContainer: '#4A1D00',
        tertiary: '#2F7D32',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#C2F0BE',
        onTertiaryContainer: '#0A2F0E',
        error: '#B3261E',
        onError: '#FFFFFF',
        errorContainer: '#F9DEDC',
        onErrorContainer: '#410E0B',
        surface: '#F6FCFF',
        onSurface: '#182124',
        surfaceContainerLowest: '#FFFFFF',
        surfaceContainerLow: '#EFF6F9',
        surfaceContainer: '#E8EFF2',
        surfaceContainerHigh: '#E1E9EC',
        surfaceContainerHighest: '#DBE3E6',
        onSurfaceVariant: '#3E4A4F',
        outline: '#6E7B80',
        outlineVariant: '#BDC9CE',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#2D3135',
        onInverseSurface: '#EEF2F5',
        inversePrimary: '#7FD7EC',
        surfaceTint: '#007C91',
        background: '#F6FCFF',
      },
      dark: {
        primary: '#7FD7EC',
        onPrimary: '#003743',
        primaryContainer: '#005C6E',
        onPrimaryContainer: '#BDEBFF',
        secondary: '#FFB780',
        onSecondary: '#5A2A00',
        secondaryContainer: '#7A3F09',
        onSecondaryContainer: '#FFDCC3',
        tertiary: '#9DD39B',
        onTertiary: '#163A1A',
        tertiaryContainer: '#2F5C32',
        onTertiaryContainer: '#C2F0BE',
        error: '#F2B8B5',
        onError: '#601410',
        errorContainer: '#8C1D18',
        onErrorContainer: '#F9DEDC',
        surface: '#10181B',
        onSurface: '#DBE3E6',
        surfaceContainerLowest: '#0B1113',
        surfaceContainerLow: '#182124',
        surfaceContainer: '#1C2529',
        surfaceContainerHigh: '#273034',
        surfaceContainerHighest: '#323B3F',
        onSurfaceVariant: '#BDC9CE',
        outline: '#88959A',
        outlineVariant: '#3E4A4F',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#DBE3E6',
        onInverseSurface: '#2D3135',
        inversePrimary: '#007C91',
        surfaceTint: '#7FD7EC',
        background: '#10181B',
      },
    },
    typography: {
      display: { family: 'Bricolage Grotesque', fallback: 'sans-serif', weight: '700' },
      body: { family: 'Instrument Serif', fallback: 'serif', weight: '400' },
      scale: 'default',
      bodyLineHeight: 1.6,
      letterSpacing: 0.01,
    },
    shape: { radius: 'lg', buttonRadius: 'full', cardRadius: 'lg' },
    elevation: { cardElevation: 'raised', navElevation: 'subtle', heroElevation: 'flat' },
    motion: {
      preset: 'moderate',
      durationMs: 320,
      easing: 'organic',
      customEasing: [0.21, 0.72, 0.14, 1],
      reducedMotion: true,
    },
    spacing: {
      baseUnit: 4,
      scale: 'default',
      density: 'roomy',
      containerMaxPx: 1240,
      sectionPaddingMultiplier: 2.5,
    },
  },
  profile: {
    $schema: THEME_PROFILE_SCHEMA_VERSION,
    brand: { mood: 'adventurous', name: 'Colombia Caribe' },
    colorMode: 'system',
    layout: {
      variant: 'modern',
      heroStyle: 'full',
      navStyle: 'transparent',
      footerStyle: 'full',
      maxContentWidth: 1280,
    },
    sectionStyles: {
      hero: 'hero',
      destinations: 'alternating',
      activities: 'card-grid',
      testimonials: 'default',
    },
    metadata: {},
  },
  quality: {
    contrastAA: true,
    darkModeComplete: true,
    fontsAllowlisted: true,
    sectionStylesVerified: true,
    previewCaptured: false,
    mobileVerified: false,
  },
});

export const ALL_SYSTEM_PRESETS: ThemePreset[] = [
  ...TOURISM_PRESETS,
  COLOMBIA_CARIBE_PRESET,
];
