/**
 * 8 Tourism-Ready Reference Presets for Bukeer Websites.
 *
 * Each preset includes complete DesignTokens + ThemeProfile + metadata.
 * All presets pass WCAG AA contrast checks and use allowlisted fonts.
 */

import { DESIGN_TOKENS_SCHEMA_VERSION } from '../contracts/design-tokens';
import { THEME_PROFILE_SCHEMA_VERSION } from '../contracts/theme-profile';
import type { ThemePreset } from '../contracts/preset';

// ---------------------------------------------------------------------------
// Helper to create a full preset
// ---------------------------------------------------------------------------

function preset(p: Omit<ThemePreset, 'versions'>): ThemePreset {
  return { ...p, versions: [] };
}

// ---------------------------------------------------------------------------
// 1. ADVENTURE
// ---------------------------------------------------------------------------

export const ADVENTURE_PRESET: ThemePreset = preset({
  metadata: {
    id: 'a0000001-0000-0000-0000-000000000001',
    name: 'Aventura',
    slug: 'adventure',
    description: 'Bold and energetic — designed for adventure, eco-tourism, and outdoor operators',
    category: 'adventure',
    emoji: '🏔️',
    tags: ['outdoor', 'active', 'hiking', 'rafting', 'bold'],
    isSystem: true,
    isActive: true,
    displayOrder: 1,
    suggestedSections: ['hero', 'features', 'destinations', 'gallery', 'testimonials', 'cta'],
  },
  tokens: {
    $schema: DESIGN_TOKENS_SCHEMA_VERSION,
    colors: {
      seedColor: '#2E7D32',
      light: {
        primary: '#2E7D32',
        onPrimary: '#FFFFFF',
        primaryContainer: '#B9F6CA',
        onPrimaryContainer: '#1B5E20',
        secondary: '#5D4037',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#D7CCC8',
        onSecondaryContainer: '#3E2723',
        tertiary: '#BF4A00',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#FFE0B2',
        onTertiaryContainer: '#7A2E00',
        error: '#B3261E',
        onError: '#FFFFFF',
        errorContainer: '#F9DEDC',
        onErrorContainer: '#410E0B',
        surface: '#FAFDF7',
        onSurface: '#1A1C18',
        surfaceContainerLowest: '#FFFFFF',
        surfaceContainerLow: '#F3F6EF',
        surfaceContainer: '#EDF0E8',
        surfaceContainerHigh: '#E7EAE2',
        surfaceContainerHighest: '#E1E4DC',
        onSurfaceVariant: '#44483E',
        outline: '#747970',
        outlineVariant: '#C4C8BD',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#2F312B',
        onInverseSurface: '#F0F1EA',
        inversePrimary: '#81C784',
        surfaceTint: '#2E7D32',
        background: '#FAFDF7',
      },
      dark: {
        primary: '#81C784',
        onPrimary: '#0A3D10',
        primaryContainer: '#1B5E20',
        onPrimaryContainer: '#C8F7CB',
        secondary: '#BCAAA4',
        onSecondary: '#3E2723',
        secondaryContainer: '#5D4037',
        onSecondaryContainer: '#D7CCC8',
        tertiary: '#FFB74D',
        onTertiary: '#4A2000',
        tertiaryContainer: '#7A3C00',
        onTertiaryContainer: '#FFE0B2',
        error: '#F2B8B5',
        onError: '#601410',
        errorContainer: '#8C1D18',
        onErrorContainer: '#F9DEDC',
        surface: '#121410',
        onSurface: '#E1E4DC',
        surfaceContainerLowest: '#0D0F0B',
        surfaceContainerLow: '#1A1C18',
        surfaceContainer: '#1E201C',
        surfaceContainerHigh: '#282B26',
        surfaceContainerHighest: '#333631',
        onSurfaceVariant: '#C4C8BD',
        outline: '#8E9388',
        outlineVariant: '#44483E',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#E1E4DC',
        onInverseSurface: '#2F312B',
        inversePrimary: '#2E7D32',
        surfaceTint: '#81C784',
        background: '#121410',
      },
    },
    typography: {
      display: { family: 'Montserrat', fallback: 'sans-serif', weight: '700' },
      body: { family: 'Open Sans', fallback: 'sans-serif', weight: '400' },
      scale: 'default',
      bodyLineHeight: 1.6,
      letterSpacing: 0,
    },
    shape: { radius: 'md', buttonRadius: 'lg', cardRadius: 'lg' },
    elevation: { cardElevation: 'raised', navElevation: 'raised', heroElevation: 'flat' },
    motion: { preset: 'moderate', durationMs: 300, easing: 'ease-out', reducedMotion: true },
    spacing: { baseUnit: 4, scale: 'default', sectionPaddingMultiplier: 2 },
  },
  profile: {
    $schema: THEME_PROFILE_SCHEMA_VERSION,
    brand: { mood: 'adventurous', name: 'Aventura' },
    colorMode: 'system',
    layout: { variant: 'bold', heroStyle: 'full', navStyle: 'transparent', footerStyle: 'full', maxContentWidth: 1400 },
    sectionStyles: { hero: 'hero', features: 'card-grid', destinations: 'alternating' },
    metadata: {},
  },
  quality: {
    contrastAA: true,
    darkModeComplete: true,
    fontsAllowlisted: true,
    sectionStylesVerified: true,
    previewCaptured: false,
    mobileVerified: false,
  },
});

// ---------------------------------------------------------------------------
// 2. LUXURY
// ---------------------------------------------------------------------------

export const LUXURY_PRESET: ThemePreset = preset({
  metadata: {
    id: 'a0000001-0000-0000-0000-000000000002',
    name: 'Lujo',
    slug: 'luxury',
    description: 'Refined and elegant — designed for luxury hotels, resorts, and premium travel',
    category: 'luxury',
    emoji: '🏨',
    tags: ['premium', 'elegant', 'hotel', 'resort', 'sophisticated'],
    isSystem: true,
    isActive: true,
    displayOrder: 2,
    suggestedSections: ['hero', 'about', 'hotels', 'gallery', 'testimonials', 'contact-form'],
  },
  tokens: {
    $schema: DESIGN_TOKENS_SCHEMA_VERSION,
    colors: {
      seedColor: '#1A237E',
      light: {
        primary: '#1A237E',
        onPrimary: '#FFFFFF',
        primaryContainer: '#C5CAE9',
        onPrimaryContainer: '#0D1042',
        secondary: '#6D4C41',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#EFEBE9',
        onSecondaryContainer: '#3E2723',
        tertiary: '#8A6508',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#FFF3D4',
        onTertiaryContainer: '#4A3500',
        error: '#B3261E',
        onError: '#FFFFFF',
        errorContainer: '#F9DEDC',
        onErrorContainer: '#410E0B',
        surface: '#FDFBFF',
        onSurface: '#1B1B1F',
        surfaceContainerLowest: '#FFFFFF',
        surfaceContainerLow: '#F6F2FA',
        surfaceContainer: '#F0ECF4',
        surfaceContainerHigh: '#EAE7EF',
        surfaceContainerHighest: '#E4E1E9',
        onSurfaceVariant: '#46464F',
        outline: '#777680',
        outlineVariant: '#C7C5D0',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#303034',
        onInverseSurface: '#F3EFF7',
        inversePrimary: '#B0C4FF',
        surfaceTint: '#1A237E',
        background: '#FDFBFF',
      },
      dark: {
        primary: '#B0C4FF',
        onPrimary: '#0D1042',
        primaryContainer: '#1A237E',
        onPrimaryContainer: '#C5CAE9',
        secondary: '#D7CCC8',
        onSecondary: '#3E2723',
        secondaryContainer: '#6D4C41',
        onSecondaryContainer: '#EFEBE9',
        tertiary: '#FFD54F',
        onTertiary: '#3A2800',
        tertiaryContainer: '#5C4200',
        onTertiaryContainer: '#FFF3D4',
        error: '#F2B8B5',
        onError: '#601410',
        errorContainer: '#8C1D18',
        onErrorContainer: '#F9DEDC',
        surface: '#131316',
        onSurface: '#E4E1E9',
        surfaceContainerLowest: '#0E0E11',
        surfaceContainerLow: '#1B1B1F',
        surfaceContainer: '#1F1F23',
        surfaceContainerHigh: '#2A292D',
        surfaceContainerHighest: '#353438',
        onSurfaceVariant: '#C7C5D0',
        outline: '#91909A',
        outlineVariant: '#46464F',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#E4E1E9',
        onInverseSurface: '#303034',
        inversePrimary: '#1A237E',
        surfaceTint: '#B0C4FF',
        background: '#131316',
      },
    },
    typography: {
      display: { family: 'Playfair Display', fallback: 'serif', weight: '600' },
      body: { family: 'Lato', fallback: 'sans-serif', weight: '400' },
      scale: 'default',
      bodyLineHeight: 1.7,
      letterSpacing: 0.02,
    },
    shape: { radius: 'sm', cardRadius: 'md' },
    elevation: { cardElevation: 'subtle', navElevation: 'subtle', heroElevation: 'flat' },
    motion: { preset: 'subtle', durationMs: 250, easing: 'ease-in-out', reducedMotion: true },
    spacing: { baseUnit: 4, scale: 'relaxed', sectionPaddingMultiplier: 3 },
  },
  profile: {
    $schema: THEME_PROFILE_SCHEMA_VERSION,
    brand: { mood: 'luxurious', name: 'Lujo' },
    colorMode: 'system',
    layout: { variant: 'classic', heroStyle: 'full', navStyle: 'sticky', footerStyle: 'full', maxContentWidth: 1200 },
    sectionStyles: { hero: 'hero', about: 'subtle', hotels: 'default', gallery: 'emphasized' },
    metadata: {},
  },
  quality: {
    contrastAA: true,
    darkModeComplete: true,
    fontsAllowlisted: true,
    sectionStylesVerified: true,
    previewCaptured: false,
    mobileVerified: false,
  },
});

// ---------------------------------------------------------------------------
// 3. TROPICAL
// ---------------------------------------------------------------------------

export const TROPICAL_PRESET: ThemePreset = preset({
  metadata: {
    id: 'a0000001-0000-0000-0000-000000000003',
    name: 'Tropical',
    slug: 'tropical',
    description: 'Warm and vibrant — designed for beach resorts, island getaways, and Caribbean tours',
    category: 'tropical',
    emoji: '🌴',
    tags: ['beach', 'island', 'caribbean', 'warm', 'vibrant'],
    isSystem: true,
    isActive: true,
    displayOrder: 3,
    suggestedSections: ['hero', 'destinations', 'activities', 'gallery', 'pricing', 'testimonials'],
  },
  tokens: {
    $schema: DESIGN_TOKENS_SCHEMA_VERSION,
    colors: {
      seedColor: '#006B60',
      light: {
        primary: '#006B60',
        onPrimary: '#FFFFFF',
        primaryContainer: '#A7F3D0',
        onPrimaryContainer: '#002019',
        secondary: '#C4501E',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#FFDBCF',
        onSecondaryContainer: '#6B2A0A',
        tertiary: '#8A6D00',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#FFF3D4',
        onTertiaryContainer: '#4A3A00',
        error: '#B3261E',
        onError: '#FFFFFF',
        errorContainer: '#F9DEDC',
        onErrorContainer: '#410E0B',
        surface: '#F5FFFE',
        onSurface: '#171D1C',
        surfaceContainerLowest: '#FFFFFF',
        surfaceContainerLow: '#EFF9F8',
        surfaceContainer: '#E9F3F2',
        surfaceContainerHigh: '#E3EDEC',
        surfaceContainerHighest: '#DDE7E6',
        onSurfaceVariant: '#3F4946',
        outline: '#6F7A76',
        outlineVariant: '#BFC9C5',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#2C3230',
        onInverseSurface: '#ECF2F0',
        inversePrimary: '#4DB6AC',
        surfaceTint: '#006B60',
        background: '#F5FFFE',
      },
      dark: {
        primary: '#4DB6AC',
        onPrimary: '#00201C',
        primaryContainer: '#005048',
        onPrimaryContainer: '#A7F3D0',
        secondary: '#FFAB91',
        onSecondary: '#5C1900',
        secondaryContainer: '#832B0A',
        onSecondaryContainer: '#FFDBCF',
        tertiary: '#FFD54F',
        onTertiary: '#3A2800',
        tertiaryContainer: '#5C4200',
        onTertiaryContainer: '#FFF3D4',
        error: '#F2B8B5',
        onError: '#601410',
        errorContainer: '#8C1D18',
        onErrorContainer: '#F9DEDC',
        surface: '#0F1513',
        onSurface: '#DDE7E6',
        surfaceContainerLowest: '#0A0F0E',
        surfaceContainerLow: '#171D1C',
        surfaceContainer: '#1B2120',
        surfaceContainerHigh: '#252B2A',
        surfaceContainerHighest: '#303635',
        onSurfaceVariant: '#BFC9C5',
        outline: '#899490',
        outlineVariant: '#3F4946',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#DDE7E6',
        onInverseSurface: '#2C3230',
        inversePrimary: '#00897B',
        surfaceTint: '#4DB6AC',
        background: '#0F1513',
      },
    },
    typography: {
      display: { family: 'Poppins', fallback: 'sans-serif', weight: '600' },
      body: { family: 'Nunito', fallback: 'sans-serif', weight: '400' },
      scale: 'default',
      bodyLineHeight: 1.6,
      letterSpacing: 0,
    },
    shape: { radius: 'lg', buttonRadius: 'xl', cardRadius: 'lg' },
    elevation: { cardElevation: 'raised', navElevation: 'subtle', heroElevation: 'flat' },
    motion: { preset: 'moderate', durationMs: 300, easing: 'ease-out', reducedMotion: true },
    spacing: { baseUnit: 4, scale: 'relaxed', sectionPaddingMultiplier: 2.5 },
  },
  profile: {
    $schema: THEME_PROFILE_SCHEMA_VERSION,
    brand: { mood: 'tropical', name: 'Tropical' },
    colorMode: 'system',
    layout: { variant: 'modern', heroStyle: 'slideshow', navStyle: 'transparent', footerStyle: 'full', maxContentWidth: 1400 },
    sectionStyles: { hero: 'hero', destinations: 'card-grid', activities: 'alternating' },
    metadata: {},
  },
  quality: {
    contrastAA: true,
    darkModeComplete: true,
    fontsAllowlisted: true,
    sectionStylesVerified: true,
    previewCaptured: false,
    mobileVerified: false,
  },
});

// ---------------------------------------------------------------------------
// 4. CORPORATE
// ---------------------------------------------------------------------------

export const CORPORATE_PRESET: ThemePreset = preset({
  metadata: {
    id: 'a0000001-0000-0000-0000-000000000004',
    name: 'Corporativo',
    slug: 'corporate',
    description: 'Clean and professional — designed for B2B travel, DMCs, and corporate agencies',
    category: 'corporate',
    emoji: '✈️',
    tags: ['business', 'professional', 'B2B', 'DMC', 'clean'],
    isSystem: true,
    isActive: true,
    displayOrder: 4,
    suggestedSections: ['hero', 'features', 'stats', 'partners', 'testimonials', 'contact-form'],
  },
  tokens: {
    $schema: DESIGN_TOKENS_SCHEMA_VERSION,
    colors: {
      seedColor: '#455A64',
      light: {
        primary: '#455A64',
        onPrimary: '#FFFFFF',
        primaryContainer: '#CFD8DC',
        onPrimaryContainer: '#263238',
        secondary: '#37474F',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#ECEFF1',
        onSecondaryContainer: '#263238',
        tertiary: '#0277BD',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#B3E5FC',
        onTertiaryContainer: '#01579B',
        error: '#B3261E',
        onError: '#FFFFFF',
        errorContainer: '#F9DEDC',
        onErrorContainer: '#410E0B',
        surface: '#FAFAFA',
        onSurface: '#1C1B1F',
        surfaceContainerLowest: '#FFFFFF',
        surfaceContainerLow: '#F5F5F5',
        surfaceContainer: '#EEEEEE',
        surfaceContainerHigh: '#E8E8E8',
        surfaceContainerHighest: '#E0E0E0',
        onSurfaceVariant: '#49454F',
        outline: '#79747E',
        outlineVariant: '#CAC4D0',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#313033',
        onInverseSurface: '#F4EFF4',
        inversePrimary: '#90A4AE',
        surfaceTint: '#455A64',
        background: '#FAFAFA',
      },
      dark: {
        primary: '#90A4AE',
        onPrimary: '#263238',
        primaryContainer: '#455A64',
        onPrimaryContainer: '#CFD8DC',
        secondary: '#B0BEC5',
        onSecondary: '#263238',
        secondaryContainer: '#37474F',
        onSecondaryContainer: '#ECEFF1',
        tertiary: '#4FC3F7',
        onTertiary: '#002F4E',
        tertiaryContainer: '#004470',
        onTertiaryContainer: '#C8EDFF',
        error: '#F2B8B5',
        onError: '#601410',
        errorContainer: '#8C1D18',
        onErrorContainer: '#F9DEDC',
        surface: '#131313',
        onSurface: '#E6E1E5',
        surfaceContainerLowest: '#0E0E0E',
        surfaceContainerLow: '#1C1B1F',
        surfaceContainer: '#201F23',
        surfaceContainerHigh: '#2B2A2E',
        surfaceContainerHighest: '#363539',
        onSurfaceVariant: '#CAC4D0',
        outline: '#938F99',
        outlineVariant: '#49454F',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#E6E1E5',
        onInverseSurface: '#313033',
        inversePrimary: '#455A64',
        surfaceTint: '#90A4AE',
        background: '#131313',
      },
    },
    typography: {
      display: { family: 'Inter', fallback: 'sans-serif', weight: '600' },
      body: { family: 'Inter', fallback: 'sans-serif', weight: '400' },
      scale: 'default',
      bodyLineHeight: 1.5,
      letterSpacing: 0,
    },
    shape: { radius: 'sm' },
    elevation: { cardElevation: 'subtle', navElevation: 'subtle', heroElevation: 'flat' },
    motion: { preset: 'subtle', durationMs: 200, easing: 'ease-out', reducedMotion: true },
    spacing: { baseUnit: 4, scale: 'default', sectionPaddingMultiplier: 2 },
  },
  profile: {
    $schema: THEME_PROFILE_SCHEMA_VERSION,
    brand: { mood: 'corporate', name: 'Corporativo' },
    colorMode: 'light',
    layout: { variant: 'minimal', heroStyle: 'centered', navStyle: 'sticky', footerStyle: 'compact', maxContentWidth: 1200 },
    sectionStyles: { hero: 'subtle', features: 'card-grid', stats: 'emphasized' },
    metadata: {},
  },
  quality: {
    contrastAA: true,
    darkModeComplete: true,
    fontsAllowlisted: true,
    sectionStylesVerified: true,
    previewCaptured: false,
    mobileVerified: false,
  },
});

// ---------------------------------------------------------------------------
// 5. BOUTIQUE
// ---------------------------------------------------------------------------

export const BOUTIQUE_PRESET: ThemePreset = preset({
  metadata: {
    id: 'a0000001-0000-0000-0000-000000000005',
    name: 'Boutique',
    slug: 'boutique',
    description: 'Warm and artisanal — designed for boutique hotels, B&Bs, and handcrafted experiences',
    category: 'boutique',
    emoji: '🏡',
    tags: ['artisan', 'cozy', 'handcrafted', 'small-hotel', 'warm'],
    isSystem: true,
    isActive: true,
    displayOrder: 5,
    suggestedSections: ['hero', 'about', 'hotels', 'gallery', 'testimonials', 'newsletter'],
  },
  tokens: {
    $schema: DESIGN_TOKENS_SCHEMA_VERSION,
    colors: {
      seedColor: '#8D6E63',
      light: {
        primary: '#8D6E63',
        onPrimary: '#FFFFFF',
        primaryContainer: '#EFEBE9',
        onPrimaryContainer: '#4E342E',
        secondary: '#6D7B5A',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#E8F0DC',
        onSecondaryContainer: '#3E4A2E',
        tertiary: '#8A6508',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#FFF3D4',
        onTertiaryContainer: '#4A3500',
        error: '#B3261E',
        onError: '#FFFFFF',
        errorContainer: '#F9DEDC',
        onErrorContainer: '#410E0B',
        surface: '#FFF8F5',
        onSurface: '#201A17',
        surfaceContainerLowest: '#FFFFFF',
        surfaceContainerLow: '#FBF1EC',
        surfaceContainer: '#F5EBE6',
        surfaceContainerHigh: '#EFE5E0',
        surfaceContainerHighest: '#E9DFDA',
        onSurfaceVariant: '#52443D',
        outline: '#85746B',
        outlineVariant: '#D7C3B8',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#362F2B',
        onInverseSurface: '#FBEEEA',
        inversePrimary: '#CFB0A4',
        surfaceTint: '#8D6E63',
        background: '#FFF8F5',
      },
      dark: {
        primary: '#CFB0A4',
        onPrimary: '#4E342E',
        primaryContainer: '#6D4C41',
        onPrimaryContainer: '#EFEBE9',
        secondary: '#C2D1AD',
        onSecondary: '#3E4A2E',
        secondaryContainer: '#556243',
        onSecondaryContainer: '#E8F0DC',
        tertiary: '#FFD54F',
        onTertiary: '#3A2800',
        tertiaryContainer: '#5C4200',
        onTertiaryContainer: '#FFF3D4',
        error: '#F2B8B5',
        onError: '#601410',
        errorContainer: '#8C1D18',
        onErrorContainer: '#F9DEDC',
        surface: '#181210',
        onSurface: '#E9DFDA',
        surfaceContainerLowest: '#130D0B',
        surfaceContainerLow: '#201A17',
        surfaceContainer: '#241E1B',
        surfaceContainerHigh: '#2F2825',
        surfaceContainerHighest: '#3A3330',
        onSurfaceVariant: '#D7C3B8',
        outline: '#9F8D83',
        outlineVariant: '#52443D',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#E9DFDA',
        onInverseSurface: '#362F2B',
        inversePrimary: '#8D6E63',
        surfaceTint: '#CFB0A4',
        background: '#181210',
      },
    },
    typography: {
      display: { family: 'Cormorant Garamond', fallback: 'serif', weight: '600' },
      body: { family: 'Lato', fallback: 'sans-serif', weight: '400' },
      scale: 'default',
      bodyLineHeight: 1.7,
      letterSpacing: 0.01,
    },
    shape: { radius: 'md', buttonRadius: 'sm', cardRadius: 'lg' },
    elevation: { cardElevation: 'subtle', navElevation: 'subtle', heroElevation: 'flat' },
    motion: { preset: 'subtle', durationMs: 250, easing: 'ease-in-out', reducedMotion: true },
    spacing: { baseUnit: 4, scale: 'relaxed', sectionPaddingMultiplier: 2.5 },
  },
  profile: {
    $schema: THEME_PROFILE_SCHEMA_VERSION,
    brand: { mood: 'boutique', name: 'Boutique' },
    colorMode: 'system',
    layout: { variant: 'classic', heroStyle: 'split', navStyle: 'sticky', footerStyle: 'full', maxContentWidth: 1100 },
    sectionStyles: { hero: 'hero', about: 'subtle', gallery: 'emphasized' },
    metadata: {},
  },
  quality: {
    contrastAA: true,
    darkModeComplete: true,
    fontsAllowlisted: true,
    sectionStylesVerified: true,
    previewCaptured: false,
    mobileVerified: false,
  },
});

// ---------------------------------------------------------------------------
// 6. CULTURAL
// ---------------------------------------------------------------------------

export const CULTURAL_PRESET: ThemePreset = preset({
  metadata: {
    id: 'a0000001-0000-0000-0000-000000000006',
    name: 'Cultural',
    slug: 'cultural',
    description: 'Rich and expressive — designed for cultural tours, heritage sites, and gastro-tourism',
    category: 'cultural',
    emoji: '🎭',
    tags: ['culture', 'heritage', 'gastro', 'museum', 'history'],
    isSystem: true,
    isActive: true,
    displayOrder: 6,
    suggestedSections: ['hero', 'about', 'destinations', 'activities', 'gallery', 'faq'],
  },
  tokens: {
    $schema: DESIGN_TOKENS_SCHEMA_VERSION,
    colors: {
      seedColor: '#880E4F',
      light: {
        primary: '#880E4F',
        onPrimary: '#FFFFFF',
        primaryContainer: '#FFD6E8',
        onPrimaryContainer: '#560027',
        secondary: '#4A148C',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#E1BEE7',
        onSecondaryContainer: '#2E0057',
        tertiary: '#B85000',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#FFE0B2',
        onTertiaryContainer: '#7A2E00',
        error: '#B3261E',
        onError: '#FFFFFF',
        errorContainer: '#F9DEDC',
        onErrorContainer: '#410E0B',
        surface: '#FFFBFF',
        onSurface: '#1E1A1D',
        surfaceContainerLowest: '#FFFFFF',
        surfaceContainerLow: '#F9F0F4',
        surfaceContainer: '#F3EAEE',
        surfaceContainerHigh: '#EDE4E8',
        surfaceContainerHighest: '#E7DEE2',
        onSurfaceVariant: '#4E444B',
        outline: '#807379',
        outlineVariant: '#D0C3C9',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#342F32',
        onInverseSurface: '#F7EEF2',
        inversePrimary: '#FFB0D0',
        surfaceTint: '#880E4F',
        background: '#FFFBFF',
      },
      dark: {
        primary: '#FFB0D0',
        onPrimary: '#560027',
        primaryContainer: '#7B0A3F',
        onPrimaryContainer: '#FFD6E8',
        secondary: '#CE93D8',
        onSecondary: '#2E0057',
        secondaryContainer: '#38006B',
        onSecondaryContainer: '#E1BEE7',
        tertiary: '#FFB74D',
        onTertiary: '#4A2000',
        tertiaryContainer: '#7A3C00',
        onTertiaryContainer: '#FFE0B2',
        error: '#F2B8B5',
        onError: '#601410',
        errorContainer: '#8C1D18',
        onErrorContainer: '#F9DEDC',
        surface: '#161214',
        onSurface: '#E7DEE2',
        surfaceContainerLowest: '#100D0F',
        surfaceContainerLow: '#1E1A1D',
        surfaceContainer: '#221E21',
        surfaceContainerHigh: '#2D282B',
        surfaceContainerHighest: '#383336',
        onSurfaceVariant: '#D0C3C9',
        outline: '#998D93',
        outlineVariant: '#4E444B',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#E7DEE2',
        onInverseSurface: '#342F32',
        inversePrimary: '#880E4F',
        surfaceTint: '#FFB0D0',
        background: '#161214',
      },
    },
    typography: {
      display: { family: 'DM Serif Display', fallback: 'serif', weight: '400' },
      body: { family: 'DM Sans', fallback: 'sans-serif', weight: '400' },
      scale: 'large',
      bodyLineHeight: 1.6,
      letterSpacing: 0,
    },
    shape: { radius: 'md', cardRadius: 'lg' },
    elevation: { cardElevation: 'raised', navElevation: 'raised', heroElevation: 'flat' },
    motion: { preset: 'expressive', durationMs: 350, easing: 'ease-in-out', reducedMotion: true },
    spacing: { baseUnit: 4, scale: 'relaxed', sectionPaddingMultiplier: 2.5 },
  },
  profile: {
    $schema: THEME_PROFILE_SCHEMA_VERSION,
    brand: { mood: 'cultural', name: 'Cultural' },
    colorMode: 'system',
    layout: { variant: 'modern', heroStyle: 'full', navStyle: 'sticky', footerStyle: 'full', maxContentWidth: 1200 },
    sectionStyles: { hero: 'hero', about: 'emphasized', destinations: 'alternating', gallery: 'inverted' },
    metadata: {},
  },
  quality: {
    contrastAA: true,
    darkModeComplete: true,
    fontsAllowlisted: true,
    sectionStylesVerified: true,
    previewCaptured: false,
    mobileVerified: false,
  },
});

// ---------------------------------------------------------------------------
// 7. ECO
// ---------------------------------------------------------------------------

export const ECO_PRESET: ThemePreset = preset({
  metadata: {
    id: 'a0000001-0000-0000-0000-000000000007',
    name: 'Eco',
    slug: 'eco',
    description: 'Natural and sustainable — designed for eco-lodges, wildlife tours, and sustainable travel',
    category: 'eco',
    emoji: '🌿',
    tags: ['sustainable', 'nature', 'wildlife', 'eco-lodge', 'green'],
    isSystem: true,
    isActive: true,
    displayOrder: 7,
    suggestedSections: ['hero', 'about', 'features', 'destinations', 'gallery', 'newsletter'],
  },
  tokens: {
    $schema: DESIGN_TOKENS_SCHEMA_VERSION,
    colors: {
      seedColor: '#33691E',
      light: {
        primary: '#33691E',
        onPrimary: '#FFFFFF',
        primaryContainer: '#C5E1A5',
        onPrimaryContainer: '#1B3A00',
        secondary: '#5D6C4E',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#E1F0CE',
        onSecondaryContainer: '#3A4A2C',
        tertiary: '#795548',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#EFEBE9',
        onTertiaryContainer: '#4E342E',
        error: '#B3261E',
        onError: '#FFFFFF',
        errorContainer: '#F9DEDC',
        onErrorContainer: '#410E0B',
        surface: '#F8FAF0',
        onSurface: '#1A1C16',
        surfaceContainerLowest: '#FFFFFF',
        surfaceContainerLow: '#F2F4EA',
        surfaceContainer: '#ECEFE4',
        surfaceContainerHigh: '#E7E9DE',
        surfaceContainerHighest: '#E1E3D8',
        onSurfaceVariant: '#44483D',
        outline: '#75796E',
        outlineVariant: '#C5C8BA',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#2F312A',
        onInverseSurface: '#F0F2E7',
        inversePrimary: '#8BC34A',
        surfaceTint: '#33691E',
        background: '#F8FAF0',
      },
      dark: {
        primary: '#8BC34A',
        onPrimary: '#1B3A00',
        primaryContainer: '#2E5A15',
        onPrimaryContainer: '#C5E1A5',
        secondary: '#C5D3B3',
        onSecondary: '#3A4A2C',
        secondaryContainer: '#4B5B3D',
        onSecondaryContainer: '#E1F0CE',
        tertiary: '#BCAAA4',
        onTertiary: '#4E342E',
        tertiaryContainer: '#6D4C41',
        onTertiaryContainer: '#EFEBE9',
        error: '#F2B8B5',
        onError: '#601410',
        errorContainer: '#8C1D18',
        onErrorContainer: '#F9DEDC',
        surface: '#12140E',
        onSurface: '#E1E3D8',
        surfaceContainerLowest: '#0D0F09',
        surfaceContainerLow: '#1A1C16',
        surfaceContainer: '#1E201A',
        surfaceContainerHigh: '#282B24',
        surfaceContainerHighest: '#33362F',
        onSurfaceVariant: '#C5C8BA',
        outline: '#8E9285',
        outlineVariant: '#44483D',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#E1E3D8',
        onInverseSurface: '#2F312A',
        inversePrimary: '#33691E',
        surfaceTint: '#8BC34A',
        background: '#12140E',
      },
    },
    typography: {
      display: { family: 'Sora', fallback: 'sans-serif', weight: '600' },
      body: { family: 'Nunito', fallback: 'sans-serif', weight: '400' },
      scale: 'default',
      bodyLineHeight: 1.6,
      letterSpacing: 0,
    },
    shape: { radius: 'lg', buttonRadius: 'xl', cardRadius: 'xl' },
    elevation: { cardElevation: 'subtle', navElevation: 'subtle', heroElevation: 'flat' },
    motion: { preset: 'moderate', durationMs: 300, easing: 'ease-out', reducedMotion: true },
    spacing: { baseUnit: 4, scale: 'relaxed', sectionPaddingMultiplier: 2.5 },
  },
  profile: {
    $schema: THEME_PROFILE_SCHEMA_VERSION,
    brand: { mood: 'eco', name: 'Eco' },
    colorMode: 'system',
    layout: { variant: 'modern', heroStyle: 'full', navStyle: 'transparent', footerStyle: 'full', maxContentWidth: 1300 },
    sectionStyles: { hero: 'hero', features: 'card-grid', destinations: 'alternating' },
    metadata: {},
  },
  quality: {
    contrastAA: true,
    darkModeComplete: true,
    fontsAllowlisted: true,
    sectionStylesVerified: true,
    previewCaptured: false,
    mobileVerified: false,
  },
});

// ---------------------------------------------------------------------------
// 8. ROMANTIC
// ---------------------------------------------------------------------------

export const ROMANTIC_PRESET: ThemePreset = preset({
  metadata: {
    id: 'a0000001-0000-0000-0000-000000000008',
    name: 'Romántico',
    slug: 'romantic',
    description: 'Soft and elegant — designed for honeymoon packages, romantic getaways, and wedding travel',
    category: 'romantic',
    emoji: '💕',
    tags: ['honeymoon', 'wedding', 'romantic', 'couples', 'elegant'],
    isSystem: true,
    isActive: true,
    displayOrder: 8,
    suggestedSections: ['hero', 'about', 'hotels', 'gallery', 'testimonials', 'contact-form'],
  },
  tokens: {
    $schema: DESIGN_TOKENS_SCHEMA_VERSION,
    colors: {
      seedColor: '#AD1457',
      light: {
        primary: '#AD1457',
        onPrimary: '#FFFFFF',
        primaryContainer: '#FFD9E3',
        onPrimaryContainer: '#6E0035',
        secondary: '#7B5A6A',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#FFD9E8',
        onSecondaryContainer: '#5A3B4B',
        tertiary: '#8A6508',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#FFF3D4',
        onTertiaryContainer: '#4A3500',
        error: '#B3261E',
        onError: '#FFFFFF',
        errorContainer: '#F9DEDC',
        onErrorContainer: '#410E0B',
        surface: '#FFFBFF',
        onSurface: '#201A1D',
        surfaceContainerLowest: '#FFFFFF',
        surfaceContainerLow: '#FDF0F4',
        surfaceContainer: '#F7EAEE',
        surfaceContainerHigh: '#F1E4E8',
        surfaceContainerHighest: '#EBDEE2',
        onSurfaceVariant: '#514348',
        outline: '#837378',
        outlineVariant: '#D5C2C8',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#362F32',
        onInverseSurface: '#FAECF1',
        inversePrimary: '#FFB1C9',
        surfaceTint: '#AD1457',
        background: '#FFFBFF',
      },
      dark: {
        primary: '#FFB1C9',
        onPrimary: '#6E0035',
        primaryContainer: '#8E0E45',
        onPrimaryContainer: '#FFD9E3',
        secondary: '#E8B9CD',
        onSecondary: '#5A3B4B',
        secondaryContainer: '#634B5A',
        onSecondaryContainer: '#FFD9E8',
        tertiary: '#FFD54F',
        onTertiary: '#3A2800',
        tertiaryContainer: '#5C4200',
        onTertiaryContainer: '#FFF3D4',
        error: '#F2B8B5',
        onError: '#601410',
        errorContainer: '#8C1D18',
        onErrorContainer: '#F9DEDC',
        surface: '#181215',
        onSurface: '#EBDEE2',
        surfaceContainerLowest: '#120D10',
        surfaceContainerLow: '#201A1D',
        surfaceContainer: '#241E21',
        surfaceContainerHigh: '#2F282B',
        surfaceContainerHighest: '#3A3336',
        onSurfaceVariant: '#D5C2C8',
        outline: '#9D8C92',
        outlineVariant: '#514348',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#EBDEE2',
        onInverseSurface: '#362F32',
        inversePrimary: '#AD1457',
        surfaceTint: '#FFB1C9',
        background: '#181215',
      },
    },
    typography: {
      display: { family: 'Playfair Display', fallback: 'serif', weight: '500' },
      body: { family: 'Raleway', fallback: 'sans-serif', weight: '400' },
      scale: 'default',
      bodyLineHeight: 1.7,
      letterSpacing: 0.02,
    },
    shape: { radius: 'md', buttonRadius: 'lg', cardRadius: 'lg' },
    elevation: { cardElevation: 'subtle', navElevation: 'subtle', heroElevation: 'flat' },
    motion: { preset: 'subtle', durationMs: 300, easing: 'ease-in-out', reducedMotion: true },
    spacing: { baseUnit: 4, scale: 'relaxed', sectionPaddingMultiplier: 3 },
  },
  profile: {
    $schema: THEME_PROFILE_SCHEMA_VERSION,
    brand: { mood: 'romantic', name: 'Romántico' },
    colorMode: 'system',
    layout: { variant: 'classic', heroStyle: 'full', navStyle: 'sticky', footerStyle: 'full', maxContentWidth: 1100 },
    sectionStyles: { hero: 'hero', about: 'subtle', hotels: 'default', gallery: 'emphasized' },
    metadata: {},
  },
  quality: {
    contrastAA: true,
    darkModeComplete: true,
    fontsAllowlisted: true,
    sectionStylesVerified: true,
    previewCaptured: false,
    mobileVerified: false,
  },
});

// ---------------------------------------------------------------------------
// All presets
// ---------------------------------------------------------------------------

export const TOURISM_PRESETS: ThemePreset[] = [
  ADVENTURE_PRESET,
  LUXURY_PRESET,
  TROPICAL_PRESET,
  CORPORATE_PRESET,
  BOUTIQUE_PRESET,
  CULTURAL_PRESET,
  ECO_PRESET,
  ROMANTIC_PRESET,
];

export function getPresetBySlug(slug: string): ThemePreset | undefined {
  return TOURISM_PRESETS.find((p) => p.metadata.slug === slug);
}

export function getPresetsByCategory(category: string): ThemePreset[] {
  return TOURISM_PRESETS.filter((p) => p.metadata.category === category);
}
