import {
  resolvePublicUiLocale,
  type SupportedPublicUiLocale,
} from '@/lib/site/public-ui-messages';

const BASE_EXTRA_TEXTS = {
  plannersBackHome: 'Volver al inicio',
  plannersPlanTrip: 'Planear mi viaje',
  plannersAbout: 'Sobre',
  plannersSpecialty: 'Especialidad',
  plannersTravelPlannerIn: 'Travel Planner en',
  plannersVisitWebsite: 'Visitar sitio web',
  academyNameLabel: 'Nombre',
  academyNamePlaceholder: 'Tu nombre',
  academyEmailLabel: 'Correo Electronico',
  academyEmailPlaceholder: 'tu@agencia.com',
  academyHeroBadge: 'Nuevo Curso Gratuito',
  academyHeroTitlePrefix: 'Rompe tu',
  academyHeroTitleEmphasis: 'Excel',
  academyHeroSubtitle:
    'Deja de operar a ciegas. Aprende a sistematizar tu agencia de viajes y recupera tu libertad en 4 modulos practicos.',
  academyHeroStart: 'Empezar Curso Gratis',
  academyHeroSyllabus: 'Ver Temario ↓',
  academyHeroBonusLabel: 'Bonus:',
  academyHeroBonusDescription:
    'Incluye Plantilla Maestra de Cotizacion + Calculadora de Costos',
  activityCircuitMapTitle: 'Recorrido de la actividad',
  activityScheduleProgram: 'Programa',
  activityScheduleViewDetail: 'Ver detalle completo →',
  circuitMapSimplifiedView: 'Vista de circuito simplificada.',
  productPackageFallbackTitle: 'Paquete de viaje',
  itineraryViewHotel: 'Ver hotel →',
  mediaCloseVideo: 'Cerrar video',
  mediaImageGallery: 'Galeria de imagenes',
  mediaCloseGallery: 'Cerrar galeria',
  mediaPrevImage: 'Imagen anterior',
  mediaNextImage: 'Imagen siguiente',
  meetingPointGooglePlaceId: 'Google place id:',
  moduleCardModule: 'Modulo',
  moduleCardClasses: 'Clases',
  optionsTableOption: 'Opcion',
  optionsTableMode: 'Modalidad',
  optionsTableDetails: 'Detalles',
  optionsTableRefund: 'Reembolso',
  optionsTablePrice: 'Precio',
  optionsTableMin: 'Min.',
  optionsTableMax: 'Max.',
  optionsTableSchedules: 'horarios',
  packageCircuitMapTitle: 'Circuito del viaje',
  productVideoOpenAria: 'Ver video (abre en nueva pestana)',
  productVideoLabel: 'Ver video',
  productVideoAria: 'Ver video del producto',
  googleLabel: 'Google',
  reviewsViewOnGoogle: 'Ver resenas en Google',
  sectionActivitiesViewAll: 'Ver todas las actividades',
  sectionActivitiesCurated: 'Experiencias Curadas',
  sectionActivitiesTitle: 'Actividades Destacadas',
  sectionAboutTitle: 'Sobre Nosotros',
  sectionBlogTitle: 'Últimas del Blog',
  sectionCtaTitle: '¿Listo para tu proxima aventura?',
  sectionDestinationsTitle: 'Destinos Destacados',
  sectionDestinationsSubtitle: 'Descubre los lugares más increíbles',
  sectionFaqTitle: 'Preguntas Frecuentes',
  sectionFeaturesTitle: 'Nuestras Características',
  sectionFrom: 'Desde',
  sectionGalleryTitle: 'Galería',
  sectionViewActivity: 'Ver actividad',
  sectionBlogViewAllArrow: 'Ver todos →',
  sectionBlogNoPosts: 'No hay publicaciones disponibles',
  sectionBlogViewAllPosts: 'Ver todos los posts',
  sectionComparisonIncluded: 'Incluido',
  sectionComparisonNotIncluded: 'No incluido',
  sectionComparisonTitle: 'Comparativa',
  sectionComparisonFeatures: 'Caracteristicas',
  sectionComparisonBukeer: 'Bukeer',
  sectionCountdownTitle: 'Cuenta regresiva',
  sectionWhatsapp: 'WhatsApp',
  sectionActivitiesWord: 'actividades',
  sectionPackagesWord: 'paquetes',
  sectionDestinationsNoData: 'No hay destinos configurados',
  sectionDestinationsViewAll: 'Ver todos los destinos',
  sectionGuarantees: 'Garantias',
  sectionScroll: 'scroll',
  sectionHotelsViewAll: 'Ver todos los hoteles',
  sectionHotelsSelected: 'Estancias Seleccionadas',
  sectionHotelsTitle: 'Hoteles Recomendados',
  sectionViewHotel: 'Ver hotel',
  sectionInclusionsTitle: 'Incluye y no incluye',
  sectionIncludes: 'Incluye',
  sectionExcludes: 'No incluye',
  sectionItineraryTitle: 'Itinerario',
  sectionItineraryIncludesTonight: 'Incluye esta noche',
  sectionItineraryAccommodation: 'Alojamiento:',
  sectionNewsletterEmailPlaceholder: 'tu@email.com',
  sectionNewsletterTitle: 'Suscríbete a nuestro newsletter',
  sectionNewsletterSubtitle: 'Recibe ofertas exclusivas y novedades',
  sectionNewsletterButton: 'Suscribirme',
  sectionNewsletterSending: 'Enviando...',
  sectionNewsletterSuccess:
    'Gracias por suscribirte. Pronto recibiras nuestras novedades.',
  sectionPackagesTitle: 'Paquetes de Viaje',
  sectionPackagesEyebrow: 'Experiencias Curadas',
  sectionPackagesViewAll: 'Ver todos los paquetes',
  sectionPackagesCircuit: 'Circuito:',
  sectionViewPackage: 'Ver paquete',
  sectionPlannersViewProfile: 'Ver perfil',
  sectionPlannersTitle: 'Nuestros Travel Planners',
  sectionPlannersSubtitle: 'Expertos locales que disenan tu viaje ideal',
  sectionPlannersEyebrow: 'Tu guia personal',
  sectionPricingRecommended: 'Recomendado',
  sectionPricingTitle: 'Precios y paquetes',
  sectionTestimonialsViewGoogle: 'Ver en Google',
  sectionTestimonialsOfFive: 'de 5 estrellas',
  sectionTestimonialsTitle: 'Testimonios',
  sectionTestimonialsMainTitle: 'Lo que dicen nuestros viajeros',
  sectionTrustTitle: 'Confianza y certificaciones',
  sectionTrustReviewsSuffix: 'resenas)',
  sectionTrustSsl: 'Pago seguro SSL',
  sectionPartnersTitle: 'Nuestros Partners',
  sectionFilterAll: 'Todos',

  // ---------------- editorial-v1 template set ----------------
  // Chrome / layout
  editorialHeaderQuoteCta: 'Cotizar viaje',
  editorialHeaderNavAria: 'Principal',
  editorialHeaderMobileMenuAria: 'Menú móvil',
  editorialHeaderMenuOpen: 'Abrir menú',
  editorialHeaderMenuClose: 'Cerrar menú',
  editorialFooterColDestinos: 'Destinos',
  editorialFooterColViajar: 'Viajar',
  editorialFooterColAgencia: 'Agencia',
  editorialFooterColNewsletter: 'Recibe historias',
  editorialFooterViewAll: 'Ver todos',
  editorialFooterSearch: 'Buscar',
  editorialFooterEmailPlaceholder: 'tu@correo.com',
  editorialFooterEmailLabel: 'Correo electrónico',
  editorialFooterSubscribe: 'Suscribirme',
  editorialFooterNewsletterHint:
    'Un correo al mes con rincones que nos enamoran y descuentos.',
  editorialFooterTaglineFallback: 'Viaja más hondo.',
  editorialFooterAboutFallback:
    'Somos un operador local. Diseñamos viajes con guías locales y alojamientos familiares.',
  editorialFooterLegalPrivacy: 'Privacidad',
  editorialFooterLegalTerms: 'Términos',
  editorialFooterLegalCancellation: 'Política de cancelación',

  // Market switcher (header pill + footer compact)
  editorialSwitcherHeading: 'Personaliza tu',
  editorialSwitcherHeadingEmphasis: 'experiencia',
  editorialSwitcherDescription: 'Idioma del sitio y moneda de precios.',
  editorialSwitcherLanguageSubheading: 'Idioma',
  editorialSwitcherCurrencySubheading: 'Moneda',
  editorialSwitcherSavedHint: 'Guardado en este navegador',
  editorialSwitcherTriggerAria: 'Abrir preferencias de idioma y moneda',
  editorialSwitcherDialogAria: 'Personaliza tu experiencia',
  editorialSwitcherLanguageItemAria: 'Cambiar idioma',
  editorialSwitcherCurrencyItemAria: 'Cambiar moneda',
  editorialSwitcherLoadingPrefix: 'Cargando en',

  // Hero
  editorialHeroEyebrowFallback: 'DESCUBRE · VIVE · CONECTA',
  editorialHeroSideListLabel: 'Destino del mes',
  editorialHeroSlidesAria: 'Imágenes destacadas',
  editorialHeroPresenting: 'Presentando',
  editorialHeroDotsAria: 'Seleccionar slide',
  editorialHeroSlidePrefix: 'Slide',

  // Hero search
  editorialSearchPlaceholderDestino: 'Caribe · Colombia',
  editorialSearchPlaceholderFechas: 'Octubre 2026 · 7 noches',
  editorialSearchPlaceholderViajeros: '2 viajeros',
  editorialSearchSubmit: 'Buscar',
  editorialSearchDestinoLabel: 'Destino',
  editorialSearchWhenLabel: 'Cuándo',
  editorialSearchFechasAria: 'Fechas de viaje',
  editorialSearchViajerosLabel: 'Viajeros',

  // Packages
  editorialPackagesEyebrowFallback: 'EXPERIENCIAS CURADAS',
  editorialPackagesTitleFallback: 'Paquetes',
  editorialPackagesAllTab: 'Todos',
  editorialPackagesPopular: 'POPULAR',
  editorialPackagesFromPrefix: 'DESDE',
  editorialPackagesConsultPrice: 'Consultar',
  editorialPackagesCtaFallback: 'VER PAQUETE',
  editorialPackagesEmpty: 'Sin paquetes disponibles',
  editorialPackagesFiltersAria: 'Filtros de paquetes',
  editorialPackagesRailAria: 'Carrusel de paquetes',
  editorialPackagesWord: 'paquetes',
  editorialPackageWord: 'paquete',

  // Destinations
  editorialDestinationsEyebrowFallback: 'RUTAS INCONFUNDIBLES',
  editorialDestinationsTitleFallback: 'Destinos',
  editorialDestinationsEmpty: 'Sin destinos disponibles.',
  editorialDestinationsViewList: 'Lista',
  editorialDestinationsViewMap: 'Mapa',
  editorialDestinationsViewAria: 'Vista de destinos',
  editorialDestinationsMapAriaFallback: 'Mapa interactivo de destinos en Colombia',
  editorialActivitiesWord: 'actividades',

  // Explore (regions)
  editorialExploreEyebrowFallback: 'EXPLORA',
  editorialExploreTitleFallback: 'Colombia, a tu ritmo',
  editorialExploreCtaFallback: 'Ver todos los destinos',
  editorialExploreFilterAria: 'Filtrar por región',
  editorialExploreCardCta: 'Ver paquetes',
  editorialExploreMapAria: 'Mapa de Colombia — destinos por región',
  editorialRegionCaribe: 'Caribe',
  editorialRegionAndes: 'Andes',
  editorialRegionSelva: 'Selva',
  editorialRegionPacifico: 'Pacífico',
  editorialRegionCaribeHighlight: 'Playas, ciudades amuralladas y desierto.',
  editorialRegionAndesHighlight: 'Cordilleras, café y pueblos de altura.',
  editorialRegionSelvaHighlight: 'Amazonía, ríos y selva virgen.',
  editorialRegionPacificoHighlight:
    'Ballenas, gastronomía chocoana y selva costera.',

  // FAQ
  editorialFaqEyebrowFallback: 'Preguntas frecuentes',
  editorialFaqTitleFallback: 'Lo que nos preguntan antes de reservar.',
  editorialFaqOpenLabel: 'Abrir pregunta',
  editorialFaqCloseLabel: 'Cerrar pregunta',

  // Blog teaser (section)
  editorialBlogEyebrowFallback: 'BLOG',
  editorialBlogTitleFallback: 'Historias desde adentro.',
  editorialBlogViewAll: 'Ver todo el blog',
  editorialBlogNoPosts: 'Aún no hay historias.',

  // Planners (section + list)
  editorialPlannersEyebrowFallback: 'Tu planner',
  editorialPlannersTitleFallback: 'Una persona que te conoce de principio a fin.',
  editorialPlannersSubtitleFallback:
    'Emparejamos tu perfil con el planner que más sabe de la región o experiencia que buscas.',
  editorialPlannersViewAll: 'Ver todos',
  editorialPlannersQuoteFallback:
    'Diseñamos viajes hechos a tu medida, paso a paso.',
  editorialPlannersAvailable: 'Disponible',
  editorialPlannersViewProfile: 'Ver perfil',
  editorialPlannersWhatsapp: 'WhatsApp',
  editorialPlannersEmpty: 'Aún no hay travel planners publicados.',
  editorialRoleAgent: 'Agente de Viajes',
  editorialRolePlanner: 'Travel Planner',
  editorialRoleOperations: 'Operaciones',
  editorialRoleManager: 'Gerente',
  editorialRoleSales: 'Ventas',

  // Matchmaker
  editorialMatchmakerGroupQuestion: '¿Con quién viajas?',
  editorialMatchmakerRegionQuestion: '¿A qué región vas?',
  editorialMatchmakerStyleQuestion: '¿Qué estilo de viaje?',
  editorialMatchmakerMatchLabel: 'Match sugerido',
  editorialMatchmakerCta: 'Recomiéndame',

  // Promise / CTA / Testimonials / Trust
  editorialPromiseEyebrowFallback: 'Por qué nosotros',
  editorialPromiseTitleFallback: 'Un viaje bien hecho <em>se nota.</em>',
  editorialCtaTitleFallback: 'Empieza hoy <em>tu viaje.</em>',
  editorialCtaAriaFallback: 'Llamado a la acción',
  editorialTestimonialsEyebrowFallback: 'Testimonios',
  editorialTestimonialsTitleFallback: 'El recuerdo después del viaje.',
  editorialTestimonialsStarsAriaSuffix: 'de 5 estrellas',
  editorialTestimonialsVerifiedSuffix: 'reseñas verificadas',
  editorialTestimonialsAverage: 'promedio',
  editorialTestimonialsReviews: 'reseñas',
  editorialTestimonialsGoogleAria: 'Ver reseñas en Google',
  editorialTestimonialsListAria: 'Otras reseñas',
  editorialTrustLiveLabel: 'Planners en línea',
  editorialTrustResponsePrefix: 'responden en ~',
  editorialTrustResponseFallback: 'responden pronto',
  editorialTrustCertified: 'operador local certificado',
  editorialTrustRatingAverage: 'rating promedio',
  editorialTrustRecommendation: 'viajeros recomendarían',
  editorialTrustYearsSuffix: 'años',
  editorialTrustSatisfactionSuffix: 'satisfacción',
  editorialTrustHumanReview: 'Revisado por humanos',
  editorialTrustHumanReviewBody: 'cada itinerario',
  editorialTrustAriaLabel: 'Credibilidad y confianza',
  editorialTrustVerifiedSuffix: 'reseñas verificadas',

  // Listing map
  editorialListingMapAriaFallback: 'Mapa de listado',
  editorialListingMapCardsAria: 'Listado sincronizado con el mapa',

  // Blog list page
  editorialBlogListEyebrow: 'Blog',
  editorialBlogListTitle: 'Historias',
  editorialBlogListEmphasis: 'desde adentro.',
  editorialBlogListSubtitle:
    'Escrito por los planners que caminan Colombia todos los meses. Guías, itinerarios, oficios y rincones.',
  editorialBlogListAllTab: 'Todo',
  editorialBlogEmptyHeading: 'Nada con esos criterios',
  editorialBlogEmptyBody: 'Prueba otra categoría o palabra.',
  editorialBlogLoadMore: 'Cargar más historias',
  editorialBlogPrev: 'Anterior',
  editorialBlogNext: 'Siguiente',
  editorialBlogReadCta: 'Leer artículo',
  editorialBlogReadingSuffix: 'min de lectura',
  editorialBlogPaginationAria: 'Paginación del blog',
  editorialBlogToolbarAria: 'Filtros del blog',
  editorialBlogSearchAria: 'Buscar historias',
  editorialBlogSearchPlaceholder: 'Buscar historias…',

  // Blog detail page
  editorialBlogShare: 'Compartir',
  editorialBlogTags: 'Etiquetas',
  editorialBlogAuthorEyebrow: 'Escrito por',
  editorialBlogCtaEyebrow: '¿Te gustaría vivirlo?',
  editorialBlogCtaTitlePrefix: 'Diseñamos un viaje a tu medida',
  editorialBlogCtaTitleEm: 'por esta región.',
  editorialBlogCtaBody:
    'Cuéntale a nuestro equipo qué te interesa y recibe una propuesta en 24h.',
  editorialBlogCtaPrimary: 'Planear mi viaje',
  editorialBlogCtaWhatsapp: 'WhatsApp',
  editorialBlogRelatedHeading: 'Sigue',
  editorialBlogRelatedHeadingEm: 'leyendo.',
  editorialBlogRelatedCta: 'Ver todo el blog',
  editorialBlogAuthorBioFallback:
    'Diseña rutas en Colombia para viajeros que quieren ir más hondo que la guía.',

  // Experiences page
  editorialExperiencesEyebrow: 'Experiencias',
  editorialExperiencesTitle: 'Actividades',
  editorialExperiencesEmphasis: 'para sumar a tu viaje.',
  editorialExperiencesSubtitle:
    'Oficios, caminatas, cocina, mar, selva. Reservables sueltas o como add-on a cualquier paquete.',
  editorialExperiencesDurationLabel: 'Duración',
  editorialExperiencesRegionLabel: 'Región',
  editorialExperiencesLevelLabel: 'Nivel',
  editorialExperiencesClearAll: 'Limpiar todo',
  editorialExperiencesCountSuffix: 'experiencias',
  editorialExperiencesEmptyHeading: 'Nada con esos criterios',
  editorialExperiencesEmptyBody: 'Ajusta los filtros o empieza de cero.',
  editorialExperiencesClearLabel: 'Limpiar filtros',
  editorialExperiencesFromPrefix: 'Desde',
  editorialExperienceCategoryAll: 'Todas',
  editorialExperienceCategoryAdventure: 'Aventura',
  editorialExperienceCategoryGastronomy: 'Gastronomía',
  editorialExperienceCategoryCulture: 'Cultura',
  editorialExperienceCategoryNature: 'Naturaleza',
  editorialExperienceCategorySea: 'Mar',
  editorialExperienceCategoryWellness: 'Bienestar',
  editorialExperienceLevelEasy: 'Fácil',
  editorialExperienceLevelModerate: 'Moderado',
  editorialExperienceLevelDemanding: 'Exigente',
  editorialExperienceLevelIntense: 'Intenso',
  editorialExperienceDurationAny: 'Cualquiera',
  editorialExperienceDurationShort: 'Menos de 4h',
  editorialExperienceDurationHalfDay: 'Medio día',
  editorialExperienceDurationFullDay: 'Día completo',
  editorialExperienceDurationMultiDay: 'Multi-día',

  // Planners list page
  editorialPlannersListHeroEyebrow: 'Nuestros planners',
  editorialPlannersListHeroTitle: 'Una persona',
  editorialPlannersListHeroEmphasis: 'que conoce su tierra.',
  editorialPlannersListHeroSubtitle:
    'Seis especialistas locales. Cada uno con una región, un oficio y 5–11 años diseñando viajes a medida por Colombia.',
  editorialPlannersListIntroEyebrow: 'Por qué un planner local',
  editorialPlannersListIntroTitlePart1: 'No somos un motor de reservas —',
  editorialPlannersListIntroTitleEm: 'somos personas',
  editorialPlannersListIntroTitlePart2: 'que han caminado Colombia.',
  editorialPlannersListIntroBody:
    'Cuando reservas con nosotros, no hablas con un call center. Te emparejamos con la persona que vive en la región donde quieres ir, habla tu idioma, y conoce a los chefs, guías, y familias que harán tu viaje distinto al de los demás.',
  editorialPlannersListStatsPlanners: 'Planners locales',
  editorialPlannersListStatsRating: 'Reseñas promedio',
  editorialPlannersListStatsTrips: 'Viajes diseñados',
  editorialPlannersListSingular: 'planner',
  editorialPlannersListPlural: 'planners',
  editorialPlannersListSortBy: 'ordenar por',
  editorialPlannersListSortByValue: 'reseñas',
  editorialPlannersListCardViewProfile: 'Ver perfil',
  editorialPlannersListCardAvailable: 'Disponible',
  editorialPlannersListCardYearsSuffix: 'años',
  editorialMatchmakerHeadingEyebrow: 'Encuentra tu planner',
  editorialMatchmakerHeadingTitle: 'Dinos qué buscas',
  editorialMatchmakerHeadingTitleEm: 'y te emparejamos en 30 segundos.',
  editorialMatchmakerHeadingBody:
    'No todos los planners hacen todas las regiones. Cuéntanos dónde quieres ir y qué te mueve — nosotros sabemos quién firma ese viaje.',
  editorialMatchmakerHeadingCta: 'Hablar con mi match',
  editorialMatchmakerSubmit: 'Enviar',

  // Planner detail page
  editorialPlannerDetailBio: 'Sobre',
  editorialPlannerDetailDifferentiators: 'Lo que',
  editorialPlannerDetailDifferentiatorsEm: 'hace diferente',
  editorialPlannerDetailSpecialtiesLabel: 'Especialidades',
  editorialPlannerDetailRegionsLabel: 'Regiones',
  editorialPlannerDetailSignature: 'Viaje',
  editorialPlannerDetailSignatureEm: 'firma',
  editorialPlannerDetailSignatureSubLabel: 'ITINERARIO DESTACADO',
  editorialPlannerDetailHallmarks: 'Otros paquetes',
  editorialPlannerDetailHallmarksEm: 'que diseña',
  editorialPlannerDetailFacts: 'Detalles',
  editorialPlannerDetailFactsEm: 'personales',
  editorialPlannerDetailReviewsTitle: 'Lo que dicen',
  editorialPlannerDetailReviewsEm: 'viajeros de',
  editorialPlannerDetailOtherPlanners: 'Otros',
  editorialPlannerDetailOtherPlannersEm: 'planners',
  editorialPlannerDetailKpiExperience: 'Experiencia',
  editorialPlannerDetailKpiTrips: 'Viajes',
  editorialPlannerDetailKpiRating: 'Rating',
  editorialPlannerDetailKpiLanguages: 'Idiomas',
  editorialPlannerDetailRailSpeakWith: 'Hablar con',
  editorialPlannerDetailRailResponseTime: 'Tiempo de respuesta',
  editorialPlannerDetailRailFrom: 'Desde',
  editorialPlannerDetailRailLanguages: 'Idiomas',
  editorialPlannerDetailRailPrimaryCta: 'Escribir a',
  editorialPlannerDetailRailSecondaryCta: 'Pedir propuesta',
  editorialPlannerDetailRailFootnote:
    'Sin compromiso · Primera propuesta en <2h hábiles',
  editorialPlannerDetailSignaturePrimaryCta: 'Ver itinerario',
  editorialPlannerDetailSignatureSecondaryCta: 'Pedirle a',
  editorialPlannerDetailSignatureChip: 'Firma de',
  editorialPlannerDetailBioFallback:
    'Diseña viajes a medida por Colombia con ritmo propio, ojo para los detalles que no salen en las guías y una red local que sólo se construye caminando.',
  editorialPlannerDetailDefaultResponse: '~3 min',

  // Product detail breadcrumbs / package / activity / hotel overlays
  editorialBreadcrumbHome: 'Inicio',
  editorialBreadcrumbPackages: 'Paquetes',
  editorialBreadcrumbActivities: 'Actividades',
  editorialBreadcrumbHotels: 'Hoteles',
  editorialBreadcrumbBlog: 'Blog',
  editorialPackageMapTitle: 'Ruta del viaje',
  editorialPackageStopsSuffix: 'paradas',
  editorialPackageTimelineEyebrow: 'Día a día',
  editorialPackageTimelineTitle: 'Itinerario detallado',
  editorialPackageHotelsEyebrow: 'Hospedaje',
  editorialPackageHotelsTitle: 'Hoteles incluidos',
  editorialPackageFlightsEyebrow: 'Vuelos',
  editorialPackageFlightsTitle: 'Vuelos incluidos',
  editorialActivityHighlightsEyebrow: 'Lo que vivirás',
  editorialActivityHighlightsTitle: 'Momentos destacados',
  editorialHotelAmenitiesEyebrow: 'Amenidades',
  editorialHotelAmenitiesTitle: 'Lo que este hotel ofrece',
  editorialHotelHighlightsEyebrow: 'Por qué elegirlo',
  editorialHotelHighlightsTitle: 'Aspectos destacados',
  editorialHotelStarsSuffix: 'estrellas',

  // Misc reused labels
  editorialShareLabel: 'Compartir',
  editorialSaveLabel: 'Guardar',
  editorialLoadMore: 'Cargar más',
  editorialFilterAll: 'Todos',
  editorialEmptyResults: 'No encontramos resultados',
  editorialNextStep: 'Continuar',
  editorialPrevStep: 'Anterior',
  editorialSubmitLead: 'Enviar',
  editorialVerifySMS: 'Verificar',
} as const;

export type PublicUiExtraTextKey = keyof typeof BASE_EXTRA_TEXTS;

const EN_US_OVERRIDES: Partial<Record<PublicUiExtraTextKey, string>> = {};
const PT_BR_OVERRIDES: Partial<Record<PublicUiExtraTextKey, string>> = {};

const EXTRA_TEXTS_BY_LOCALE: Record<
  SupportedPublicUiLocale,
  Record<PublicUiExtraTextKey, string>
> = {
  'es-CO': { ...BASE_EXTRA_TEXTS },
  'en-US': { ...BASE_EXTRA_TEXTS, ...EN_US_OVERRIDES },
  'pt-BR': { ...BASE_EXTRA_TEXTS, ...PT_BR_OVERRIDES },
};

export function getPublicUiExtraText(
  localeLike: string | null | undefined,
  key: PublicUiExtraTextKey,
): string {
  const locale = resolvePublicUiLocale(localeLike);
  return EXTRA_TEXTS_BY_LOCALE[locale][key];
}

export function getPublicUiExtraTextGetter(localeLike: string | null | undefined) {
  const locale = resolvePublicUiLocale(localeLike);
  const dictionary = EXTRA_TEXTS_BY_LOCALE[locale];
  return (key: PublicUiExtraTextKey): string => dictionary[key];
}
