import {
  resolvePublicUiLocale,
  type SupportedPublicUiLocale,
} from '@/lib/site/public-ui-messages';

const BASE_EXTRA_TEXTS = {
  plannersBackHome: 'Volver al inicio',
  plannersPlanTrip: 'Planear mi viaje',
  plannersAbout: 'Sobre',
  plannersSpecialty: 'Especialidad',
  plannersTravelPlannerIn: 'Travel Planner en',
  plannersVisitWebsite: 'Visitar sitio web',
  academyNameLabel: 'Nombre',
  academyNamePlaceholder: 'Tu nombre',
  academyEmailLabel: 'Correo Electronico',
  academyEmailPlaceholder: 'tu@agencia.com',
  academyHeroBadge: 'Nuevo Curso Gratuito',
  academyHeroTitlePrefix: 'Rompe tu',
  academyHeroTitleEmphasis: 'Excel',
  academyHeroSubtitle:
    'Deja de operar a ciegas. Aprende a sistematizar tu agencia de viajes y recupera tu libertad en 4 modulos practicos.',
  academyHeroStart: 'Empezar Curso Gratis',
  academyHeroSyllabus: 'Ver Temario ↓',
  academyHeroBonusLabel: 'Bonus:',
  academyHeroBonusDescription:
    'Incluye Plantilla Maestra de Cotizacion + Calculadora de Costos',
  activityCircuitMapTitle: 'Recorrido de la actividad',
  activityScheduleProgram: 'Programa',
  activityScheduleViewDetail: 'Ver detalle completo →',
  circuitMapSimplifiedView: 'Vista de circuito simplificada.',
  productPackageFallbackTitle: 'Paquete de viaje',
  itineraryViewHotel: 'Ver hotel →',
  mediaCloseVideo: 'Cerrar video',
  mediaImageGallery: 'Galeria de imagenes',
  mediaCloseGallery: 'Cerrar galeria',
  mediaPrevImage: 'Imagen anterior',
  mediaNextImage: 'Imagen siguiente',
  meetingPointGooglePlaceId: 'Google place id:',
  moduleCardModule: 'Modulo',
  moduleCardClasses: 'Clases',
  optionsTableOption: 'Opcion',
  optionsTableMode: 'Modalidad',
  optionsTableDetails: 'Detalles',
  optionsTableRefund: 'Reembolso',
  optionsTablePrice: 'Precio',
  optionsTableMin: 'Min.',
  optionsTableMax: 'Max.',
  optionsTableSchedules: 'horarios',
  packageCircuitMapTitle: 'Circuito del viaje',
  productVideoOpenAria: 'Ver video (abre en nueva pestana)',
  productVideoLabel: 'Ver video',
  productVideoAria: 'Ver video del producto',
  googleLabel: 'Google',
  reviewsViewOnGoogle: 'Ver resenas en Google',
  sectionActivitiesViewAll: 'Ver todas las actividades',
  sectionActivitiesCurated: 'Experiencias Curadas',
  sectionActivitiesTitle: 'Actividades Destacadas',
  sectionAboutTitle: 'Sobre Nosotros',
  sectionBlogTitle: 'Últimas del Blog',
  sectionCtaTitle: '¿Listo para tu proxima aventura?',
  sectionDestinationsTitle: 'Destinos Destacados',
  sectionDestinationsSubtitle: 'Descubre los lugares más increíbles',
  sectionFaqTitle: 'Preguntas Frecuentes',
  sectionFeaturesTitle: 'Nuestras Características',
  sectionFrom: 'Desde',
  sectionGalleryTitle: 'Galería',
  sectionViewActivity: 'Ver actividad',
  sectionBlogViewAllArrow: 'Ver todos →',
  sectionBlogNoPosts: 'No hay publicaciones disponibles',
  sectionBlogViewAllPosts: 'Ver todos los posts',
  sectionComparisonIncluded: 'Incluido',
  sectionComparisonNotIncluded: 'No incluido',
  sectionComparisonTitle: 'Comparativa',
  sectionComparisonFeatures: 'Caracteristicas',
  sectionComparisonBukeer: 'Bukeer',
  sectionCountdownTitle: 'Cuenta regresiva',
  sectionWhatsapp: 'WhatsApp',
  sectionActivitiesWord: 'actividades',
  sectionPackagesWord: 'paquetes',
  sectionDestinationsNoData: 'No hay destinos configurados',
  sectionDestinationsViewAll: 'Ver todos los destinos',
  sectionGuarantees: 'Garantias',
  sectionScroll: 'scroll',
  sectionHotelsViewAll: 'Ver todos los hoteles',
  sectionHotelsSelected: 'Estancias Seleccionadas',
  sectionHotelsTitle: 'Hoteles Recomendados',
  sectionViewHotel: 'Ver hotel',
  sectionInclusionsTitle: 'Incluye y no incluye',
  sectionIncludes: 'Incluye',
  sectionExcludes: 'No incluye',
  sectionItineraryTitle: 'Itinerario',
  sectionItineraryIncludesTonight: 'Incluye esta noche',
  sectionItineraryAccommodation: 'Alojamiento:',
  sectionNewsletterEmailPlaceholder: 'tu@email.com',
  sectionNewsletterTitle: 'Suscríbete a nuestro newsletter',
  sectionNewsletterSubtitle: 'Recibe ofertas exclusivas y novedades',
  sectionNewsletterButton: 'Suscribirme',
  sectionNewsletterSending: 'Enviando...',
  sectionNewsletterSuccess:
    'Gracias por suscribirte. Pronto recibiras nuestras novedades.',
  sectionPackagesAllDestinations: 'Todos los destinos',
  sectionPackagesTitle: 'Paquetes de Viaje',
  sectionPackagesEyebrow: 'Experiencias Curadas',
  sectionPackagesViewAll: 'Ver todos los paquetes',
  sectionPackagesCircuit: 'Circuito:',
  sectionViewPackage: 'Ver paquete',
  sectionPlannersViewProfile: 'Ver perfil',
  sectionPlannersTitle: 'Nuestros Travel Planners',
  sectionPlannersSubtitle: 'Expertos locales que disenan tu viaje ideal',
  sectionPlannersEyebrow: 'Tu guia personal',
  sectionPricingRecommended: 'Recomendado',
  sectionPricingTitle: 'Precios y paquetes',
  sectionTestimonialsViewGoogle: 'Ver en Google',
  sectionTestimonialsOfFive: 'de 5 estrellas',
  sectionTestimonialsTitle: 'Testimonios',
  sectionTestimonialsMainTitle: 'Lo que dicen nuestros viajeros',
  sectionTrustTitle: 'Confianza y certificaciones',
  sectionTrustReviewsSuffix: 'resenas)',
  sectionTrustSsl: 'Pago seguro SSL',
  sectionPartnersTitle: 'Nuestros Partners',
  sectionFilterAll: 'Todos',

  // ---------------- editorial-v1 template set ----------------
  // Chrome / layout
  editorialHeaderQuoteCta: 'Cotizar viaje',
  editorialHeaderWhatsappCta: 'Planear por WhatsApp',
  editorialHeaderNavAria: 'Principal',
  editorialHeaderMobileMenuAria: 'Menú móvil',
  editorialHeaderMenuOpen: 'Abrir menú',
  editorialHeaderMenuClose: 'Cerrar menú',
  editorialFooterColDestinos: 'Destinos',
  editorialFooterColViajar: 'Viajar',
  editorialFooterColAgencia: 'Agencia',
  editorialFooterColNewsletter: 'Recibe historias',
  editorialFooterViewAll: 'Ver todos',
  editorialFooterSearch: 'Buscar',
  editorialFooterEmailPlaceholder: 'tu@correo.com',
  editorialFooterEmailLabel: 'Correo electrónico',
  editorialFooterSubscribe: 'Suscribirme',
  editorialFooterNewsletterHint:
    'Un correo al mes con rincones que nos enamoran y descuentos.',
  editorialFooterTaglineFallback: 'Viaja más hondo.',
  editorialFooterAboutFallback:
    'Somos un operador local. Diseñamos viajes con guías locales y alojamientos familiares.',
  editorialFooterLegalPrivacy: 'Privacidad',
  editorialFooterLegalTerms: 'Términos',
  editorialFooterLegalCancellation: 'Política de cancelación',

  // Market switcher (header pill + footer compact)
  editorialSwitcherHeading: 'Personaliza tu',
  editorialSwitcherHeadingEmphasis: 'experiencia',
  editorialSwitcherDescription: 'Idioma del sitio y moneda de precios.',
  editorialSwitcherLanguageSubheading: 'Idioma',
  editorialSwitcherCurrencySubheading: 'Moneda',
  editorialSwitcherSavedHint: 'Guardado en este navegador',
  editorialSwitcherTriggerAria: 'Abrir preferencias de idioma y moneda',
  editorialSwitcherDialogAria: 'Personaliza tu experiencia',
  editorialSwitcherLanguageItemAria: 'Cambiar idioma',
  editorialSwitcherCurrencyItemAria: 'Cambiar moneda',
  editorialSwitcherLoadingPrefix: 'Cargando en',

  // Hero
  editorialHeroEyebrowFallback: 'VIAJA · VIVE · CONECTA',
  editorialHeroHeadlineFallback: 'Diseñamos viajes <em>a tu medida</em> por toda Colombia.',
  editorialHeroSubtitleFallback: 'Diseñamos experiencias auténticas con expertos locales.',
  editorialHeroSideListLabel: 'Destino del mes',
  editorialHeroSlidesAria: 'Imágenes destacadas',
  editorialHeroPresenting: 'Presentando',
  editorialHeroDotsAria: 'Seleccionar slide',
  editorialHeroSlidePrefix: 'Slide',
  editorialHeroWhatsappMeta: 'Responden en ~3 min · Planner humano',

  // Hero search
  editorialSearchPlaceholderDestino: 'Caribe · Colombia',
  editorialSearchPlaceholderFechas: 'Octubre 2026 · 7 noches',
  editorialSearchPlaceholderViajeros: '2 viajeros',
  editorialSearchSubmit: 'Buscar',
  editorialSearchDestinoLabel: 'Destino',
  editorialSearchWhenLabel: 'Cuándo',
  editorialSearchFechasAria: 'Fechas de viaje',
  editorialSearchViajerosLabel: 'Viajeros',

  // Packages
  editorialPackagesEyebrowFallback: 'PAQUETES',
  editorialPackagesTitleFallback: 'Planes <em>por toda Colombia.</em>',
  editorialPackagesSubtitleFallback: 'Itinerarios diseñados por planners locales. Ajustables, flexibles, punto de partida para tu viaje.',
  editorialPackagesAllTab: 'Todos',
  editorialPackagesPopular: 'POPULAR',
  editorialPackagesFromPrefix: 'DESDE',
  editorialPackagesConsultPrice: 'Consultar',
  editorialPackagesCtaFallback: 'VER PAQUETE',
  editorialPackagesEmpty: 'Sin paquetes disponibles',
  editorialPackagesFiltersAria: 'Filtros de paquetes',
  editorialPackagesRailAria: 'Carrusel de paquetes',
  editorialPackagesWord: 'paquetes',
  editorialPackageWord: 'paquete',
  editorialPackagesClearLabel: 'Limpiar',
  editorialPackagesClearLink: 'limpiar filtros',
  editorialPackagesCountryLabel: 'País',
  editorialPackagesLocationLabel: 'Ubicación',
  editorialPackagesKeywordLabel: 'Palabra clave',
  editorialPackagesKeywordPlaceholder: 'Buscar por palabra clave',
  editorialPackagesDurationLabel: 'Duración',
  editorialPackagesDurationAny: 'Cualquiera',
  editorialPackagesViewList: 'Lista',
  editorialPackagesViewMap: 'Mapa',
  editorialPackagesViewAria: 'Vista de paquetes',
  editorialPackagesLoadMore: 'Cargar más',
  editorialPackagesEmptyHeading: 'Ningún paquete con esos filtros',
  editorialPackagesEmptyBody: 'Prueba ensanchando el rango o limpiando filtros.',
  editorialPackagesEmptyCta: 'Limpiar filtros',
  editorialPackagesFromPerPerson: 'Desde · por persona',
  editorialPackagesViewPackageShort: 'Ver',
  editorialPackagesCountSeparator: 'de',
  editorialPackagesPopularBadge: 'Popular',

  editorialDestinationsEyebrowFallback: 'RUTAS INCONFUNDIBLES',
  editorialDestinationsTitleFallback: 'Destinos',
  editorialDestinationsSubtitle: 'Lugares mágicos que capturan la esencia de Colombia. Desde playas vírgenes hasta cumbres nevadas.',
  editorialHotelsEyebrow: 'HOTELES',
  editorialHotelsTitle: 'Estancias <em>curadas por ciudad.</em>',
  editorialHotelsSubtitle: 'Fincas, boutiques y resorts seleccionados por nuestros planners. Cambia de categoría sin reconstruir el viaje.',
  editorialHotelsCityLabel: 'Ciudad',
  editorialHotelsStarsLabel: 'Estrellas',
  editorialHotelsAmenityLabel: 'Servicios',
  editorialHotelsViewList: 'Lista',
  editorialHotelsViewMap: 'Mapa',
  editorialHotelsViewAria: 'Vista de hoteles',
  editorialHotelsLoadMore: 'Cargar más',
  editorialHotelsEmptyHeading: 'Ningún hotel con esos filtros',
  editorialHotelsEmptyBody: 'Prueba ensanchando el rango o limpiando filtros.',
  editorialHotelsEmptyCta: 'Limpiar filtros',
  editorialHotelsClearLink: 'limpiar filtros',
  editorialHotelsCountSingular: 'hotel',
  editorialHotelsCountPlural: 'hoteles',
  editorialHotelsCountSeparator: 'de',

  // WhatsApp Flow
  waflowCloseBubble: 'Cerrar bocadillo',
  waflowFabTitle: '¿Planeas un viaje?',
  waflowFabSubtitlePrefix: 'Chatea con un planner — responde en ~',
  waflowFabAria: 'Chat por WhatsApp con un planner',
  waflowDialogAria: 'Planear mi viaje',
  waflowClose: 'Cerrar',
  waflowOnlineNow: 'Planners en línea ahora',
  waflowOnline: 'Planners en línea',
  waflowResponsePrefix: 'Responden en ~',
  waflowSkipToChat: 'Prefiero contarlo en el chat →',
  waflowStepPrefix: 'Paso',
  waflowStepOf: 'de',
  waflowHeroATitle: 'Cuéntanos <em>qué sueñas.</em>',
  waflowHeroASubtitle: 'Te contactamos en WhatsApp con un planner humano. Respondemos en promedio en 3 min.',
  waflowHeroBTitlePrefix: 'Viaja a',
  waflowHeroBSubtitle: 'Cuéntanos los detalles básicos y tu planner te arma una propuesta en 24h.',
  waflowHeroDTitleSuffix: 'hazlo tuyo.',
  waflowHeroDSubtitle: 'Ajustamos fechas, hoteles y actividades hasta que sea el viaje que quieres.',
  waflowFromPrefix: 'desde',
  waflowChangeCountryAriaPrefix: 'Cambiar país, seleccionado',
  waflowCountrySearch: 'Buscar país o indicativo',
  waflowCountriesAria: 'Países',
  waflowCountryNotFound: 'No encontramos ese país',
  waflowSubmitA: 'Enviar y abrir WhatsApp',
  waflowSubmitBPrefix: 'Planear mi viaje a',
  waflowSubmitD: 'Continuar con este paquete',
  waflowPhoneErrorPrefix: 'Escribe tu WhatsApp con 7 a 15 dígitos. Puedes incluir',
  waflowPhoneErrorSuffix: 'o dejar solo el número local.',
  waflowFallbackName: 'Viajero',
  waflowPhoneLabel: 'Tu WhatsApp',
  waflowRequired: 'Requerido',
  waflowPhonePlaceholder: 'número',
  waflowWhenLabel: '¿Cuándo te gustaría viajar?',
  waflowApprox: 'Aprox',
  waflowNameLabel: 'Tu nombre',
  waflowOptional: 'Opcional',
  waflowNamePlaceholder: 'Como quieres que te llamemos',
  waflowSending: 'Enviando…',
  waflowPrivacy: 'Tu número se usa solo para este viaje. Sin spam. Sin llamadas automáticas.',
  waflowConfirmationTitle: 'WhatsApp se abrió en una pestaña nueva.',
  waflowConfirmationBodyPrefix: 'Si no se abrió, toca el botón verde. Tu planner responde en promedio en',
  waflowConfirmationBodySuffix: 'y te escribe también desde nuestro lado.',
  waflowOpenWhatsapp: 'Abrir WhatsApp',
  waflowKeepExploring: 'Seguir explorando',
  waflowRefLabel: 'Ref:',
  editorialExperiencesEyebrowFallback: 'ACTIVIDADES',
  editorialDestinationsEmpty: 'Sin destinos disponibles.',
  editorialDestinationsViewList: 'Lista',
  editorialDestinationsViewMap: 'Mapa',
  editorialDestinationsViewAria: 'Vista de destinos',
  editorialDestinationsMapAriaFallback: 'Mapa interactivo de destinos en Colombia',
  editorialActivitiesWord: 'actividades',

  // Explore (regions)
  editorialExploreEyebrowFallback: 'EXPLORA',
  editorialExploreTitleFallback: 'Colombia, a tu ritmo',
  editorialExploreCtaFallback: 'Ver todos los destinos',
  editorialExploreFilterAria: 'Filtrar por región',
  editorialExploreCardCta: 'Ver paquetes',
  editorialExploreMapAria: 'Mapa de Colombia — destinos por región',
  editorialRegionCaribe: 'Caribe',
  editorialRegionAndes: 'Andes',
  editorialRegionSelva: 'Selva',
  editorialRegionPacifico: 'Pacífico',
  editorialRegionCaribeHighlight: 'Playas, ciudades amuralladas y desierto.',
  editorialRegionAndesHighlight: 'Cordilleras, café y pueblos de altura.',
  editorialRegionSelvaHighlight: 'Amazonía, ríos y selva virgen.',
  editorialRegionPacificoHighlight:
    'Ballenas, gastronomía chocoana y selva costera.',

  // Itinerary Accordion
  editorialItineraryEyebrowFallback: 'Itinerario',

  // Pricing
  editorialPricingEyebrowFallback: 'Precios',

  // FAQ
  editorialFaqEyebrowFallback: 'Preguntas frecuentes',
  editorialFaqTitleFallback: 'Lo que nos preguntan antes de reservar.',
  editorialFaqOpenLabel: 'Abrir pregunta',
  editorialFaqCloseLabel: 'Cerrar pregunta',

  // Blog teaser (section)
  editorialBlogEyebrowFallback: 'BLOG',
  editorialBlogTitleFallback: 'Historias <em>desde adentro.</em>',
  editorialBlogViewAll: 'Ver todo el blog',
  editorialBlogNoPosts: 'Aún no hay historias.',

  // Planners (section + list)
  editorialPlannersEyebrowFallback: 'Tu planner',
  editorialPlannersTitleFallback: 'Una persona que te conoce de principio a fin.',
  editorialPlannersSubtitleFallback:
    'Emparejamos tu perfil con el planner que más sabe de la región o experiencia que buscas.',
  editorialPlannersViewAll: 'Ver todos',
  editorialPlannersQuoteFallback:
    'Diseñamos viajes hechos a tu medida, paso a paso.',
  editorialPlannersAvailable: 'Disponible',
  editorialPlannersViewProfile: 'Ver perfil',
  editorialPlannersWhatsapp: 'WhatsApp',
  editorialPlannersYearsText: 'años diseñando viajes a medida.',
  editorialPlannersEmpty: 'Aún no hay travel planners publicados.',
  editorialRoleAgent: 'Agente de Viajes',
  editorialRolePlanner: 'Travel Planner',
  editorialRoleOperations: 'Operaciones',
  editorialRoleManager: 'Gerente',
  editorialRoleSales: 'Ventas',

  // Matchmaker
  editorialMatchmakerGroupQuestion: '¿Con quién viajas?',
  editorialMatchmakerRegionQuestion: '¿A qué región vas?',
  editorialMatchmakerStyleQuestion: '¿Qué estilo de viaje?',
  editorialMatchmakerMatchLabel: 'Match sugerido',
  editorialMatchmakerCta: 'Recomiéndame',

  // Promise / CTA / Testimonials / Trust
  editorialPromiseEyebrowFallback: 'Por qué nosotros',
  editorialPromiseTitleFallback: 'Un viaje bien hecho <em>se nota.</em>',
  editorialCtaTitleFallback: 'Empieza hoy <em>tu gran viaje.</em>',
  editorialCtaAriaFallback: 'Llamado a la acción',
  editorialTestimonialsEyebrowFallback: 'Testimonios',
  editorialTestimonialsTitleFallback: 'El recuerdo después del viaje.',
  editorialTestimonialsStarsAriaSuffix: 'de 5 estrellas',
  editorialTestimonialsVerifiedSuffix: 'reseñas verificadas',
  editorialTestimonialsAverage: 'promedio',
  editorialTestimonialsReviews: 'reseñas',
  editorialTestimonialsGoogleAria: 'Ver reseñas en Google',
  editorialTestimonialsListAria: 'Otras reseñas',
  editorialTrustLiveLabel: 'Planners en línea',
  editorialTrustResponsePrefix: 'responden en ~',
  editorialTrustResponseFallback: 'responden pronto',
  editorialTrustCertified: 'operador local certificado',
  editorialTrustRatingAverage: 'rating promedio',
  editorialTrustRecommendation: 'viajeros recomendarían',
  editorialTrustYearsSuffix: 'años',
  editorialTrustSatisfactionSuffix: 'satisfacción',
  editorialTrustHumanReview: 'Revisado por humanos',
  editorialTrustHumanReviewBody: 'cada itinerario',
  editorialTrustAriaLabel: 'Credibilidad y confianza',
  editorialTrustVerifiedSuffix: 'reseñas verificadas',
  editorialTrustLogosLabel: 'Reconocidos por',

  // Listing map
  editorialListingMapAriaFallback: 'Mapa de listado',
  editorialListingMapCardsAria: 'Listado sincronizado con el mapa',

  // Blog list page
  editorialBlogListEyebrow: 'Blog',
  editorialBlogListTitle: 'Historias <em>desde adentro.</em>',
  editorialBlogListEmphasis: 'desde adentro.',
  editorialBlogListSubtitle:
    'Escrito por los planners que caminan Colombia todos los meses. Guías, itinerarios, oficios y rincones.',
  editorialBlogListAllTab: 'Todo',
  editorialBlogEmptyHeading: 'Nada con esos criterios',
  editorialBlogEmptyBody: 'Prueba otra categoría o palabra.',
  editorialBlogLoadMore: 'Cargar más historias',
  editorialBlogPrev: 'Anterior',
  editorialBlogNext: 'Siguiente',
  editorialBlogReadCta: 'Leer artículo',
  editorialBlogReadingSuffix: 'min de lectura',
  editorialBlogPaginationAria: 'Paginación del blog',
  editorialBlogToolbarAria: 'Filtros del blog',
  editorialBlogSearchAria: 'Buscar historias',
  editorialBlogSearchPlaceholder: 'Buscar historias…',

  // Blog detail page
  editorialBlogShare: 'Compartir',
  editorialBlogTags: 'Etiquetas',
  editorialBlogAuthorEyebrow: 'Escrito por',
  editorialBlogCtaEyebrow: '¿Te gustaría vivirlo?',
  editorialBlogCtaTitlePrefix: 'Diseñamos un viaje a tu medida',
  editorialBlogCtaTitleEm: 'por esta región.',
  editorialBlogCtaBody:
    'Cuéntale a nuestro equipo qué te interesa y recibe una propuesta en 24h.',
  editorialBlogCtaPrimary: 'Planear mi viaje',
  editorialBlogCtaWhatsapp: 'WhatsApp',
  editorialBlogRelatedHeading: 'Sigue',
  editorialBlogRelatedHeadingEm: 'leyendo.',
  editorialBlogRelatedCta: 'Ver todo el blog',
  editorialBlogAuthorBioFallback:
    'Diseña rutas en Colombia para viajeros que quieren ir más hondo que la guía.',

  // Experiences page
  editorialExperiencesEyebrow: 'Experiencias',
  editorialExperiencesTitle: 'Actividades <em>para sumar a tu viaje.</em>',
  editorialExperiencesEmphasis: 'para sumar a tu viaje.',
  editorialExperiencesSubtitle:
    'Oficios, caminatas, cocina, mar, selva. Reservables sueltas o como add-on a cualquier paquete.',
  editorialExperiencesDurationLabel: 'Duración',
  editorialExperiencesSortLabel: 'Ordenar',
  editorialExperiencesSortPopular: 'Más populares',
  editorialExperiencesSortRating: 'Mejor calificadas',
  editorialExperiencesSortPriceAsc: 'Precio · menor a mayor',
  editorialExperiencesSortPriceDesc: 'Precio · mayor a menor',
  editorialExperiencesSortDuration: 'Duración · más cortas',
  editorialExperiencesRegionLabel: 'Región',
  editorialExperiencesLocationLabel: 'Ubicación',
  editorialExperiencesLevelLabel: 'Nivel',
  editorialExperiencesKeywordLabel: 'Palabra clave',
  editorialExperiencesKeywordPlaceholder: 'Buscar por palabra clave',
  editorialExperiencesClearAll: 'Limpiar todo',
  editorialExperiencesCountSuffix: 'experiencias',
  editorialExperiencesEmptyHeading: 'Nada con esos criterios',
  editorialExperiencesEmptyBody: 'Ajusta los filtros o empieza de cero.',
  editorialExperiencesClearLabel: 'Limpiar filtros',
  editorialExperiencesFromPrefix: 'Desde',
  editorialExperienceCategoryAll: 'Todas',
  editorialExperienceCategoryAdventure: 'Aventura',
  editorialExperienceCategoryGastronomy: 'Gastronomía',
  editorialExperienceCategoryCulture: 'Cultura',
  editorialExperienceCategoryNature: 'Naturaleza',
  editorialExperienceCategorySea: 'Mar',
  editorialExperienceCategoryWellness: 'Bienestar',
  editorialExperienceLevelEasy: 'Fácil',
  editorialExperienceLevelModerate: 'Moderado',
  editorialExperienceLevelDemanding: 'Exigente',
  editorialExperienceLevelIntense: 'Intenso',
  editorialExperienceDurationAny: 'Cualquiera',
  editorialExperienceDurationShort: 'Menos de 4h',
  editorialExperienceDurationHalfDay: 'Medio día',
  editorialExperienceDurationFullDay: 'Día completo',
  editorialExperienceDurationMultiDay: 'Multi-día',

  // Planners list page
  editorialPlannersListHeroEyebrow: 'Nuestros planners',
  editorialPlannersListHeroTitle: 'Una persona <em>que conoce su tierra.</em>',
  editorialPlannersListHeroEmphasis: 'que conoce su tierra.',
  editorialPlannersListHeroSubtitle:
    'Seis especialistas locales. Cada uno con una región, un oficio y 5–11 años diseñando viajes a medida por Colombia.',
  editorialPlannersListMetaTitle: 'Nuestros travel planners',
  editorialPlannersListMetaDescription:
    'Conoce al equipo de travel planners. Emparejamos tu viaje con la persona que más sabe de la región o experiencia que buscas.',
  editorialPlannersListIntroEyebrow: 'Por qué un planner local',
  editorialPlannersListIntroTitlePart1: 'No somos un motor de reservas —',
  editorialPlannersListIntroTitleEm: 'somos personas',
  editorialPlannersListIntroTitlePart2: 'que han caminado Colombia.',
  editorialPlannersListIntroBody:
    'Cuando reservas con nosotros, no hablas con un call center. Te emparejamos con la persona que vive en la región donde quieres ir, habla tu idioma, y conoce a los chefs, guías, y familias que harán tu viaje distinto al de los demás.',
  editorialPlannersListStatsPlanners: 'Planners locales',
  editorialPlannersListStatsRating: 'Reseñas promedio',
  editorialPlannersListStatsTrips: 'Viajes diseñados',
  editorialPlannersListSingular: 'planner',
  editorialPlannersListPlural: 'planners',
  editorialPlannersListSortBy: 'ordenar por',
  editorialPlannersListSortByValue: 'reseñas',
  editorialPlannersListCardViewProfile: 'Ver perfil',
  editorialPlannersListCardAvailable: 'Disponible',
  editorialPlannersListCardYearsSuffix: 'años',
  editorialMatchmakerHeadingEyebrow: 'Encuentra tu planner',
  editorialMatchmakerHeadingTitle: 'Dinos qué buscas',
  editorialMatchmakerHeadingTitleEm: 'y te emparejamos en 30 segundos.',
  editorialMatchmakerHeadingBody:
    'No todos los planners hacen todas las regiones. Cuéntanos dónde quieres ir y qué te mueve — nosotros sabemos quién firma ese viaje.',
  editorialMatchmakerHeadingCta: 'Hablar con mi match',
  editorialMatchmakerSubmit: 'Enviar',

  // Planner detail page
  editorialPlannerDetailBio: 'Sobre',
  editorialPlannerDetailDifferentiators: 'Lo que',
  editorialPlannerDetailDifferentiatorsEm: 'hace diferente',
  editorialPlannerDetailSpecialtiesLabel: 'Especialidades',
  editorialPlannerDetailRegionsLabel: 'Regiones',
  editorialPlannerDetailSignature: 'Viaje',
  editorialPlannerDetailSignatureEm: 'firma',
  editorialPlannerDetailSignatureSubLabel: 'ITINERARIO DESTACADO',
  editorialPlannerDetailHallmarks: 'Otros paquetes',
  editorialPlannerDetailHallmarksEm: 'que diseña',
  editorialPlannerDetailFacts: 'Detalles',
  editorialPlannerDetailFactsEm: 'personales',
  editorialPlannerDetailReviewsTitle: 'Lo que dicen',
  editorialPlannerDetailReviewsEm: 'viajeros de',
  editorialPlannerDetailOtherPlanners: 'Otros',
  editorialPlannerDetailOtherPlannersEm: 'planners',
  editorialPlannerDetailKpiExperience: 'Experiencia',
  editorialPlannerDetailKpiTrips: 'Viajes',
  editorialPlannerDetailKpiRating: 'Rating',
  editorialPlannerDetailKpiLanguages: 'Idiomas',
  editorialPlannerDetailRailSpeakWith: 'Hablar con',
  editorialPlannerDetailRailResponseTime: 'Tiempo de respuesta',
  editorialPlannerDetailRailFrom: 'Desde',
  editorialPlannerDetailRailLanguages: 'Idiomas',
  editorialPlannerDetailRailPrimaryCta: 'Escribir a',
  editorialPlannerDetailRailSecondaryCta: 'Pedir propuesta',
  editorialPlannerDetailRailFootnote:
    'Sin compromiso · Primera propuesta en <2h hábiles',
  editorialPlannerDetailSignaturePrimaryCta: 'Ver itinerario',
  editorialPlannerDetailSignatureSecondaryCta: 'Pedirle a',
  editorialPlannerDetailSignatureChip: 'Firma de',
  editorialPlannerDetailBioFallback:
    'Diseña viajes a medida por Colombia con ritmo propio, ojo para los detalles que no salen en las guías y una red local que sólo se construye caminando.',
  editorialPlannerDetailDefaultResponse: '~3 min',

  // Product detail breadcrumbs / package / activity / hotel overlays
  editorialBreadcrumbHome: 'Inicio',
  editorialBreadcrumbPackages: 'Paquetes',
  editorialBreadcrumbActivities: 'Actividades',
  editorialBreadcrumbHotels: 'Hoteles',
  editorialBreadcrumbBlog: 'Blog',
  editorialPackageDurationLabel: 'Duración',
  editorialPackageDestinationsLabel: 'Destinos',
  editorialPackageRatingLabel: 'Calificación',
  editorialPackageMapTitle: 'Ruta del viaje',
  editorialPackageStopsSuffix: 'paradas',
  editorialPackageTimelineEyebrow: 'Día a día',
  editorialPackageTimelineTitle: 'Itinerario detallado',
  editorialPackageHotelsEyebrow: 'Hospedaje',
  editorialPackageHotelsTitle: 'Hoteles incluidos',
  editorialPackageFlightsEyebrow: 'Vuelos',
  editorialPackageFlightsTitle: 'Vuelos incluidos',
  editorialActivityHighlightsEyebrow: 'Lo que vivirás',
  editorialActivityHighlightsTitle: 'Momentos destacados',
  editorialHotelAmenitiesEyebrow: 'Amenidades',
  editorialHotelAmenitiesTitle: 'Lo que este hotel ofrece',
  editorialHotelHighlightsEyebrow: 'Por qué elegirlo',
  editorialHotelHighlightsTitle: 'Aspectos destacados',
  editorialHotelStarsSuffix: 'estrellas',

  // Destinos listing / detail (editorial-v1 pages)
  editorialDestinosListEyebrow: 'EXPLORA',
  editorialDestinosListTitle: 'Ocho Colombias, <em>ocho ritmos.</em>',
  editorialDestinosListSubtitle:
    'Del mar de siete colores al desierto de La Guajira. Cada región con sus guías, sus sabores y su ritmo.',
  editorialDestinosListEmpty: 'No hay destinos disponibles en este momento.',
  editorialDestinosLegendHeading: 'Regiones',
  editorialDestinosRegionCaribe: 'Caribe',
  editorialDestinosRegionAndes: 'Andes',
  editorialDestinosRegionSelva: 'Selva',
  editorialDestinosRegionPacifico: 'Pacífico',
  editorialDestinoBreadcrumbDestinos: 'Destinos',
  editorialDestinoQuickFactRegion: 'Región',
  editorialDestinoQuickFactBestMonths: 'Mejores meses',
  editorialDestinoQuickFactAltitude: 'Altitud',
  editorialDestinoQuickFactAirport: 'Aeropuerto',
  editorialDestinoQuickFactHotels: 'Hoteles',
  editorialDestinoQuickFactActivities: 'Experiencias',
  editorialDestinoAboutTitle: 'Sobre',
  editorialDestinoActivitiesTitle: 'Qué hacer',
  editorialDestinoActivitiesEmphasis: 'en {name}.',
  editorialDestinoHotelsTitle: 'Dónde dormir',
  editorialDestinoHotelsEmphasis: 'en {name}.',
  editorialDestinoPackagesTitle: 'Paquetes que visitan',
  editorialDestinoPackagesEmphasis: '{name}.',
  editorialDestinoMapTitle: 'Ubicación en Colombia',
  editorialDestinoRelatedTitle: 'Otros destinos',
  editorialDestinoRelatedEmphasis: 'de la misma región.',
  editorialDestinoCtaTitle: 'Cotiza un viaje a',
  editorialDestinoCtaBody:
    'Un planner local arma tu itinerario a {name} en <2 horas. Sin cobros por cotizar.',
  editorialDestinoCtaPrimary: 'Cotizar viaje',
  editorialDestinoCtaSecondary: 'Hablar por WhatsApp',

  // Misc reused labels
  editorialShareLabel: 'Compartir',
  editorialSaveLabel: 'Guardar',
  editorialLoadMore: 'Cargar más',
  editorialFilterAll: 'Todos',
  editorialEmptyResults: 'No encontramos resultados',
  editorialNextStep: 'Continuar',
  editorialPrevStep: 'Anterior',
  editorialSubmitLead: 'Enviar',
  editorialVerifySMS: 'Verificar',
} as const;

export type PublicUiExtraTextKey = keyof typeof BASE_EXTRA_TEXTS;

const EN_US_OVERRIDES: Partial<Record<PublicUiExtraTextKey, string>> = {
  editorialHeaderQuoteCta: 'Get a quote',
  editorialHeaderWhatsappCta: 'Plan on WhatsApp',
  editorialHeaderNavAria: 'Main',
  editorialHeaderMobileMenuAria: 'Mobile menu',
  editorialHeaderMenuOpen: 'Open menu',
  editorialHeaderMenuClose: 'Close menu',
  editorialBreadcrumbHome: 'Home',
  editorialBreadcrumbPackages: 'Packages',
  editorialBreadcrumbActivities: 'Activities',
  editorialBreadcrumbHotels: 'Hotels',
  editorialBreadcrumbBlog: 'Blog',

  editorialFooterColDestinos: 'Destinations',
  editorialFooterColViajar: 'Travel',
  editorialFooterColAgencia: 'Agency',
  editorialFooterColNewsletter: 'Get stories',
  editorialFooterViewAll: 'View all',
  editorialFooterSearch: 'Search',
  editorialFooterEmailPlaceholder: 'you@email.com',
  editorialFooterEmailLabel: 'Email',
  editorialFooterSubscribe: 'Subscribe',
  editorialFooterNewsletterHint:
    'One monthly email with places we love and limited offers.',
  editorialFooterTaglineFallback: 'Travel deeper.',
  editorialFooterAboutFallback:
    'We are a local operator. We design journeys with local guides and family-run stays.',
  editorialFooterLegalPrivacy: 'Privacy',
  editorialFooterLegalTerms: 'Terms',
  editorialFooterLegalCancellation: 'Cancellation policy',

  editorialSwitcherHeading: 'Customize your',
  editorialSwitcherHeadingEmphasis: 'experience',
  editorialSwitcherDescription: 'Site language and price currency.',
  editorialSwitcherLanguageSubheading: 'Language',
  editorialSwitcherCurrencySubheading: 'Currency',
  editorialSwitcherSavedHint: 'Saved in this browser',
  editorialSwitcherTriggerAria: 'Open language and currency preferences',
  editorialSwitcherDialogAria: 'Customize your experience',
  editorialSwitcherLanguageItemAria: 'Change language',
  editorialSwitcherCurrencyItemAria: 'Change currency',
  editorialSwitcherLoadingPrefix: 'Loading in',

  editorialHeroEyebrowFallback: 'DISCOVER · FEEL · CONNECT',
  editorialHeroSideListLabel: 'Destination of the month',
  editorialHeroSlidesAria: 'Featured images',
  editorialHeroPresenting: 'Now showing',
  editorialHeroDotsAria: 'Select slide',
  editorialHeroSlidePrefix: 'Slide',
  editorialHeroWhatsappMeta: 'Replies in about 3 min · Human planner',

  editorialSearchPlaceholderDestino: 'Caribbean · Colombia',
  editorialSearchPlaceholderFechas: 'October 2026 · 7 nights',
  editorialSearchPlaceholderViajeros: '2 travelers',
  editorialSearchSubmit: 'Search',
  editorialSearchDestinoLabel: 'Destination',
  editorialSearchWhenLabel: 'When',
  editorialSearchFechasAria: 'Travel dates',
  editorialSearchViajerosLabel: 'Travelers',
  editorialDestinationsSubtitle: 'Magical places that capture the essence of Colombia. From pristine beaches to snow-capped peaks.',
  editorialDestinationsTitleFallback: 'Destinations',
  editorialDestinationsViewList: 'List',
  editorialDestinationsViewMap: 'Map',
  editorialDestinationsMapAriaFallback: 'Interactive map of destinations in Colombia',
  editorialDestinosListEyebrow: 'EXPLORE',
  editorialDestinosListTitle: 'Eight Colombias, <em>eight rhythms.</em>',
  editorialDestinosListSubtitle:
    'From the sea of seven colors to the La Guajira desert. Every region has its own guides, flavors, and rhythm.',
  editorialDestinosListEmpty: 'No destinations available right now.',
  editorialDestinosLegendHeading: 'Regions',
  editorialDestinosRegionCaribe: 'Caribbean',
  editorialDestinosRegionAndes: 'Andes',
  editorialDestinosRegionSelva: 'Jungle',
  editorialDestinosRegionPacifico: 'Pacific',
  editorialDestinoBreadcrumbDestinos: 'Destinations',
  editorialDestinoQuickFactRegion: 'Region',
  editorialDestinoQuickFactBestMonths: 'Best months',
  editorialDestinoQuickFactAltitude: 'Altitude',
  editorialDestinoQuickFactAirport: 'Airport',
  editorialDestinoQuickFactHotels: 'Hotels',
  editorialDestinoQuickFactActivities: 'Experiences',
  editorialDestinoAboutTitle: 'About',
  editorialDestinoActivitiesTitle: 'Things to do',
  editorialDestinoActivitiesEmphasis: 'in {name}.',
  editorialDestinoHotelsTitle: 'Where to stay',
  editorialDestinoHotelsEmphasis: 'in {name}.',
  editorialDestinoPackagesTitle: 'Trips that visit',
  editorialDestinoPackagesEmphasis: '{name}.',
  editorialDestinoMapTitle: 'Location in Colombia',
  editorialDestinoRelatedTitle: 'Other destinations',
  editorialDestinoRelatedEmphasis: 'in the same region.',
  editorialDestinoCtaTitle: 'Plan a trip to',
  editorialDestinoCtaBody:
    'A local planner builds your itinerary to {name} in under 2 hours. No fee to request a quote.',
  editorialDestinoCtaPrimary: 'Get a quote',
  editorialDestinoCtaSecondary: 'Chat on WhatsApp',
  sectionViewHotel: 'View hotel',
  editorialHotelsEyebrow: 'HOTELS',
  editorialHotelsTitle: 'Stays <em>curated by city.</em>',
  editorialHotelsSubtitle: 'Fincas, boutiques, and resorts selected by our planners. Switch categories without rebuilding the whole trip.',
  editorialHotelsCityLabel: 'City',
  editorialHotelsStarsLabel: 'Stars',
  editorialHotelsAmenityLabel: 'Amenities',
  editorialHotelsViewList: 'List',
  editorialHotelsViewMap: 'Map',
  editorialHotelsViewAria: 'Hotels view',
  editorialHotelsLoadMore: 'Load more',
  editorialHotelsEmptyHeading: 'No hotels match those filters',
  editorialHotelsEmptyBody: 'Try widening the range or clearing filters.',
  editorialHotelsEmptyCta: 'Clear filters',
  editorialHotelsClearLink: 'clear filters',
  editorialHotelsCountSingular: 'hotel',
  editorialHotelsCountPlural: 'hotels',
  editorialHotelsCountSeparator: 'of',

  // WhatsApp Flow
  waflowCloseBubble: 'Close bubble',
  waflowFabTitle: 'Planning a trip?',
  waflowFabSubtitlePrefix: 'Chat with a planner — replies in ~',
  waflowFabAria: 'Chat on WhatsApp with a planner',
  waflowDialogAria: 'Plan my trip',
  waflowClose: 'Close',
  waflowOnlineNow: 'Planners online now',
  waflowOnline: 'Planners online',
  waflowResponsePrefix: 'Reply in ~',
  waflowSkipToChat: 'I prefer to explain it in chat →',
  waflowStepPrefix: 'Step',
  waflowStepOf: 'of',
  waflowHeroATitle: 'Tell us <em>what you dream of.</em>',
  waflowHeroASubtitle: 'We contact you on WhatsApp with a human planner. Average reply time is 3 min.',
  waflowHeroBTitlePrefix: 'Travel to',
  waflowHeroBSubtitle: 'Tell us the basics and your planner will prepare a proposal within 24h.',
  waflowHeroDTitleSuffix: 'make it yours.',
  waflowHeroDSubtitle: 'We adjust dates, hotels, and activities until it becomes the trip you want.',
  waflowFromPrefix: 'from',
  waflowChangeCountryAriaPrefix: 'Change country, selected',
  waflowCountrySearch: 'Search country or calling code',
  waflowCountriesAria: 'Countries',
  waflowCountryNotFound: 'We could not find that country',
  waflowSubmitA: 'Send and open WhatsApp',
  waflowSubmitBPrefix: 'Plan my trip to',
  waflowSubmitD: 'Continue with this package',
  waflowPhoneErrorPrefix: 'Enter your WhatsApp with 7 to 15 digits. You can include',
  waflowPhoneErrorSuffix: 'or leave only the local number.',
  waflowFallbackName: 'Traveler',
  waflowPhoneLabel: 'Your WhatsApp',
  waflowRequired: 'Required',
  waflowPhonePlaceholder: 'number',
  waflowWhenLabel: 'When would you like to travel?',
  waflowApprox: 'Approx',
  waflowNameLabel: 'Your name',
  waflowOptional: 'Optional',
  waflowNamePlaceholder: 'What should we call you?',
  waflowSending: 'Sending…',
  waflowPrivacy: 'Your number is used only for this trip. No spam. No automated calls.',
  waflowConfirmationTitle: 'WhatsApp opened in a new tab.',
  waflowConfirmationBodyPrefix: 'If it did not open, tap the green button. Your planner replies on average in',
  waflowConfirmationBodySuffix: 'and will also message you from our side.',
  waflowOpenWhatsapp: 'Open WhatsApp',
  waflowKeepExploring: 'Keep exploring',
  waflowRefLabel: 'Ref:',
  editorialExperiencesEyebrow: 'ACTIVITIES',
  editorialExperiencesTitle: 'Activities <em>to add to your trip.</em>',
  editorialExperiencesEmphasis: 'to add to your trip.',
  editorialExperiencesSubtitle: 'Crafts, hikes, cooking, sea, jungle. Bookable individually or as an add-on to any package.',
  editorialExperiencesEyebrowFallback: 'ACTIVITIES',

  editorialPackagesEyebrowFallback: 'PACKAGES',
  editorialPackagesTitleFallback: 'Trips <em>across Colombia.</em>',
  editorialPackagesSubtitleFallback: 'Journeys designed by local planners. Flexible and adjustable as the starting point for your trip.',
  editorialPackagesAllTab: 'All',
  editorialPackagesPopular: 'POPULAR',
  editorialPackagesFromPrefix: 'FROM',
  editorialPackagesConsultPrice: 'Ask for price',
  editorialPackagesCtaFallback: 'VIEW PACKAGE',
  editorialPackagesEmpty: 'No packages available',
  editorialPackagesFiltersAria: 'Package filters',
  editorialPackagesRailAria: 'Packages carousel',
  editorialPackagesWord: 'packages',
  editorialPackageWord: 'package',
  editorialPackagesClearLabel: 'Clear',
  editorialPackagesClearLink: 'clear filters',
  editorialPackagesCountryLabel: 'Country',
  editorialPackagesLocationLabel: 'Location',
  editorialPackagesKeywordLabel: 'Keyword',
  editorialPackagesKeywordPlaceholder: 'Search by keyword',
  editorialPackagesDurationLabel: 'Duration',
  editorialPackagesDurationAny: 'Any',
  editorialPackagesViewList: 'List',
  editorialPackagesViewMap: 'Map',
  editorialPackagesViewAria: 'Packages view',
  editorialPackagesLoadMore: 'Load more',
  editorialPackagesEmptyHeading: 'No packages match those filters',
  editorialPackagesEmptyBody: 'Try widening the range or clearing filters.',
  editorialPackagesEmptyCta: 'Clear filters',
  editorialPackagesFromPerPerson: 'From · per person',
  editorialPackagesViewPackageShort: 'View',
  editorialPackagesCountSeparator: 'of',
  editorialPackagesPopularBadge: 'Popular',
  editorialExperiencesSortLabel: 'Sort by',
  editorialExperiencesSortPopular: 'Most popular',
  editorialExperiencesSortRating: 'Top rated',
  editorialExperiencesSortPriceAsc: 'Price · low to high',
  editorialExperiencesSortPriceDesc: 'Price · high to low',
  editorialExperiencesSortDuration: 'Duration · shortest first',
  editorialExperiencesRegionLabel: 'Region',
  editorialExperiencesLocationLabel: 'Location',
  editorialExperiencesLevelLabel: 'Level',
  editorialExperiencesKeywordLabel: 'Keyword',
  editorialExperiencesKeywordPlaceholder: 'Search by keyword',
  editorialExperiencesClearAll: 'Clear all',
  editorialExperiencesCountSuffix: 'experiences',
  editorialExperiencesEmptyHeading: 'No matches',
  editorialExperiencesEmptyBody: 'Adjust your filters or start over.',
  editorialExperiencesClearLabel: 'Clear filters',
  editorialExperiencesFromPrefix: 'From',
  editorialExperienceCategoryAll: 'All',
  editorialExperienceCategoryAdventure: 'Adventure',
  editorialExperienceCategoryGastronomy: 'Food',
  editorialExperienceCategoryCulture: 'Culture',
  editorialExperienceCategoryNature: 'Nature',
  editorialExperienceCategorySea: 'Sea',
  editorialExperienceCategoryWellness: 'Wellness',
  editorialExperienceLevelEasy: 'Easy',
  editorialExperienceLevelModerate: 'Moderate',
  editorialExperienceLevelDemanding: 'Demanding',
  editorialExperienceLevelIntense: 'Intense',
  editorialExperienceDurationAny: 'Any',
  editorialExperienceDurationShort: 'Under 4h',
  editorialExperienceDurationHalfDay: 'Half day',
  editorialExperienceDurationFullDay: 'Full day',
  editorialExperienceDurationMultiDay: 'Multi-day',

  editorialBlogListEyebrow: 'Blog',
  editorialBlogListTitle: 'Stories <em>from the inside.</em>',
  editorialBlogListEmphasis: 'from the inside.',
  editorialBlogListSubtitle:
    'Written by planners who travel Colombia every month. Guides, itineraries, crafts, and hidden corners.',
  editorialBlogListAllTab: 'All',
  editorialBlogEmptyHeading: 'No stories found',
  editorialBlogEmptyBody: 'Try another category or search term.',
  editorialBlogLoadMore: 'Load more stories',
  editorialBlogPrev: 'Previous',
  editorialBlogNext: 'Next',
  editorialBlogReadCta: 'Read article',
  editorialBlogReadingSuffix: 'min read',
  editorialBlogPaginationAria: 'Blog pagination',
  editorialBlogToolbarAria: 'Blog filters',
  editorialBlogSearchAria: 'Search stories',
  editorialBlogSearchPlaceholder: 'Search stories...',

  editorialPlannersEyebrowFallback: 'Your planner',
  editorialPlannersTitleFallback: 'One person who knows your trip from start to finish.',
  editorialPlannersSubtitleFallback:
    'We match your profile with the planner who best knows the region or experience you want.',
  editorialPlannersViewAll: 'View all',
  editorialPlannersQuoteFallback:
    'We design tailor-made trips step by step.',
  editorialPlannersAvailable: 'Available',
  editorialPlannersViewProfile: 'View profile',
  editorialPlannersYearsText: 'years designing tailor-made trips.',
  editorialPlannersEmpty: 'No travel planners are published yet.',
  editorialRoleAgent: 'Travel Agent',
  editorialRolePlanner: 'Travel Planner',
  editorialRoleOperations: 'Operations',
  editorialRoleManager: 'Manager',
  editorialRoleSales: 'Sales',
  editorialPlannersListHeroEyebrow: 'Our planners',
  editorialPlannersListHeroTitle: 'A person <em>who knows their land.</em>',
  editorialPlannersListHeroEmphasis: 'who knows their land.',
  editorialPlannersListHeroSubtitle:
    'Local specialists. Each one has a region, a craft, and years designing tailor-made trips across Colombia.',
  editorialPlannersListMetaTitle: 'Our travel planners',
  editorialPlannersListMetaDescription:
    'Meet our travel planners. We match your trip with the person who best knows the region or experience you want.',
  editorialPlannersListIntroEyebrow: 'Why a local planner',
  editorialPlannersListIntroTitlePart1: 'We are not a booking engine —',
  editorialPlannersListIntroTitleEm: 'we are people',
  editorialPlannersListIntroTitlePart2: 'who have traveled Colombia.',
  editorialPlannersListIntroBody:
    'When you book with us, you do not talk to a call center. We match you with the person who lives in the region you want to visit, speaks your language, and knows the chefs, guides, and families who make your trip different.',
  editorialPlannersListStatsPlanners: 'Local planners',
  editorialPlannersListStatsRating: 'Average reviews',
  editorialPlannersListStatsTrips: 'Trips designed',
  editorialPlannersListSingular: 'planner',
  editorialPlannersListPlural: 'planners',
  editorialPlannersListSortBy: 'sort by',
  editorialPlannersListSortByValue: 'reviews',
  editorialPlannersListCardViewProfile: 'View profile',
  editorialPlannersListCardAvailable: 'Available',
  editorialPlannersListCardYearsSuffix: 'years',
  editorialMatchmakerHeadingEyebrow: 'Find your planner',
  editorialMatchmakerHeadingTitle: 'Tell us what you want',
  editorialMatchmakerHeadingTitleEm: 'and we will match you in 30 seconds.',
  editorialMatchmakerHeadingBody:
    'Not every planner covers every region. Tell us where you want to go and what moves you, and we know who should design that trip.',
  editorialMatchmakerHeadingCta: 'Talk to my match',
  editorialMatchmakerSubmit: 'Send',
  editorialMatchmakerGroupQuestion: 'Who are you traveling with?',
  editorialMatchmakerRegionQuestion: 'Which region are you visiting?',
  editorialMatchmakerStyleQuestion: 'What travel style?',
  editorialMatchmakerMatchLabel: 'Suggested match',

  editorialTrustLiveLabel: 'Planners online',
  editorialTrustResponsePrefix: 'reply in about ',
  editorialTrustResponseFallback: 'reply soon',
  editorialTrustCertified: 'certified local operator',
  editorialTrustRatingAverage: 'average rating',
  editorialTrustRecommendation: 'travelers would recommend us',
  editorialTrustYearsSuffix: 'years',
  editorialTrustSatisfactionSuffix: 'satisfaction',
  editorialTrustHumanReview: 'Human-reviewed',
  editorialTrustHumanReviewBody: 'every itinerary',
  editorialTrustAriaLabel: 'Trust and credibility',
  editorialTrustVerifiedSuffix: 'verified reviews',
  editorialTrustLogosLabel: 'Recognized by',
  editorialPackageDurationLabel: 'Duration',
  editorialPackageDestinationsLabel: 'Destinations',
  editorialPackageRatingLabel: 'Rating',
};
const PT_BR_OVERRIDES: Partial<Record<PublicUiExtraTextKey, string>> = {
  editorialHeaderQuoteCta: 'Solicitar cotação',
  editorialHeaderWhatsappCta: 'Planejar pelo WhatsApp',
  editorialHeaderNavAria: 'Principal',
  editorialHeaderMobileMenuAria: 'Menu móvel',
  editorialHeaderMenuOpen: 'Abrir menu',
  editorialHeaderMenuClose: 'Fechar menu',
  editorialFooterViewAll: 'Ver todos',
  editorialFooterSearch: 'Buscar',
  editorialFooterLegalPrivacy: 'Política de privacidade',
  editorialFooterLegalTerms: 'Termos e condições',
  editorialFooterLegalCancellation: 'Política de cancelamento',
  editorialFooterColDestinos: 'Destinos',
  editorialFooterColViajar: 'Viajar',
  editorialFooterColAgencia: 'Agência',
  editorialFooterColNewsletter: 'Newsletter',
  editorialFooterNewsletterHint: 'Um email por mês com lugares que amamos e descontos.',
  editorialFooterEmailLabel: 'Email',
  editorialFooterEmailPlaceholder: 'voce@email.com',
  editorialFooterSubscribe: 'Inscrever-se',
  editorialSwitcherDescription: 'Idioma do site e moeda dos preços.',
  editorialSwitcherTriggerAria: 'Abrir preferências de idioma e moeda',
  editorialPackagesCtaFallback: 'VER PACOTE',
  editorialPackagesWord: 'pacotes',
  editorialPackageWord: 'pacote',
  editorialPackagesClearLabel: 'Limpar',
  editorialPackagesClearLink: 'limpar filtros',
  editorialPackagesCountryLabel: 'País',
  editorialPackagesLocationLabel: 'Localização',
  editorialPackagesKeywordLabel: 'Palavra-chave',
  editorialPackagesKeywordPlaceholder: 'Buscar por palavra-chave',
  editorialPackagesDurationLabel: 'Duração',
  editorialPackagesDurationAny: 'Qualquer',
  editorialPackagesViewList: 'Lista',
  editorialPackagesViewMap: 'Mapa',
  editorialPackagesViewAria: 'Vista de pacotes',
  editorialPackagesLoadMore: 'Carregar mais',
  editorialPackagesEmptyHeading: 'Nenhum pacote corresponde aos filtros',
  editorialPackagesEmptyBody: 'Tente ampliar os filtros ou limpá-los.',
  editorialPackagesEmptyCta: 'Limpar filtros',
  editorialPackagesFromPerPerson: 'A partir de · por pessoa',
  editorialPackagesViewPackageShort: 'Ver',
  editorialPackagesCountSeparator: 'de',
  editorialPackagesPopularBadge: 'Popular',
  editorialDestinoQuickFactHotels: 'Hotéis',
  editorialActivitiesWord: 'atividades',
  editorialHotelsEyebrow: 'HOTÉIS',
  editorialHotelsTitle: 'Estadias <em>curadas por cidade.</em>',
  editorialHotelsSubtitle: 'Fincas, boutiques e resorts selecionados por nossos planners.',
  editorialHotelsCityLabel: 'Cidade',
  editorialHotelsStarsLabel: 'Estrelas',
  editorialHotelsAmenityLabel: 'Serviços',
  editorialHotelsViewList: 'Lista',
  editorialHotelsViewMap: 'Mapa',
  editorialHotelsViewAria: 'Vista de hotéis',
  editorialHotelsLoadMore: 'Carregar mais',
  editorialHotelsEmptyHeading: 'Nenhum hotel corresponde aos filtros',
  editorialHotelsEmptyBody: 'Tente ampliar os filtros ou limpá-los.',
  editorialHotelsEmptyCta: 'Limpar filtros',
  editorialHotelsClearLink: 'limpar filtros',
  editorialHotelsCountSingular: 'hotel',
  editorialHotelsCountPlural: 'hotéis',
  editorialHotelsCountSeparator: 'de',
  waflowFabTitle: 'Planejando uma viagem?',
  waflowFabSubtitlePrefix: 'Converse com um planner — responde em ~',
  waflowFabAria: 'Chat no WhatsApp com um planner',
  waflowDialogAria: 'Planejar minha viagem',
  waflowClose: 'Fechar',
  waflowOnlineNow: 'Planners online agora',
  waflowOnline: 'Planners online',
  waflowResponsePrefix: 'Respondem em ~',
  waflowSkipToChat: 'Prefiro explicar no chat →',
  waflowSubmitA: 'Enviar e abrir WhatsApp',
  waflowSubmitBPrefix: 'Planejar minha viagem para',
  waflowSubmitD: 'Continuar com este pacote',
  waflowPhoneLabel: 'Seu WhatsApp',
  waflowRequired: 'Obrigatório',
  waflowNameLabel: 'Seu nome',
  waflowOptional: 'Opcional',
  waflowSending: 'Enviando…',
  waflowPrivacy: 'Seu número será usado apenas para esta viagem. Sem spam.',
  waflowConfirmationTitle: 'O WhatsApp abriu em uma nova aba.',
  waflowOpenWhatsapp: 'Abrir WhatsApp',
  waflowKeepExploring: 'Continuar explorando',
};

const FR_FR_OVERRIDES: Partial<Record<PublicUiExtraTextKey, string>> = {
  editorialHeaderQuoteCta: 'Demander un devis',
  editorialHeaderWhatsappCta: 'Planifier sur WhatsApp',
  editorialHeaderNavAria: 'Principal',
  editorialHeaderMobileMenuAria: 'Menu mobile',
  editorialHeaderMenuOpen: 'Ouvrir le menu',
  editorialHeaderMenuClose: 'Fermer le menu',
  editorialFooterViewAll: 'Voir tout',
  editorialFooterSearch: 'Rechercher',
  editorialFooterLegalPrivacy: 'Politique de confidentialité',
  editorialFooterLegalTerms: 'Conditions générales',
  editorialFooterLegalCancellation: "Politique d'annulation",
  editorialFooterColDestinos: 'Destinations',
  editorialFooterColViajar: 'Voyager',
  editorialFooterColAgencia: 'Agence',
  editorialFooterColNewsletter: 'Newsletter',
  editorialFooterNewsletterHint: 'Un email par mois avec des lieux que nous aimons et des réductions.',
  editorialFooterEmailLabel: 'Email',
  editorialFooterEmailPlaceholder: 'vous@email.com',
  editorialFooterSubscribe: 'S’inscrire',
  editorialSwitcherDescription: 'Langue du site et devise des prix.',
  editorialSwitcherTriggerAria: 'Ouvrir les préférences de langue et devise',
  editorialBreadcrumbPackages: 'Forfaits',
  sectionPackagesWord: 'forfaits',
  sectionPackagesTitle: 'Forfaits voyage',
  sectionPackagesEyebrow: 'Séjours sélectionnés',
  sectionPackagesViewAll: 'Voir tous les forfaits',
  sectionPackagesCircuit: 'Circuit :',
  sectionViewPackage: 'Voir le forfait',
  editorialPackagesEyebrowFallback: 'FORFAITS',
  editorialPackagesTitleFallback: 'Voyages <em>dans toute la Colombie.</em>',
  editorialPackagesSubtitleFallback: 'Itinéraires conçus par des planners locaux. Flexibles et personnalisables comme point de départ de votre voyage.',
  editorialPackagesAllTab: 'Tous',
  editorialPackagesPopular: 'POPULAIRE',
  editorialPackagesFromPrefix: 'À PARTIR DE',
  editorialPackagesConsultPrice: 'Demander le prix',
  editorialPackagesCtaFallback: 'VOIR LE FORFAIT',
  editorialPackagesWord: 'forfaits',
  editorialPackageWord: 'forfait',
  editorialPackagesClearLabel: 'Effacer',
  editorialPackagesClearLink: 'effacer les filtres',
  editorialPackagesCountryLabel: 'Pays',
  editorialPackagesLocationLabel: 'Lieu',
  editorialPackagesKeywordLabel: 'Mot-clé',
  editorialPackagesKeywordPlaceholder: 'Rechercher par mot-clé',
  editorialPackagesDurationLabel: 'Durée',
  editorialPackagesDurationAny: 'Toutes',
  editorialPackagesViewList: 'Liste',
  editorialPackagesViewMap: 'Carte',
  editorialPackagesViewAria: 'Vue des forfaits',
  editorialPackagesLoadMore: 'Charger plus',
  editorialPackagesEmptyHeading: 'Aucun forfait ne correspond aux filtres',
  editorialPackagesEmptyBody: 'Essayez d’élargir ou d’effacer les filtres.',
  editorialPackagesEmptyCta: 'Effacer les filtres',
  editorialPackagesFromPerPerson: 'À partir de · par personne',
  editorialPackagesViewPackageShort: 'Voir',
  editorialPackagesCountSeparator: 'sur',
  editorialPackagesPopularBadge: 'Populaire',
  editorialDestinoQuickFactHotels: 'Hôtels',
  editorialActivitiesWord: 'activités',
  editorialHotelsEyebrow: 'HÔTELS',
  editorialHotelsTitle: 'Séjours <em>sélectionnés par ville.</em>',
  editorialHotelsSubtitle: 'Fincas, boutiques et resorts sélectionnés par nos planners.',
  editorialHotelsCityLabel: 'Ville',
  editorialHotelsStarsLabel: 'Étoiles',
  editorialHotelsAmenityLabel: 'Services',
  editorialHotelsViewList: 'Liste',
  editorialHotelsViewMap: 'Carte',
  editorialHotelsViewAria: 'Vue des hôtels',
  editorialHotelsLoadMore: 'Charger plus',
  editorialHotelsEmptyHeading: 'Aucun hôtel ne correspond aux filtres',
  editorialHotelsEmptyBody: 'Essayez d’élargir ou d’effacer les filtres.',
  editorialHotelsEmptyCta: 'Effacer les filtres',
  editorialHotelsClearLink: 'effacer les filtres',
  editorialHotelsCountSingular: 'hôtel',
  editorialHotelsCountPlural: 'hôtels',
  editorialHotelsCountSeparator: 'sur',
  waflowFabTitle: 'Vous planifiez un voyage ?',
  waflowFabSubtitlePrefix: 'Discutez avec un planner — réponse en ~',
  waflowFabAria: 'Chat WhatsApp avec un planner',
  waflowDialogAria: 'Planifier mon voyage',
  waflowClose: 'Fermer',
  waflowOnlineNow: 'Planners en ligne maintenant',
  waflowOnline: 'Planners en ligne',
  waflowResponsePrefix: 'Réponse en ~',
  waflowSkipToChat: 'Je préfère l’expliquer dans le chat →',
  waflowSubmitA: 'Envoyer et ouvrir WhatsApp',
  waflowSubmitBPrefix: 'Planifier mon voyage à',
  waflowSubmitD: 'Continuer avec ce forfait',
  waflowPhoneLabel: 'Votre WhatsApp',
  waflowRequired: 'Obligatoire',
  waflowNameLabel: 'Votre nom',
  waflowOptional: 'Optionnel',
  waflowSending: 'Envoi…',
  waflowPrivacy: 'Votre numéro est utilisé uniquement pour ce voyage. Pas de spam.',
  waflowConfirmationTitle: 'WhatsApp s’est ouvert dans un nouvel onglet.',
  waflowOpenWhatsapp: 'Ouvrir WhatsApp',
  waflowKeepExploring: 'Continuer à explorer',
};

const DE_DE_OVERRIDES: Partial<Record<PublicUiExtraTextKey, string>> = {
  editorialHeaderQuoteCta: 'Reiseangebot anfragen',
  editorialHeaderWhatsappCta: 'Per WhatsApp planen',
  editorialHeaderNavAria: 'Hauptnavigation',
  editorialHeaderMobileMenuAria: 'Mobiles Menü',
  editorialHeaderMenuOpen: 'Menü öffnen',
  editorialHeaderMenuClose: 'Menü schließen',
  editorialFooterViewAll: 'Alle anzeigen',
  editorialFooterSearch: 'Suchen',
  editorialFooterLegalPrivacy: 'Datenschutzrichtlinie',
  editorialFooterLegalTerms: 'Allgemeine Geschäftsbedingungen',
  editorialFooterLegalCancellation: 'Stornierungsbedingungen',
  editorialFooterColDestinos: 'Reiseziele',
  editorialFooterColViajar: 'Reisen',
  editorialFooterColAgencia: 'Agentur',
  editorialFooterColNewsletter: 'Newsletter',
  editorialFooterNewsletterHint: 'Eine E-Mail pro Monat mit Orten, die wir lieben, und Rabatten.',
  editorialFooterEmailLabel: 'E-Mail',
  editorialFooterEmailPlaceholder: 'sie@email.com',
  editorialFooterSubscribe: 'Abonnieren',
  editorialSwitcherDescription: 'Websitesprache und Preiswährung.',
  editorialSwitcherTriggerAria: 'Sprach- und Währungseinstellungen öffnen',
  editorialPackagesCtaFallback: 'PAKET ANSEHEN',
  editorialPackagesWord: 'Pakete',
  editorialPackageWord: 'Paket',
  editorialPackagesClearLabel: 'Löschen',
  editorialPackagesClearLink: 'Filter löschen',
  editorialPackagesCountryLabel: 'Land',
  editorialPackagesLocationLabel: 'Ort',
  editorialPackagesKeywordLabel: 'Suchwort',
  editorialPackagesKeywordPlaceholder: 'Nach Suchwort suchen',
  editorialPackagesDurationLabel: 'Dauer',
  editorialPackagesDurationAny: 'Beliebig',
  editorialPackagesViewList: 'Liste',
  editorialPackagesViewMap: 'Karte',
  editorialPackagesViewAria: 'Paketansicht',
  editorialPackagesLoadMore: 'Mehr laden',
  editorialPackagesEmptyHeading: 'Keine Pakete entsprechen den Filtern',
  editorialPackagesEmptyBody: 'Erweitern oder löschen Sie die Filter.',
  editorialPackagesEmptyCta: 'Filter löschen',
  editorialPackagesFromPerPerson: 'Ab · pro Person',
  editorialPackagesViewPackageShort: 'Ansehen',
  editorialPackagesCountSeparator: 'von',
  editorialPackagesPopularBadge: 'Beliebt',
  editorialDestinoQuickFactHotels: 'Hotels',
  editorialActivitiesWord: 'Aktivitäten',
  editorialHotelsEyebrow: 'HOTELS',
  editorialHotelsTitle: 'Aufenthalte <em>nach Stadt kuratiert.</em>',
  editorialHotelsSubtitle: 'Fincas, Boutique-Hotels und Resorts, ausgewählt von unseren Plannern.',
  editorialHotelsCityLabel: 'Stadt',
  editorialHotelsStarsLabel: 'Sterne',
  editorialHotelsAmenityLabel: 'Services',
  editorialHotelsViewList: 'Liste',
  editorialHotelsViewMap: 'Karte',
  editorialHotelsViewAria: 'Hotelansicht',
  editorialHotelsLoadMore: 'Mehr laden',
  editorialHotelsEmptyHeading: 'Keine Hotels entsprechen den Filtern',
  editorialHotelsEmptyBody: 'Erweitern oder löschen Sie die Filter.',
  editorialHotelsEmptyCta: 'Filter löschen',
  editorialHotelsClearLink: 'Filter löschen',
  editorialHotelsCountSingular: 'Hotel',
  editorialHotelsCountPlural: 'Hotels',
  editorialHotelsCountSeparator: 'von',
  waflowFabTitle: 'Planen Sie eine Reise?',
  waflowFabSubtitlePrefix: 'Chatten Sie mit einem Planner — Antwort in ~',
  waflowFabAria: 'WhatsApp-Chat mit einem Planner',
  waflowDialogAria: 'Meine Reise planen',
  waflowClose: 'Schließen',
  waflowOnlineNow: 'Planner jetzt online',
  waflowOnline: 'Planner online',
  waflowResponsePrefix: 'Antwort in ~',
  waflowSkipToChat: 'Ich erkläre es lieber im Chat →',
  waflowSubmitA: 'Senden und WhatsApp öffnen',
  waflowSubmitBPrefix: 'Meine Reise planen nach',
  waflowSubmitD: 'Mit diesem Paket fortfahren',
  waflowPhoneLabel: 'Ihr WhatsApp',
  waflowRequired: 'Erforderlich',
  waflowNameLabel: 'Ihr Name',
  waflowOptional: 'Optional',
  waflowSending: 'Wird gesendet…',
  waflowPrivacy: 'Ihre Nummer wird nur für diese Reise verwendet. Kein Spam.',
  waflowConfirmationTitle: 'WhatsApp wurde in einem neuen Tab geöffnet.',
  waflowOpenWhatsapp: 'WhatsApp öffnen',
  waflowKeepExploring: 'Weiter erkunden',
};

const EXTRA_TEXTS_BY_LOCALE: Record<
  SupportedPublicUiLocale,
  Record<PublicUiExtraTextKey, string>
> = {
  'es-CO': { ...BASE_EXTRA_TEXTS },
  'en-US': { ...BASE_EXTRA_TEXTS, ...EN_US_OVERRIDES },
  'pt-BR': { ...BASE_EXTRA_TEXTS, ...PT_BR_OVERRIDES },
  'fr-FR': { ...BASE_EXTRA_TEXTS, ...EN_US_OVERRIDES, ...FR_FR_OVERRIDES },
  'de-DE': { ...BASE_EXTRA_TEXTS, ...EN_US_OVERRIDES, ...DE_DE_OVERRIDES },
};

export function getPublicUiExtraText(
  localeLike: string | null | undefined,
  key: PublicUiExtraTextKey,
): string {
  const locale = resolvePublicUiLocale(localeLike);
  return EXTRA_TEXTS_BY_LOCALE[locale][key];
}

export function getPublicUiExtraTextGetter(localeLike: string | null | undefined) {
  const locale = resolvePublicUiLocale(localeLike);
  const dictionary = EXTRA_TEXTS_BY_LOCALE[locale];
  return (key: PublicUiExtraTextKey): string => dictionary[key];
}
